/* CreateDate: 10/06/2006 14:24:58.447 , ModifyDate: 05/08/2010 02:30:09.787 */
GO
CREATE TABLE [dbo].[scrubbedtest](
	[phone] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[lastcontact] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dnc] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ebr] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[rowid] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_scrubbedtest] PRIMARY KEY CLUSTERED
(
	[rowid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_phone] ON [dbo].[scrubbedtest]
(
	[phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
