/* CreateDate: 09/25/2006 15:11:53.100 , ModifyDate: 05/08/2010 02:30:08.780 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DNC_OUT](
	[DNCOutID] [int] IDENTITY(1,1) NOT NULL,
	[Phone] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastContactDate] [datetime] NULL,
	[LastSaleDate] [datetime] NULL,
	[FileCreationDate] [datetime] NULL,
	[DNC] [bit] NULL,
	[DNCCode] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBRExpiration] [datetime] NULL,
	[Sent] [bit] NULL,
	[LastUpdate] [datetime] NULL,
	[Timestamp] [datetime] NULL,
 CONSTRAINT [PK_DNC_OUT] PRIMARY KEY CLUSTERED
(
	[DNCOutID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [DNC_Out_Phone_Ix] ON [dbo].[DNC_OUT]
(
	[Phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DNC_OUT] ADD  CONSTRAINT [DF_DNC_OUT_DNC]  DEFAULT (0) FOR [DNC]
GO
ALTER TABLE [dbo].[DNC_OUT] ADD  CONSTRAINT [DF_DNC_OUT_Sent]  DEFAULT (0) FOR [Sent]
GO
ALTER TABLE [dbo].[DNC_OUT] ADD  CONSTRAINT [DF_DNC_OUT_LastUpdate]  DEFAULT (getdate()) FOR [LastUpdate]
GO
ALTER TABLE [dbo].[DNC_OUT] ADD  CONSTRAINT [DF_DNC_OUT_Timestamp]  DEFAULT (getdate()) FOR [Timestamp]
GO
