/* CreateDate: 09/03/2021 09:37:07.523 , ModifyDate: 09/03/2021 09:37:07.523 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [sp_MSupd_bi_mktg_ddsDimContactMonthly]
		@c1 int = NULL,
		@c2 nvarchar(10) = NULL,
		@c3 nvarchar(50) = NULL,
		@c4 nvarchar(50) = NULL,
		@c5 nvarchar(80) = NULL,
		@c6 nvarchar(50) = NULL,
		@c7 nvarchar(50) = NULL,
		@c8 nvarchar(50) = NULL,
		@c9 nvarchar(50) = NULL,
		@c10 nvarchar(50) = NULL,
		@c11 nvarchar(50) = NULL,
		@c12 varchar(1) = NULL,
		@c13 varchar(1) = NULL,
		@c14 varchar(1) = NULL,
		@c15 varchar(1) = NULL,
		@c16 varchar(1) = NULL,
		@c17 nvarchar(50) = NULL,
		@c18 nvarchar(10) = NULL,
		@c19 int = NULL,
		@c20 nvarchar(25) = NULL,
		@c21 nvarchar(20) = NULL,
		@c22 nvarchar(20) = NULL,
		@c23 nvarchar(50) = NULL,
		@c24 nvarchar(50) = NULL,
		@c25 nvarchar(50) = NULL,
		@c26 nvarchar(50) = NULL,
		@c27 nvarchar(10) = NULL,
		@c28 nvarchar(50) = NULL,
		@c29 nvarchar(50) = NULL,
		@c30 nvarchar(50) = NULL,
		@c31 nvarchar(100) = NULL,
		@c32 nvarchar(100) = NULL,
		@c33 nvarchar(255) = NULL,
		@c34 datetime = NULL,
		@c35 nvarchar(150) = NULL,
		@c36 nvarchar(50) = NULL,
		@c37 nvarchar(50) = NULL,
		@c38 nvarchar(50) = NULL,
		@c39 tinyint = NULL,
		@c40 datetime = NULL,
		@c41 datetime = NULL,
		@c42 varchar(200) = NULL,
		@c43 tinyint = NULL,
		@c44 int = NULL,
		@c45 int = NULL,
		@c46 nchar(1) = NULL,
		@c47 nvarchar(10) = NULL,
		@c48 nvarchar(100) = NULL,
		@c49 nvarchar(100) = NULL,
		@c50 nvarchar(100) = NULL,
		@c51 nvarchar(50) = NULL,
		@c52 nvarchar(100) = NULL,
		@c53 datetime = NULL,
		@c54 datetime = NULL,
		@c55 nvarchar(100) = NULL,
		@c56 nvarchar(10) = NULL,
		@c57 nvarchar(18) = NULL,
		@c58 nvarchar(50) = NULL,
		@c59 nvarchar(18) = NULL,
		@c60 nvarchar(100) = NULL,
		@c61 nvarchar(100) = NULL,
		@c62 nvarchar(255) = NULL,
		@c63 nvarchar(60) = NULL,
		@c64 nvarchar(80) = NULL,
		@c65 nvarchar(50) = NULL,
		@c66 nvarchar(80) = NULL,
		@c67 nvarchar(50) = NULL,
		@c68 nvarchar(20) = NULL,
		@c69 nvarchar(100) = NULL,
		@c70 nvarchar(18) = NULL,
		@c71 bit = NULL,
		@c72 nvarchar(80) = NULL,
		@c73 nvarchar(80) = NULL,
		@c74 nvarchar(80) = NULL,
		@c75 nvarchar(80) = NULL,
		@c76 nvarchar(105) = NULL,
		@c77 nvarchar(50) = NULL,
		@c78 datetime = NULL,
		@pkc1 int = NULL,
		@bitmap binary(10)
as
begin
	declare @primarykey_text nvarchar(100) = ''
if (substring(@bitmap,1,1) & 1 = 1)
begin
update [bi_mktg_dds].[DimContactMonthly] set
		[ContactKey] = case substring(@bitmap,1,1) & 1 when 1 then @c1 else [ContactKey] end,
		[ContactSSID] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [ContactSSID] end,
		[ContactFirstName] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [ContactFirstName] end,
		[ContactMiddleName] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [ContactMiddleName] end,
		[ContactLastName] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [ContactLastName] end,
		[ContactSuffix] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [ContactSuffix] end,
		[Salutation] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [Salutation] end,
		[ContactStatusSSID] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [ContactStatusSSID] end,
		[ContactStatusDescription] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [ContactStatusDescription] end,
		[ContactMethodSSID] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [ContactMethodSSID] end,
		[ContactMethodDescription] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [ContactMethodDescription] end,
		[DoNotSolicitFlag] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [DoNotSolicitFlag] end,
		[DoNotCallFlag] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [DoNotCallFlag] end,
		[DoNotEmailFlag] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [DoNotEmailFlag] end,
		[DoNotMailFlag] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [DoNotMailFlag] end,
		[DoNotTextFlag] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [DoNotTextFlag] end,
		[ContactGender] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [ContactGender] end,
		[ContactCallTime] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [ContactCallTime] end,
		[CompleteSale] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [CompleteSale] end,
		[ContactResearch] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [ContactResearch] end,
		[ReferringStore] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [ReferringStore] end,
		[ReferringStylist] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [ReferringStylist] end,
		[ContactLanguageSSID] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [ContactLanguageSSID] end,
		[ContactLanguageDescription] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [ContactLanguageDescription] end,
		[ContactPromotonSSID] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [ContactPromotonSSID] end,
		[ContactPromotionDescription] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [ContactPromotionDescription] end,
		[ContactRequestSSID] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [ContactRequestSSID] end,
		[ContactRequestDescription] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [ContactRequestDescription] end,
		[ContactAgeRangeSSID] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [ContactAgeRangeSSID] end,
		[ContactAgeRangeDescription] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [ContactAgeRangeDescription] end,
		[ContactHairLossSSID] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [ContactHairLossSSID] end,
		[ContactHairLossDescription] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [ContactHairLossDescription] end,
		[DNCFlag] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [DNCFlag] end,
		[DNCDate] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [DNCDate] end,
		[ContactAffiliateID] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [ContactAffiliateID] end,
		[ContactCenterSSID] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [ContactCenterSSID] end,
		[ContactCenter] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [ContactCenter] end,
		[ContactAlternateCenter] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [ContactAlternateCenter] end,
		[RowIsCurrent] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [RowIsCurrent] end,
		[RowStartDate] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [RowStartDate] end,
		[RowEndDate] = case substring(@bitmap,6,1) & 1 when 1 then @c41 else [RowEndDate] end,
		[RowChangeReason] = case substring(@bitmap,6,1) & 2 when 2 then @c42 else [RowChangeReason] end,
		[RowIsInferred] = case substring(@bitmap,6,1) & 4 when 4 then @c43 else [RowIsInferred] end,
		[InsertAuditKey] = case substring(@bitmap,6,1) & 8 when 8 then @c44 else [InsertAuditKey] end,
		[UpdateAuditKey] = case substring(@bitmap,6,1) & 16 when 16 then @c45 else [UpdateAuditKey] end,
		[AdiFlag] = case substring(@bitmap,6,1) & 32 when 32 then @c46 else [AdiFlag] end,
		[DiscStyleSSID] = case substring(@bitmap,6,1) & 64 when 64 then @c47 else [DiscStyleSSID] end,
		[HairLossTreatment] = case substring(@bitmap,6,1) & 128 when 128 then @c48 else [HairLossTreatment] end,
		[HairLossSpot] = case substring(@bitmap,7,1) & 1 when 1 then @c49 else [HairLossSpot] end,
		[HairLossExperience] = case substring(@bitmap,7,1) & 2 when 2 then @c50 else [HairLossExperience] end,
		[HairLossinFamily] = case substring(@bitmap,7,1) & 4 when 4 then @c51 else [HairLossinFamily] end,
		[HairLossFamily] = case substring(@bitmap,7,1) & 8 when 8 then @c52 else [HairLossFamily] end,
		[CreationDate] = case substring(@bitmap,7,1) & 16 when 16 then @c53 else [CreationDate] end,
		[UpdateDate] = case substring(@bitmap,7,1) & 32 when 32 then @c54 else [UpdateDate] end,
		[ContactSessionid] = case substring(@bitmap,7,1) & 64 when 64 then @c55 else [ContactSessionid] end,
		[ContactOriginalCenter] = case substring(@bitmap,7,1) & 128 when 128 then @c56 else [ContactOriginalCenter] end,
		[SFDC_LeadID] = case substring(@bitmap,8,1) & 1 when 1 then @c57 else [SFDC_LeadID] end,
		[BosleySiebelID] = case substring(@bitmap,8,1) & 2 when 2 then @c58 else [BosleySiebelID] end,
		[BosleySFDC_LeadID] = case substring(@bitmap,8,1) & 4 when 4 then @c59 else [BosleySFDC_LeadID] end,
		[DMARegion] = case substring(@bitmap,8,1) & 8 when 8 then @c60 else [DMARegion] end,
		[DMADescription] = case substring(@bitmap,8,1) & 16 when 16 then @c61 else [DMADescription] end,
		[Street] = case substring(@bitmap,8,1) & 32 when 32 then @c62 else [Street] end,
		[City] = case substring(@bitmap,8,1) & 64 when 64 then @c63 else [City] end,
		[State] = case substring(@bitmap,8,1) & 128 when 128 then @c64 else [State] end,
		[StateCode] = case substring(@bitmap,9,1) & 1 when 1 then @c65 else [StateCode] end,
		[Country] = case substring(@bitmap,9,1) & 2 when 2 then @c66 else [Country] end,
		[CountryCode] = case substring(@bitmap,9,1) & 4 when 4 then @c67 else [CountryCode] end,
		[PostalCode] = case substring(@bitmap,9,1) & 8 when 8 then @c68 else [PostalCode] end,
		[GCLID] = case substring(@bitmap,9,1) & 16 when 16 then @c69 else [GCLID] end,
		[SFDC_PersonAccountID] = case substring(@bitmap,9,1) & 32 when 32 then @c70 else [SFDC_PersonAccountID] end,
		[SFDC_IsDeleted] = case substring(@bitmap,9,1) & 64 when 64 then @c71 else [SFDC_IsDeleted] end,
		[LeadSource] = case substring(@bitmap,9,1) & 128 when 128 then @c72 else [LeadSource] end,
		[Accomodation] = case substring(@bitmap,10,1) & 1 when 1 then @c73 else [Accomodation] end,
		[Phone] = case substring(@bitmap,10,1) & 2 when 2 then @c74 else [Phone] end,
		[MobilePhone] = case substring(@bitmap,10,1) & 4 when 4 then @c75 else [MobilePhone] end,
		[Email] = case substring(@bitmap,10,1) & 8 when 8 then @c76 else [Email] end,
		[Lead_Activity_status__c] = case substring(@bitmap,10,1) & 16 when 16 then @c77 else [Lead_Activity_status__c] end,
		[MonthlyInsertDate] = case substring(@bitmap,10,1) & 32 when 32 then @c78 else [MonthlyInsertDate] end
	where [ContactKey] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
		Begin
			if exists (Select * from sys.all_parameters where object_id = OBJECT_ID('sp_MSreplraiserror') and [name] = '@param3')
			Begin

				set @primarykey_text = @primarykey_text + '[ContactKey] = ' + convert(nvarchar(100),@pkc1,1)
				exec sp_MSreplraiserror @errorid=20598, @param1=N'[bi_mktg_dds].[DimContactMonthly]', @param2=@primarykey_text, @param3=13233
			End
			Else
				exec sp_MSreplraiserror @errorid=20598
		End
end
else
begin
update [bi_mktg_dds].[DimContactMonthly] set
		[ContactSSID] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [ContactSSID] end,
		[ContactFirstName] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [ContactFirstName] end,
		[ContactMiddleName] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [ContactMiddleName] end,
		[ContactLastName] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [ContactLastName] end,
		[ContactSuffix] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [ContactSuffix] end,
		[Salutation] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [Salutation] end,
		[ContactStatusSSID] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [ContactStatusSSID] end,
		[ContactStatusDescription] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [ContactStatusDescription] end,
		[ContactMethodSSID] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [ContactMethodSSID] end,
		[ContactMethodDescription] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [ContactMethodDescription] end,
		[DoNotSolicitFlag] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [DoNotSolicitFlag] end,
		[DoNotCallFlag] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [DoNotCallFlag] end,
		[DoNotEmailFlag] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [DoNotEmailFlag] end,
		[DoNotMailFlag] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [DoNotMailFlag] end,
		[DoNotTextFlag] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [DoNotTextFlag] end,
		[ContactGender] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [ContactGender] end,
		[ContactCallTime] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [ContactCallTime] end,
		[CompleteSale] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [CompleteSale] end,
		[ContactResearch] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [ContactResearch] end,
		[ReferringStore] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [ReferringStore] end,
		[ReferringStylist] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [ReferringStylist] end,
		[ContactLanguageSSID] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [ContactLanguageSSID] end,
		[ContactLanguageDescription] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [ContactLanguageDescription] end,
		[ContactPromotonSSID] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [ContactPromotonSSID] end,
		[ContactPromotionDescription] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [ContactPromotionDescription] end,
		[ContactRequestSSID] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [ContactRequestSSID] end,
		[ContactRequestDescription] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [ContactRequestDescription] end,
		[ContactAgeRangeSSID] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [ContactAgeRangeSSID] end,
		[ContactAgeRangeDescription] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [ContactAgeRangeDescription] end,
		[ContactHairLossSSID] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [ContactHairLossSSID] end,
		[ContactHairLossDescription] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [ContactHairLossDescription] end,
		[DNCFlag] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [DNCFlag] end,
		[DNCDate] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [DNCDate] end,
		[ContactAffiliateID] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [ContactAffiliateID] end,
		[ContactCenterSSID] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [ContactCenterSSID] end,
		[ContactCenter] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [ContactCenter] end,
		[ContactAlternateCenter] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [ContactAlternateCenter] end,
		[RowIsCurrent] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [RowIsCurrent] end,
		[RowStartDate] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [RowStartDate] end,
		[RowEndDate] = case substring(@bitmap,6,1) & 1 when 1 then @c41 else [RowEndDate] end,
		[RowChangeReason] = case substring(@bitmap,6,1) & 2 when 2 then @c42 else [RowChangeReason] end,
		[RowIsInferred] = case substring(@bitmap,6,1) & 4 when 4 then @c43 else [RowIsInferred] end,
		[InsertAuditKey] = case substring(@bitmap,6,1) & 8 when 8 then @c44 else [InsertAuditKey] end,
		[UpdateAuditKey] = case substring(@bitmap,6,1) & 16 when 16 then @c45 else [UpdateAuditKey] end,
		[AdiFlag] = case substring(@bitmap,6,1) & 32 when 32 then @c46 else [AdiFlag] end,
		[DiscStyleSSID] = case substring(@bitmap,6,1) & 64 when 64 then @c47 else [DiscStyleSSID] end,
		[HairLossTreatment] = case substring(@bitmap,6,1) & 128 when 128 then @c48 else [HairLossTreatment] end,
		[HairLossSpot] = case substring(@bitmap,7,1) & 1 when 1 then @c49 else [HairLossSpot] end,
		[HairLossExperience] = case substring(@bitmap,7,1) & 2 when 2 then @c50 else [HairLossExperience] end,
		[HairLossinFamily] = case substring(@bitmap,7,1) & 4 when 4 then @c51 else [HairLossinFamily] end,
		[HairLossFamily] = case substring(@bitmap,7,1) & 8 when 8 then @c52 else [HairLossFamily] end,
		[CreationDate] = case substring(@bitmap,7,1) & 16 when 16 then @c53 else [CreationDate] end,
		[UpdateDate] = case substring(@bitmap,7,1) & 32 when 32 then @c54 else [UpdateDate] end,
		[ContactSessionid] = case substring(@bitmap,7,1) & 64 when 64 then @c55 else [ContactSessionid] end,
		[ContactOriginalCenter] = case substring(@bitmap,7,1) & 128 when 128 then @c56 else [ContactOriginalCenter] end,
		[SFDC_LeadID] = case substring(@bitmap,8,1) & 1 when 1 then @c57 else [SFDC_LeadID] end,
		[BosleySiebelID] = case substring(@bitmap,8,1) & 2 when 2 then @c58 else [BosleySiebelID] end,
		[BosleySFDC_LeadID] = case substring(@bitmap,8,1) & 4 when 4 then @c59 else [BosleySFDC_LeadID] end,
		[DMARegion] = case substring(@bitmap,8,1) & 8 when 8 then @c60 else [DMARegion] end,
		[DMADescription] = case substring(@bitmap,8,1) & 16 when 16 then @c61 else [DMADescription] end,
		[Street] = case substring(@bitmap,8,1) & 32 when 32 then @c62 else [Street] end,
		[City] = case substring(@bitmap,8,1) & 64 when 64 then @c63 else [City] end,
		[State] = case substring(@bitmap,8,1) & 128 when 128 then @c64 else [State] end,
		[StateCode] = case substring(@bitmap,9,1) & 1 when 1 then @c65 else [StateCode] end,
		[Country] = case substring(@bitmap,9,1) & 2 when 2 then @c66 else [Country] end,
		[CountryCode] = case substring(@bitmap,9,1) & 4 when 4 then @c67 else [CountryCode] end,
		[PostalCode] = case substring(@bitmap,9,1) & 8 when 8 then @c68 else [PostalCode] end,
		[GCLID] = case substring(@bitmap,9,1) & 16 when 16 then @c69 else [GCLID] end,
		[SFDC_PersonAccountID] = case substring(@bitmap,9,1) & 32 when 32 then @c70 else [SFDC_PersonAccountID] end,
		[SFDC_IsDeleted] = case substring(@bitmap,9,1) & 64 when 64 then @c71 else [SFDC_IsDeleted] end,
		[LeadSource] = case substring(@bitmap,9,1) & 128 when 128 then @c72 else [LeadSource] end,
		[Accomodation] = case substring(@bitmap,10,1) & 1 when 1 then @c73 else [Accomodation] end,
		[Phone] = case substring(@bitmap,10,1) & 2 when 2 then @c74 else [Phone] end,
		[MobilePhone] = case substring(@bitmap,10,1) & 4 when 4 then @c75 else [MobilePhone] end,
		[Email] = case substring(@bitmap,10,1) & 8 when 8 then @c76 else [Email] end,
		[Lead_Activity_status__c] = case substring(@bitmap,10,1) & 16 when 16 then @c77 else [Lead_Activity_status__c] end,
		[MonthlyInsertDate] = case substring(@bitmap,10,1) & 32 when 32 then @c78 else [MonthlyInsertDate] end
	where [ContactKey] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
		Begin
			if exists (Select * from sys.all_parameters where object_id = OBJECT_ID('sp_MSreplraiserror') and [name] = '@param3')
			Begin

				set @primarykey_text = @primarykey_text + '[ContactKey] = ' + convert(nvarchar(100),@pkc1,1)
				exec sp_MSreplraiserror @errorid=20598, @param1=N'[bi_mktg_dds].[DimContactMonthly]', @param2=@primarykey_text, @param3=13233
			End
			Else
				exec sp_MSreplraiserror @errorid=20598
		End
end
end
GO
