/* CreateDate: 09/03/2021 09:37:06.650 , ModifyDate: 09/03/2021 09:37:06.650 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [sp_MSins_bi_mktg_ddsFactActivity]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 int,
    @c13 int,
    @c14 int,
    @c15 int,
    @c16 int,
    @c17 int,
    @c18 int,
    @c19 int,
    @c20 int,
    @c21 int,
    @c22 int,
    @c23 int,
    @c24 int
as
begin
	insert into [bi_mktg_dds].[FactActivity] (
		[ActivityDateKey],
		[ActivityKey],
		[ActivityTimeKey],
		[ActivityCompletedDateKey],
		[ActivityCompletedTimeKey],
		[ActivityDueDateKey],
		[ActivityStartTimeKey],
		[GenderKey],
		[EthnicityKey],
		[OccupationKey],
		[MaritalStatusKey],
		[AgeRangeKey],
		[HairLossTypeKey],
		[CenterKey],
		[ContactKey],
		[ActionCodeKey],
		[ResultCodeKey],
		[SourceKey],
		[ActivityTypeKey],
		[CompletedByEmployeeKey],
		[StartedByEmployeeKey],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[ActivityEmployeeKey]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		default,
		@c24	)
end
GO
