create procedure [dbo].[sp_MSins_bi_mktg_ddsDimContactAppend]
    @c1 int,
    @c2 int,
    @c3 nvarchar(10),
    @c4 int,
    @c5 int,
    @c6 nvarchar(10),
    @c7 nvarchar(50),
    @c8 nvarchar(10),
    @c9 nvarchar(50),
    @c10 nvarchar(10),
    @c11 nvarchar(50),
    @c12 nvarchar(10),
    @c13 nvarchar(50),
    @c14 nvarchar(10),
    @c15 nvarchar(10),
    @c16 nvarchar(10),
    @c17 nvarchar(10),
    @c18 nvarchar(50),
    @c19 nvarchar(10),
    @c20 nvarchar(10),
    @c21 nvarchar(10),
    @c22 nvarchar(10),
    @c23 nvarchar(10),
    @c24 nvarchar(10),
    @c25 nvarchar(10),
    @c26 nvarchar(10),
    @c27 nvarchar(10),
    @c28 nvarchar(10),
    @c29 nvarchar(10),
    @c30 nvarchar(10),
    @c31 nvarchar(10),
    @c32 nvarchar(10),
    @c33 varchar(50),
    @c34 varchar(50),
    @c35 varchar(50),
    @c36 int
as
begin
	insert into [bi_mktg_dds].[DimContactAppend] (
		[ContactAppendKey],
		[ContactKey],
		[ContactSSID],
		[CenterKey],
		[CenterSSID],
		[HouseholdMosaicGroupID],
		[HouseholdMosaicGroup],
		[HouseholdMosaicTypeID],
		[HouseholdMosaicType],
		[ZipCodeMosaicGroupID],
		[ZipCodeMosaicGroup],
		[ZipCodeMosaicTypeID],
		[ZipCodeMosaicType],
		[Combined_Age],
		[Education_Model],
		[Occupation_Group],
		[Match_Level_for_GEOData],
		[Est_HouseHold_Income],
		[NCOA_Move_Update_Code],
		[Mail_Responder],
		[MOR_Bank_Upscale_Merchandise_Buyer],
		[MOR_Bank_HealthandFitness_Magazine],
		[CAPE_Ethnic_Pop_White_Only],
		[CAPE_Ethnic_Pop_Black_Only],
		[CAPE_Ethnic_Pop_Asian_Only],
		[CAPE_Ethnic_Pop_Hispanic],
		[CAPE_Lang_HH_Spanish_Speaking],
		[CAPE_Income_HH_Median_Family],
		[MatchStatus],
		[CE_Selected_Individual_Vendor_Ethnicity_Code],
		[CE_Selected_Individual_Vendor_Ethnic_Group_Code],
		[CE_Selected_Individual_Vendor_Spoken_Language_Code],
		[Latitude],
		[Longitude],
		[LeadMatchStatus],
		[LeadScore]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36	)
end
