/* CreateDate: 10/03/2019 22:32:12.023 , ModifyDate: 10/03/2019 22:32:12.023 */
GO
create procedure [sp_MSins_dbodbaMargin]
    @c1 int,
    @c2 uniqueidentifier,
    @c3 nvarchar(100),
    @c4 int,
    @c5 int,
    @c6 uniqueidentifier,
    @c7 int,
    @c8 nvarchar(100),
    @c9 nvarchar(100),
    @c10 nvarchar(100),
    @c11 nvarchar(50),
    @c12 bit,
    @c13 datetime,
    @c14 datetime,
    @c15 int,
    @c16 money,
    @c17 money,
    @c18 money,
    @c19 money,
    @c20 int,
    @c21 money,
    @c22 int,
    @c23 int,
    @c24 int,
    @c25 int,
    @c26 money,
    @c27 datetime,
    @c28 nvarchar(25),
    @c29 datetime,
    @c30 nvarchar(25)
as
begin
	insert into [dbo].[dbaMargin] (
		[ClientProfitabilityID],
		[ClientGUID],
		[ClientName],
		[ClientIdentifier],
		[ClientCenterId],
		[ClientMembershipGUID],
		[MembershipID],
		[BusinessSegment],
		[MembershipDescription],
		[Status],
		[MembershipIdentifier],
		[IsMembershipActive],
		[MembershipStartDate],
		[MembershipEndDate],
		[MembershipDuration],
		[PaymentsTotal],
		[RefundsTotal],
		[ServiceRevenue],
		[ProductRevenue],
		[HairOrderCount],
		[HairOrderTotalCost],
		[FullService],
		[Applications],
		[Services],
		[ServiceDuration],
		[ServiceCost],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30	)
end
GO
