create procedure [sp_MSins_dboEmployeeHoursCertipay]
    @c1 varchar(64),
    @c2 varchar(64),
    @c3 int,
    @c4 varchar(50),
    @c5 varchar(50),
    @c6 datetime,
    @c7 datetime,
    @c8 datetime,
    @c9 real,
    @c10 real,
    @c11 real,
    @c12 real,
    @c13 int,
    @c14 datetime,
    @c15 int,
    @c16 real,
    @c17 real,
    @c18 real,
    @c19 bigint,
    @c20 bigint,
    @c21 bigint,
    @c22 bigint,
    @c23 bigint,
    @c24 bigint,
    @c25 bigint,
    @c26 real,
    @c27 bigint,
    @c28 int
as
begin
	insert into [dbo].[EmployeeHoursCertipay] (
		[LastName],
		[FirstName],
		[HomeDepartment],
		[EmployeeNumber],
		[EmployeeID],
		[PeriodBegin],
		[PeriodEnd],
		[CheckDate],
		[SalaryHours],
		[RegularHours],
		[OverTimeHours],
		[PTO_Hours],
		[PerformerHomeCenter],
		[ImportDate],
		[GeneralLedger],
		[PTHours],
		[FuneralHours],
		[JuryHours],
		[SalaryEarnings],
		[RegularEarnings],
		[OTEarnings],
		[PTEarnings],
		[PTOEarnings],
		[FuneralEarnings],
		[JuryEarnings],
		[TravelHours],
		[TravelEarnings],
		[ID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28	)
end
