create procedure [sp_MSins_bief_ddsDimDate_TEMP]
    @c1 int,
    @c2 datetime,
    @c3 char(12),
    @c4 smallint,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 char(12),
    @c10 char(7),
    @c11 char(13),
    @c12 char(4),
    @c13 char(9),
    @c14 smallint,
    @c15 datetime,
    @c16 datetime,
    @c17 smallint,
    @c18 char(10),
    @c19 bit,
    @c20 bit,
    @c21 char(10),
    @c22 char(15),
    @c23 char(3),
    @c24 char(8),
    @c25 smallint,
    @c26 datetime,
    @c27 datetime,
    @c28 smallint,
    @c29 char(16),
    @c30 bit,
    @c31 char(9),
    @c32 char(15),
    @c33 char(2),
    @c34 char(7),
    @c35 smallint,
    @c36 datetime,
    @c37 datetime,
    @c38 smallint,
    @c39 char(16),
    @c40 char(9),
    @c41 char(15),
    @c42 char(2),
    @c43 char(7),
    @c44 smallint,
    @c45 int,
    @c46 datetime,
    @c47 datetime,
    @c48 smallint,
    @c49 char(16),
    @c50 char(4),
    @c51 char(2),
    @c52 datetime,
    @c53 datetime,
    @c54 smallint,
    @c55 char(20),
    @c56 smallint,
    @c57 smallint,
    @c58 char(7),
    @c59 char(7),
    @c60 smallint,
    @c61 smallint,
    @c62 smallint,
    @c63 smallint,
    @c64 smallint,
    @c65 int,
    @c66 int,
    @c67 int,
    @c68 int,
    @c69 int,
    @c70 char(4),
    @c71 char(16),
    @c72 char(6),
    @c73 char(1),
    @c74 char(16),
    @c75 char(7),
    @c76 char(34),
    @c77 char(3),
    @c78 char(21),
    @c79 char(2),
    @c80 char(8),
    @c81 char(4),
    @c82 char(14),
    @c83 char(16),
    @c84 char(22),
    @c85 char(2),
    @c86 char(14),
    @c87 char(8),
    @c88 char(20),
    @c89 char(4),
    @c90 char(10),
    @c91 char(2),
    @c92 char(16),
    @c93 char(8),
    @c94 char(22),
    @c95 char(4),
    @c96 char(10),
    @c97 uniqueidentifier,
    @c98 int,
    @c99 int,
    @c100 int
as
begin
	insert into [bief_dds].[DimDate_TEMP] (
		[DateKey],
		[FullDate],
		[ISODate],
		[YearNumber],
		[YearQuarterNumber],
		[YearMonthNumber],
		[YearQuarterMonthNumber],
		[YearWeekNumber],
		[DateName],
		[WeekName],
		[WeekNameWithYear],
		[WeekShortName],
		[WeekShortNameWithYear],
		[WeekNumber],
		[FirstDateOfWeek],
		[LastDateOfWeek],
		[DayOfWeek],
		[DayOfWeekName],
		[IsWeekday],
		[IsWeekend],
		[MonthName],
		[MonthNameWithYear],
		[MonthShortName],
		[MonthShortNameWithYear],
		[MonthNumber],
		[FirstDateOfMonth],
		[LastDateOfMonth],
		[DayOfMonth],
		[DayOfMonthName],
		[IsLastDayOfMonth],
		[QuarterName],
		[QuarterNameWithYear],
		[QuarterShortName],
		[QuarterShortNameWithYear],
		[QuarterNumber],
		[FirstDateOfQuarter],
		[LastDateOfQuarter],
		[DayOfQuarter],
		[DayOfQuarterName],
		[HalfName],
		[HalfNameWithYear],
		[HalfShortName],
		[HalfShortNameWithYear],
		[HalfNumber],
		[YearHalfNumber],
		[FirstDateOfHalf],
		[LastDateOfHalf],
		[DayOfHalf],
		[DayOfHalfName],
		[YearName],
		[YearShortName],
		[FirstDateOfYear],
		[LastDateOfYear],
		[DayOfYear],
		[DayOfYearName],
		[CalendarQuarter],
		[CalendarYear],
		[CalendarYearMonth],
		[CalendarYearQtr],
		[FiscalYear],
		[FiscalWeek],
		[FiscalPeriod],
		[FiscalMonth],
		[FiscalQuarter],
		[FiscalYearFiscalWeek],
		[FiscalYearFiscalPeriod],
		[FiscalYearFiscalMonth],
		[FiscalYearFiscalQuarter],
		[FiscalYearFiscalQuarterFiscalMonth],
		[FiscalYearName],
		[FiscalYearLongName],
		[FiscalYearShortName],
		[FiscalQuarterName],
		[FiscalQuarterLongName],
		[FiscalQuarterNameWithYear],
		[FiscalQuarterLongNameWithYear],
		[FiscalQuarterShortName],
		[FiscalQuarterShortNameWithYear],
		[FiscalMonthName],
		[FiscalMonthNameWithYear],
		[FiscalMonthShortName],
		[FiscalMonthShortNameWithYear],
		[FiscalMonthCalendarShortName],
		[FiscalMonthCalendarShortNameWithYear],
		[FiscalWeekName],
		[FiscalWeekLongName],
		[FiscalWeekNameWithYear],
		[FiscalWeekLongNameWithYear],
		[FiscalWeekShortName],
		[FiscalWeekShortNameWithYear],
		[FiscalPeriodName],
		[FiscalPeriodLongName],
		[FiscalPeriodNameWithYear],
		[FiscalPeriodLongNameWithYear],
		[FiscalPeriodShortName],
		[FiscalPeriodShortNameWithYear],
		[msrepl_tran_version],
		[CummWorkdays],
		[MonthWorkdays],
		[MonthWorkdaysTotal]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40,
		@c41,
		@c42,
		@c43,
		@c44,
		@c45,
		@c46,
		@c47,
		@c48,
		@c49,
		@c50,
		@c51,
		@c52,
		@c53,
		@c54,
		@c55,
		@c56,
		@c57,
		@c58,
		@c59,
		@c60,
		@c61,
		@c62,
		@c63,
		@c64,
		@c65,
		@c66,
		@c67,
		@c68,
		@c69,
		@c70,
		@c71,
		@c72,
		@c73,
		@c74,
		@c75,
		@c76,
		@c77,
		@c78,
		@c79,
		@c80,
		@c81,
		@c82,
		@c83,
		@c84,
		@c85,
		@c86,
		@c87,
		@c88,
		@c89,
		@c90,
		@c91,
		@c92,
		@c93,
		@c94,
		@c95,
		@c96,
		@c97,
		@c98,
		@c99,
		@c100	)
end
