create procedure [sp_MSins_bi_ent_ddsDimCenter]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 int,
    @c13 nvarchar(50),
    @c14 nvarchar(50),
    @c15 nvarchar(50),
    @c16 nvarchar(50),
    @c17 nvarchar(50),
    @c18 nvarchar(10),
    @c19 nvarchar(50),
    @c20 nvarchar(10),
    @c21 nvarchar(50),
    @c22 nvarchar(15),
    @c23 nvarchar(15),
    @c24 int,
    @c25 nvarchar(50),
    @c26 nvarchar(10),
    @c27 nvarchar(15),
    @c28 int,
    @c29 nvarchar(50),
    @c30 nvarchar(10),
    @c31 nvarchar(15),
    @c32 int,
    @c33 nvarchar(50),
    @c34 nvarchar(10),
    @c35 nchar(1),
    @c36 tinyint,
    @c37 datetime,
    @c38 datetime,
    @c39 varchar(200),
    @c40 tinyint,
    @c41 int,
    @c42 int,
    @c43 uniqueidentifier,
    @c44 int,
    @c45 int,
    @c46 bit,
    @c47 int,
    @c48 uniqueidentifier,
    @c49 uniqueidentifier,
    @c50 uniqueidentifier,
    @c51 uniqueidentifier,
    @c52 int,
    @c53 nvarchar(10),
    @c54 nvarchar(10),
    @c55 int,
    @c56 int,
    @c57 nvarchar(100),
    @c58 nvarchar(100)
as
begin
	insert into [bi_ent_dds].[DimCenter] (
		[CenterKey],
		[CenterSSID],
		[RegionKey],
		[RegionSSID],
		[TimeZoneKey],
		[TimeZoneSSID],
		[CenterTypeKey],
		[CenterTypeSSID],
		[DoctorRegionKey],
		[DoctorRegionSSID],
		[CenterOwnershipKey],
		[CenterOwnershipSSID],
		[CenterDescription],
		[CenterAddress1],
		[CenterAddress2],
		[CenterAddress3],
		[CountryRegionDescription],
		[CountryRegionDescriptionShort],
		[StateProvinceDescription],
		[StateProvinceDescriptionShort],
		[City],
		[PostalCode],
		[CenterPhone1],
		[Phone1TypeSSID],
		[CenterPhone1TypeDescription],
		[CenterPhone1TypeDescriptionShort],
		[CenterPhone2],
		[Phone2TypeSSID],
		[CenterPhone2TypeDescription],
		[CenterPhone2TypeDescriptionShort],
		[CenterPhone3],
		[Phone3TypeSSID],
		[CenterPhone3TypeDescription],
		[CenterPhone3TypeDescriptionShort],
		[Active],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[ReportingCenterSSID],
		[ReportingCenterKey],
		[HasFullAccessFlag],
		[CenterBusinessTypeID],
		[RegionRSMNBConsultantSSID],
		[RegionRSMMembershipAdvisorSSID],
		[RegionRTMTechnicalManagerSSID],
		[RegionROMOperationsManagerSSID],
		[CenterManagementAreaSSID],
		[NewBusinessSize],
		[RecurringBusinessSize],
		[CenterNumber],
		[DMACode],
		[DMADescription],
		[DMARegion]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40,
		@c41,
		@c42,
		default,
		@c43,
		@c44,
		@c45,
		@c46,
		@c47,
		@c48,
		@c49,
		@c50,
		@c51,
		@c52,
		@c53,
		@c54,
		@c55,
		@c56,
		@c57,
		@c58	)
end
