/* CreateDate: 01/18/2005 09:34:07.717 , ModifyDate: 06/21/2012 10:00:52.153 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[onca_nickname](
	[nickname] [nchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[actual_name] [nchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [pk_onca_nickname] PRIMARY KEY CLUSTERED
(
	[nickname] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
