/* CreateDate: 01/18/2005 09:34:14.170 , ModifyDate: 06/18/2013 09:24:50.827 */
GO
CREATE TABLE [dbo].[onct_entity](
	[entity_id] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[description] [nchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[table_name] [nchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[internal_name] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[window_id] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[table_alias] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [pk_onct_entity] PRIMARY KEY CLUSTERED
(
	[entity_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [onct_entity_i2] ON [dbo].[onct_entity]
(
	[table_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [onct_entity_i3] ON [dbo].[onct_entity]
(
	[internal_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [onct_entity_i4] ON [dbo].[onct_entity]
(
	[window_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[onct_entity]  WITH CHECK ADD  CONSTRAINT [table_entity_294] FOREIGN KEY([table_name])
REFERENCES [dbo].[onct_table] ([table_name])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[onct_entity] CHECK CONSTRAINT [table_entity_294]
GO
