/* CreateDate: 06/20/2012 11:37:02.683 , ModifyDate: 08/11/2014 01:01:00.147 */
GO
CREATE TABLE [dbo].[cstd_email_dh_flat](
	[contact_alt_center] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[contact_contact_method_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_contact_status_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_creation_date] [datetime] NULL,
	[contact_affiliateid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_age] [int] NULL,
	[contact_age_range_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_call_time] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_complete_sale] [int] NULL,
	[contact_dnc_date] [datetime] NULL,
	[contact_dnc_flag] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_do_not_call] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_do_not_email] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_do_not_mail] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_do_not_text] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_gender_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_hair_loss_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_hair_loss_experience_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_hair_loss_family_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_hair_loss_in_family_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_hair_loss_product] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_hair_loss_spot_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_language_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_loginid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_promotion_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_referring_store] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_referring_stylist] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_request_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_research] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_sessionid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_do_not_solicit] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_duplicate_check] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_external_id] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_first_name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_first_name_search] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_first_name_soundex] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_greeting] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_last_name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_last_name_search] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_last_name_soundex] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_middle_name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_salutation_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_status_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_status_updated_date] [datetime] NULL,
	[contact_suffix] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_surgery_consultation_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_updated_date] [datetime] NULL,
	[contact_phone_active] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_area_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_contact_phone_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_country_code_prefix] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_creation_date] [datetime] NULL,
	[contact_phone_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_extension] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_phone_number] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_phone_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_sort_order] [int] NULL,
	[contact_phone_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_phone_updated_date] [datetime] NULL,
	[contact_address_address_line_1] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_address_line_1_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_address_line_2] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_address_line_2_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_address_line_3] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_address_line_4] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_address_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_city] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_city_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_company_address_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_contact_address_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_country_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_county_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_creation_date] [datetime] NULL,
	[contact_address_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_sort_order] [int] NULL,
	[contact_address_state_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_time_zone_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_address_updated_date] [datetime] NULL,
	[contact_address_zip_code] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_age_range_active] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_age_range_age_range_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_age_range_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_age_range_maximum_age] [int] NULL,
	[contact_age_range_minimum_age] [int] NULL,
	[contact_email_active] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_contact_email_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_creation_date] [datetime] NULL,
	[contact_email_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_email] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_email_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_sort_order] [int] NULL,
	[contact_email_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_email_updated_date] [datetime] NULL,
	[contact_company_company_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_company_role_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_contact_company_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_creation_date] [datetime] NULL,
	[contact_company_preferred_center_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_department_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_internal_title_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_reports_to_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_sort_order] [int] NULL,
	[contact_company_title] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_company_updated_date] [datetime] NULL,
	[company_annual_sales] [int] NULL,
	[company_company_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_name_1] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_name_1_search] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_name_1_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_name_2] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_name_2_search] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_name_2_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_status_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_contact_method_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_creation_date] [datetime] NULL,
	[company_center_manager_name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_center_number] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_company_map_link] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_director_name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_dma] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_do_not_solicit] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_duplicate_check] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_external_id] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_number_of_employees] [int] NULL,
	[company_parent_company_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_profile_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_status_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_status_updated_date] [datetime] NULL,
	[company_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_updated_date] [datetime] NULL,
	[company_address_address_line_1] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_address_line_1_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_address_line_2] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_address_line_2_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_address_line_3] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_address_line_4] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_address_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_city] [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_city_soundex] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_company_address_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_company_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_country_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_county_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_creation_date] [datetime] NULL,
	[company_address_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_sort_order] [int] NULL,
	[company_address_state_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_time_zone_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[company_address_updated_date] [datetime] NULL,
	[company_address_zip_code] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_action_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_batch_address_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_batch_result_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_batch_status_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_campaign_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_completed_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_completion_date] [datetime] NULL,
	[appointment_activity_completion_time] [datetime] NULL,
	[appointment_activity_confirmed_time] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_confirmed_time_from] [datetime] NULL,
	[appointment_activity_confirmed_time_to] [datetime] NULL,
	[appointment_activity_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_creation_date] [datetime] NULL,
	[appointment_activity_activity_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_followup_date] [datetime] NULL,
	[appointment_activity_followup_time] [datetime] NULL,
	[appointment_activity_lock_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_lock_date] [datetime] NULL,
	[appointment_activity_no_followup_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_override_time_zone] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_promotion_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_time_zone_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_utc_start_date] [datetime] NULL,
	[appointment_activity_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_document_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_due_date] [datetime] NULL,
	[appointment_activity_duration] [int] NULL,
	[appointment_activity_incident_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_milestone_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_notify_when_completed] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_opportunity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_priority] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_project_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_project_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_recur_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_result_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_source_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_start_time] [datetime] NULL,
	[appointment_activity_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_updated_date] [datetime] NULL,
	[brochure_activity_action_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_batch_address_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_batch_result_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_batch_status_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_campaign_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_completed_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_completion_date] [datetime] NULL,
	[brochure_activity_completion_time] [datetime] NULL,
	[brochure_activity_confirmed_time] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_confirmed_time_from] [datetime] NULL,
	[brochure_activity_confirmed_time_to] [datetime] NULL,
	[brochure_activity_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_creation_date] [datetime] NULL,
	[brochure_activity_activity_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_followup_date] [datetime] NULL,
	[brochure_activity_followup_time] [datetime] NULL,
	[brochure_activity_lock_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_lock_date] [datetime] NULL,
	[brochure_activity_no_followup_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_override_time_zone] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_promotion_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_time_zone_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_utc_start_date] [datetime] NULL,
	[brochure_activity_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_document_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_due_date] [datetime] NULL,
	[brochure_activity_duration] [int] NULL,
	[brochure_activity_incident_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_milestone_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_notify_when_completed] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_opportunity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_priority] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_project_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_project_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_recur_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_result_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_source_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_start_time] [datetime] NULL,
	[brochure_activity_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_updated_date] [datetime] NULL,
	[activity_demographic_activity_demographic_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_age] [int] NULL,
	[activity_demographic_birthday] [datetime] NULL,
	[activity_demographic_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_creation_date] [datetime] NULL,
	[activity_demographic_disc_style] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_ethnicity_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_gender] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_ludwig] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_maritalstatus_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_no_sale_reason] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_norwood] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_occupation_code] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_performer] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_price_quoted] [money] NULL,
	[activity_demographic_solution_offered] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[activity_demographic_updated_date] [datetime] NULL,
	[contact_source_assignment_date] [datetime] NULL,
	[contact_source_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_contact_source_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_creation_date] [datetime] NULL,
	[contact_source_dnis_number] [int] NULL,
	[contact_source_sub_source_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_media_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_sort_order] [int] NULL,
	[contact_source_source_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_source_updated_date] [datetime] NULL,
	[appointment_activity_user_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_user_activity_user_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_user_assignment_date] [datetime] NULL,
	[appointment_activity_user_attendance] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_user_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_user_creation_date] [datetime] NULL,
	[appointment_activity_user_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_user_sort_order] [int] NULL,
	[appointment_activity_user_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[appointment_activity_user_updated_date] [datetime] NULL,
	[appointment_activity_user_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_activity_user_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_assignment_date] [datetime] NULL,
	[brochure_activity_user_attendance] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_creation_date] [datetime] NULL,
	[brochure_activity_user_primary_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_sort_order] [int] NULL,
	[brochure_activity_user_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[brochure_activity_user_updated_date] [datetime] NULL,
	[brochure_activity_user_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_activity_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_balance_amount] [decimal](18, 0) NULL,
	[contact_completion_balance_percentage] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_base_price] [decimal](18, 0) NULL,
	[contact_completion_client_number] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_comment] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_company_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_contact_completion_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_contact_id] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_contract_amount] [decimal](18, 0) NULL,
	[contact_completion_contract_number] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_created_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_creation_date] [datetime] NULL,
	[contact_completion_date_rescheduled] [datetime] NULL,
	[contact_completion_date_saved] [datetime] NULL,
	[contact_completion_discount_amount] [decimal](18, 0) NULL,
	[contact_completion_discount_markup_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_discount_percentage] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_followup_result] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_followup_result_id] [int] NULL,
	[contact_completion_hair_length] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_head_size] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_initial_payment] [decimal](18, 0) NULL,
	[contact_completion_length_price] [decimal](18, 0) NULL,
	[contact_completion_number_of_graphs] [int] NULL,
	[contact_completion_original_appointment_date] [datetime] NULL,
	[contact_completion_referred_to_doctor_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_reschedule_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_sale_no_sale_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_sale_type_code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_sale_type_description] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_services] [int] NULL,
	[contact_completion_show_no_show_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_status_line] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_surgery_consultation_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_surgery_offered_flag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_systems] [int] NULL,
	[contact_completion_time_rescheduled] [datetime] NULL,
	[contact_completion_updated_by_user_code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[contact_completion_updated_date] [datetime] NULL,
 CONSTRAINT [PK_cstd_email_dh_flat] PRIMARY KEY CLUSTERED
(
	[contact_contact_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
