/* CreateDate: 08/30/2021 16:17:22.370 , ModifyDate: 08/30/2021 16:17:22.370 */
GO
CREATE TABLE [dbo].[FactLead_bck300821](
	[ContactKey] [int] NOT NULL,
	[LeadCreationDateKey] [int] NOT NULL,
	[LeadCreationTimeKey] [int] NOT NULL,
	[CenterKey] [int] NOT NULL,
	[SourceKey] [int] NOT NULL,
	[GenderKey] [int] NOT NULL,
	[OccupationKey] [int] NOT NULL,
	[EthnicityKey] [int] NOT NULL,
	[MaritalStatusKey] [int] NOT NULL,
	[HairLossTypeKey] [int] NOT NULL,
	[AgeRangeKey] [int] NOT NULL,
	[EmployeeKey] [int] NOT NULL,
	[PromotionCodeKey] [int] NULL,
	[SalesTypeKey] [int] NULL,
	[Leads] [int] NOT NULL,
	[Appointments] [int] NOT NULL,
	[Shows] [int] NOT NULL,
	[Sales] [int] NOT NULL,
	[Activities] [int] NOT NULL,
	[NoShows] [int] NOT NULL,
	[NoSales] [int] NOT NULL,
	[InsertAuditKey] [int] NOT NULL,
	[UpdateAuditKey] [int] NOT NULL,
	[RowTimeStamp] [timestamp] NOT NULL,
	[AssignedEmployeeKey] [int] NULL,
	[SHOWDIFF] [int] NULL,
	[SALEDIFF] [int] NULL,
	[QuestionAge] [int] NULL,
	[RecentSourceKey] [int] NULL,
	[InvalidLead] [int] NULL,
	[NewBusinessRevenue] [money] NULL,
	[PCPMemberRevenue] [money] NULL,
	[PCPLaserRevenue] [money] NULL,
	[RetailRevenue] [money] NULL,
	[ServiceRevenue] [money] NULL,
	[NBLaserRevenue] [money] NULL
) ON [FG1]
GO
