CREATE TABLE [bief_dds].[DimDate_TEMP](
	[DateKey] [int] NOT NULL,
	[FullDate] [datetime] NULL,
	[ISODate] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearNumber] [smallint] NULL,
	[YearQuarterNumber] [int] NULL,
	[YearMonthNumber] [int] NULL,
	[YearQuarterMonthNumber] [int] NULL,
	[YearWeekNumber] [int] NULL,
	[DateName] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekName] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekNameWithYear] [char](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekShortName] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekShortNameWithYear] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekNumber] [smallint] NULL,
	[FirstDateOfWeek] [datetime] NULL,
	[LastDateOfWeek] [datetime] NULL,
	[DayOfWeek] [smallint] NULL,
	[DayOfWeekName] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsWeekday] [bit] NULL,
	[IsWeekend] [bit] NULL,
	[MonthName] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MonthNameWithYear] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MonthShortName] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MonthShortNameWithYear] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MonthNumber] [smallint] NULL,
	[FirstDateOfMonth] [datetime] NULL,
	[LastDateOfMonth] [datetime] NULL,
	[DayOfMonth] [smallint] NULL,
	[DayOfMonthName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsLastDayOfMonth] [bit] NULL,
	[QuarterName] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuarterNameWithYear] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuarterShortName] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuarterShortNameWithYear] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuarterNumber] [smallint] NULL,
	[FirstDateOfQuarter] [datetime] NULL,
	[LastDateOfQuarter] [datetime] NULL,
	[DayOfQuarter] [smallint] NULL,
	[DayOfQuarterName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalfName] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalfNameWithYear] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalfShortName] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalfShortNameWithYear] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalfNumber] [smallint] NULL,
	[YearHalfNumber] [int] NULL,
	[FirstDateOfHalf] [datetime] NULL,
	[LastDateOfHalf] [datetime] NULL,
	[DayOfHalf] [smallint] NULL,
	[DayOfHalfName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearName] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearShortName] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstDateOfYear] [datetime] NULL,
	[LastDateOfYear] [datetime] NULL,
	[DayOfYear] [smallint] NULL,
	[DayOfYearName] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CalendarQuarter] [smallint] NULL,
	[CalendarYear] [smallint] NULL,
	[CalendarYearMonth] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CalendarYearQtr] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalYear] [smallint] NULL,
	[FiscalWeek] [smallint] NULL,
	[FiscalPeriod] [smallint] NULL,
	[FiscalMonth] [smallint] NULL,
	[FiscalQuarter] [smallint] NULL,
	[FiscalYearFiscalWeek] [int] NULL,
	[FiscalYearFiscalPeriod] [int] NULL,
	[FiscalYearFiscalMonth] [int] NULL,
	[FiscalYearFiscalQuarter] [int] NULL,
	[FiscalYearFiscalQuarterFiscalMonth] [int] NULL,
	[FiscalYearName] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalYearLongName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalYearShortName] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalQuarterName] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalQuarterLongName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalQuarterNameWithYear] [char](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalQuarterLongNameWithYear] [char](34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalQuarterShortName] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalQuarterShortNameWithYear] [char](21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalMonthName] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalMonthNameWithYear] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalMonthShortName] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalMonthShortNameWithYear] [char](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalMonthCalendarShortName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalMonthCalendarShortNameWithYear] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalWeekName] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalWeekLongName] [char](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalWeekNameWithYear] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalWeekLongNameWithYear] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalWeekShortName] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalWeekShortNameWithYear] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalPeriodName] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalPeriodLongName] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalPeriodNameWithYear] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalPeriodLongNameWithYear] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalPeriodShortName] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FiscalPeriodShortNameWithYear] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[msrepl_tran_version] [uniqueidentifier] NOT NULL,
	[CummWorkdays] [int] NULL,
	[MonthWorkdays] [int] NULL,
	[MonthWorkdaysTotal] [int] NULL,
 CONSTRAINT [PK_DimDate_TEMP] PRIMARY KEY CLUSTERED
(
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
