/* CreateDate: 06/30/2017 21:39:08.713 , ModifyDate: 06/30/2017 22:30:43.963 */
GO
CREATE TABLE [dbo].[Canary](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PostTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Canary] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
