/* CreateDate: 03/19/2021 08:58:04.850 , ModifyDate: 03/19/2021 09:50:49.500 */
GO
CREATE TABLE [dbo].[ExtractsForJanuary2021v2](
	[reportcreatedate] [datetime] NULL,
	[FunnelTransactionID] [float] NULL,
	[ContactID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SalesForceTaskID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrightPatternID] [float] NULL,
	[LeadFunnelTransactionID] [float] NULL,
	[SaleforceLeadID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Company] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FunnelStep] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Funnelstatus] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalGCLID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LeadCreateDateUTC] [datetime] NULL,
	[LeadCreateDateEST] [datetime] NULL,
	[ActivityDateEST] [datetime] NULL,
	[Date] [date] NULL,
	[Time] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayPart] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Hour] [float] NULL,
	[Minute] [float] NULL,
	[Seconds] [float] NULL,
	[OriginalContactType] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalSourcecode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignAgency] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignChannel] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignFormat] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignLanguage] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignPromotionCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignStartDate] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignEndDate] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OriginalCampaignStatus] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PostalCode] [float] NULL,
	[Region] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MarketDMA] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterRegion] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterDMA] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterType] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterOwner] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Language] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Gender] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [float] NULL,
	[MobilePhone] [float] NULL,
	[Email] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewContact] [float] NULL,
	[NewLead] [float] NULL,
	[NewAppointment] [float] NULL,
	[NewShow] [float] NULL,
	[NewSale] [float] NULL,
	[NewLeadToAppointment] [float] NULL,
	[NewLeadToShow] [float] NULL,
	[NewLeadToSale] [float] NULL,
	[IsDeleted] [float] NULL
) ON [PRIMARY]
GO
