/* CreateDate: 05/05/2020 17:42:41.240 , ModifyDate: 05/05/2020 17:42:41.240 */
GO
create procedure [sp_MSins_dbocfgConfigurationApplication]
    @c1 int,
    @c2 date,
    @c3 datetime,
    @c4 nvarchar(25),
    @c5 datetime,
    @c6 nvarchar(25),
    @c7 date,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 nvarchar(250),
    @c13 int,
    @c14 int,
    @c15 int,
    @c16 int,
    @c17 int,
    @c18 int,
    @c19 int,
    @c20 datetime,
    @c21 int,
    @c22 int,
    @c23 int,
    @c24 int,
    @c25 bit
as
begin
	insert into [dbo].[cfgConfigurationApplication] (
		[ConfigurationApplicationID],
		[Version32ReleaseDate],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[Version41ReleaseDate],
		[ScheduleCreateRange],
		[HairSystemOrderCounter],
		[HairSystemOrderMaximumDaysInFuture],
		[AccountingExportBatchCounter],
		[AccountingExportDefaultPath],
		[HairSystemTurnaroundDaysRange1],
		[HairSystemTurnaroundDaysRange2],
		[HairSystemTurnaroundDaysRange3],
		[HairSystemTurnaroundLongHairExtraDays],
		[HairSystemTurnaroundLongHairLength],
		[AccountingExportReceiveAPVarianceGLNumber],
		[AccountingExportReceiveAPCreditGLNumber],
		[LastUpdateClientEFT],
		[MonetraProcessingBufferInMinutes],
		[SalesConsultationDayBuffer],
		[NumberOfRefundMonths],
		[PhotoQuality],
		[IsPreviousConsultationWarningEnabled]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		default,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25	)
end
GO
