/* CreateDate: 05/05/2020 17:42:46.673 , ModifyDate: 05/05/2020 17:42:46.673 */
GO
create procedure [sp_MSins_dbodatInventoryShipment]
    @c1 uniqueidentifier,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 datetime,
    @c10 datetime,
    @c11 datetime,
    @c12 nvarchar(50),
    @c13 money,
    @c14 int,
    @c15 nvarchar(50),
    @c16 int,
    @c17 datetime,
    @c18 nvarchar(25),
    @c19 datetime,
    @c20 nvarchar(25),
    @c21 money,
    @c22 int
as
begin
	insert into [dbo].[datInventoryShipment] (
		[InventoryShipmentGUID],
		[InventoryShipmentTypeID],
		[InventoryShipmentStatusID],
		[ShipmentNumber],
		[ShipFromVendorID],
		[ShipFromCenterID],
		[ShipToVendorID],
		[ShipToCenterID],
		[ShipDate],
		[ReceiveDate],
		[CloseDate],
		[InvoiceNumber],
		[InvoiceTotal],
		[InvoiceCount],
		[TrackingNumber],
		[ShipmentMethodID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[InvoiceActualTotal],
		[InvoiceActualCount]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		default,
		@c21,
		@c22	)
end
GO
