/* CreateDate: 05/05/2020 17:42:53.057 , ModifyDate: 05/05/2020 17:42:53.057 */
GO
create procedure [sp_MSins_dbodatTechnicalProfilePermRelaxer]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 int,
    @c13 int,
    @c14 int,
    @c15 int,
    @c16 int,
    @c17 int,
    @c18 int,
    @c19 datetime,
    @c20 nvarchar(25),
    @c21 datetime,
    @c22 nvarchar(25)
as
begin
	insert into [dbo].[datTechnicalProfilePermRelaxer] (
		[TechnicalProfilePermRelaxerID],
		[TechnicalProfileID],
		[PermOwnPermBrandID],
		[PermOwnPermOwnHairRods1ID],
		[PermOwnPermOwnHairRods2ID],
		[PermOwnProcessingTime],
		[PermOwnProcessingTimeUnitID],
		[PermOwnPermTechniqueID],
		[PermSystemPermBrandID],
		[PermSystemPermOwnHairRods1ID],
		[PermSystemPermOwnHairRods2ID],
		[PermSystemProcessingTime],
		[PermSystemProcessingTimeUnitID],
		[PermSystemPermTechniqueID],
		[RelaxerBrandID],
		[RelaxerStrengthID],
		[RelaxerProcessingTime],
		[RelaxerProcessingTimeUnitID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		default	)
end
GO
