/* CreateDate: 05/05/2020 17:42:46.857 , ModifyDate: 05/05/2020 17:42:46.857 */
GO
create procedure [sp_MSins_dbodatCenterFeeBatch]
    @c1 uniqueidentifier,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 datetime,
    @c8 uniqueidentifier,
    @c9 datetime,
    @c10 datetime,
    @c11 nvarchar(25),
    @c12 datetime,
    @c13 nvarchar(25),
    @c14 int,
    @c15 datetime,
    @c16 uniqueidentifier,
    @c17 bit,
    @c18 bit,
    @c19 bit,
    @c20 bit,
    @c21 bit,
    @c22 bit,
    @c23 bit
as
begin
	insert into [dbo].[datCenterFeeBatch] (
		[CenterFeeBatchGUID],
		[CenterID],
		[FeePayCycleID],
		[FeeMonth],
		[FeeYear],
		[CenterFeeBatchStatusId],
		[RunDate],
		[RunByEmployeeGUID],
		[DownloadDate],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[IsExported],
		[ApprovedDate],
		[ApprovedByEmployeeGUID],
		[AreSalesOrdersCreated],
		[IsMonetraProcessingCompleted],
		[AreMonetraResultsProcessed],
		[IsACHFileCreated],
		[AreAccumulatorsExecuted],
		[AreARPaymentsApplied],
		[IsNACHAFileCreated]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		default,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23	)
end
GO
