/* CreateDate: 05/05/2020 17:42:46.243 , ModifyDate: 05/05/2020 17:42:46.243 */
GO
create procedure [sp_MSins_dbolkpHairSystemOrderStatus]
    @c1 int,
    @c2 int,
    @c3 nvarchar(100),
    @c4 nvarchar(10),
    @c5 bit,
    @c6 bit,
    @c7 bit,
    @c8 bit,
    @c9 datetime,
    @c10 nvarchar(25),
    @c11 datetime,
    @c12 nvarchar(25),
    @c13 bit,
    @c14 bit,
    @c15 bit,
    @c16 bit,
    @c17 bit,
    @c18 bit,
    @c19 bit,
    @c20 bit,
    @c21 bit,
    @c22 bit,
    @c23 nvarchar(100)
as
begin
	insert into [dbo].[lkpHairSystemOrderStatus] (
		[HairSystemOrderStatusID],
		[HairSystemOrderStatusSortOrder],
		[HairSystemOrderStatusDescription],
		[HairSystemOrderStatusDescriptionShort],
		[CanApplyFlag],
		[CanTransferFlag],
		[CanEditFlag],
		[IsActiveFlag],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[CanCancelFlag],
		[IsPreallocationFlag],
		[CanRedoFlag],
		[CanRepairFlag],
		[ShowInHistoryFlag],
		[CanAddToStockFlag],
		[IncludeInMembershipCountFlag],
		[CanRequestCreditFlag],
		[IncludeInInventorySnapshotFlag],
		[IsInTransitFlag],
		[DescriptionResourceKey]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		default,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23	)
end
GO
