/* CreateDate: 05/05/2020 17:42:49.757 , ModifyDate: 05/05/2020 17:42:49.757 */
GO
create procedure [sp_MSins_dbodatCreditCardTransactionLog]
    @c1 uniqueidentifier,
    @c2 uniqueidentifier,
    @c3 uniqueidentifier,
    @c4 bigint,
    @c5 datetime,
    @c6 datetime,
    @c7 nvarchar(50),
    @c8 money,
    @c9 nvarchar(100),
    @c10 nvarchar(30),
    @c11 nvarchar(30),
    @c12 nvarchar(4),
    @c13 nvarchar(10),
    @c14 bigint,
    @c15 bit,
    @c16 bit,
    @c17 nvarchar(20),
    @c18 nvarchar(20),
    @c19 nvarchar(20),
    @c20 bit,
    @c21 nvarchar(max),
    @c22 datetime,
    @c23 nvarchar(25),
    @c24 datetime,
    @c25 nvarchar(25),
    @c26 nvarchar(20)
as
begin
	insert into [dbo].[datCreditCardTransactionLog] (
		[CreditCardTransactionLogGUID],
		[SalesOrderTenderGUID],
		[SalesOrderGUID],
		[EFTTransactionID],
		[SecureDate],
		[SettleDate],
		[ApprovalCode],
		[Amount],
		[Verbiage],
		[MSoftCode],
		[PHardCode],
		[Last4Digits],
		[ExpirationDate],
		[MonetraTransactionId],
		[IsTokenUsedFlag],
		[IsCardPresentFlag],
		[EmployeeID],
		[MachineTerminalID],
		[IpAddress],
		[IsSuccessfulFlag],
		[TransactionErrorMessage],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[AVSResult]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		default,
		@c26	)
end
GO
