/* CreateDate: 05/05/2020 17:42:49.707 , ModifyDate: 05/05/2020 17:42:49.707 */
GO
create procedure [sp_MSins_dbodatCommissionCorrection]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 uniqueidentifier,
    @c5 int,
    @c6 uniqueidentifier,
    @c7 int,
    @c8 int,
    @c9 datetime,
    @c10 money,
    @c11 int,
    @c12 nvarchar(200),
    @c13 int,
    @c14 nvarchar(200),
    @c15 datetime,
    @c16 nvarchar(25),
    @c17 datetime,
    @c18 nvarchar(25),
    @c19 nvarchar(200),
    @c20 datetime,
    @c21 datetime
as
begin
	insert into [dbo].[datCommissionCorrection] (
		[CommissionCorrectionID],
		[CenterID],
		[PayPeriodKey],
		[ClientGUID],
		[EmployeePositionID],
		[EmployeeGUID],
		[CommissionPlanID],
		[CommissionPlanSectionID],
		[TransactionDate],
		[AmountToBePaid],
		[CommissionAdjustmentReasonID],
		[ReasonForCorrection],
		[CommissionCorrectionStatusID],
		[ReasonForDenial],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[Comments],
		[StatusChangeDate],
		[PayOnDate]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		default,
		@c19,
		@c20,
		@c21	)
end
GO
