/* CreateDate: 05/05/2020 17:42:37.437 , ModifyDate: 05/05/2020 17:42:37.437 */
GO
create procedure [sp_MSins_dbocfgAccumulator]
    @c1 int,
    @c2 int,
    @c3 nvarchar(50),
    @c4 nvarchar(10),
    @c5 int,
    @c6 bit,
    @c7 bit,
    @c8 int,
    @c9 int,
    @c10 bit,
    @c11 bit,
    @c12 bit,
    @c13 bit,
    @c14 bit,
    @c15 datetime,
    @c16 nvarchar(25),
    @c17 datetime,
    @c18 nvarchar(25),
    @c19 bit,
    @c20 nvarchar(50)
as
begin
	insert into [dbo].[cfgAccumulator] (
		[AccumulatorID],
		[AccumulatorSortOrder],
		[AccumulatorDescription],
		[AccumulatorDescriptionShort],
		[AccumulatorDataTypeID],
		[SalesOrderProcessFlag],
		[SchedulerProcessFlag],
		[SchedulerActionTypeID],
		[SchedulerAdjustmentTypeID],
		[AdjustARBalanceFlag],
		[AdjustContractPriceFlag],
		[AdjustContractPaidFlag],
		[IsVisibleFlag],
		[IsActiveFlag],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[IsVisibleToClient],
		[ClientDescription]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		default,
		@c19,
		@c20	)
end
GO
