/* CreateDate: 05/05/2020 17:42:44.597 , ModifyDate: 05/05/2020 17:42:44.597 */
GO
create procedure [sp_MSins_dbocfgMembershipRule]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 bit,
    @c13 nvarchar(25),
    @c14 datetime,
    @c15 nvarchar(25),
    @c16 datetime,
    @c17 int,
    @c18 int,
    @c19 int,
    @c20 int,
    @c21 int,
    @c22 int,
    @c23 int,
    @c24 int,
    @c25 int,
    @c26 int,
    @c27 int
as
begin
	insert into [dbo].[cfgMembershipRule] (
		[MembershipRuleID],
		[MembershipRuleSortOrder],
		[MembershipRuleTypeID],
		[CurrentMembershipID],
		[NewMembershipID],
		[SalesCodeID],
		[Interval],
		[UnitOfMeasureID],
		[MembershipScreen1ID],
		[MembershipScreen2ID],
		[MembershipScreen3ID],
		[IsActiveFlag],
		[CreateUser],
		[CreateDate],
		[LastUpdateUser],
		[LastUpdate],
		[UpdateStamp],
		[CurrentMembershipStatusID],
		[NewMembershipStatusID],
		[MembershipCancelRuleID],
		[MembershipCancelSalesCodeID],
		[AdditionalNewMembershipID],
		[CenterBusinessTypeID],
		[FromCancelledMembershipSalesCodeID],
		[AddOnID],
		[ReplaceCurrentClientMembershipStatusID],
		[AssociatedAddOnSalesCodeID],
		[AssociatedAddOnNewClientMembershipAddOnStatusID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		default,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27	)
end
GO
