/* CreateDate: 05/05/2020 17:42:52.687 , ModifyDate: 05/05/2020 17:42:52.687 */
GO
create procedure [sp_MSins_dbodatTechnicalProfileExt]
    @c1 int,
    @c2 int,
    @c3 datetime,
    @c4 datetime,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 nvarchar(200),
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 int,
    @c13 bit,
    @c14 int,
    @c15 bit,
    @c16 nvarchar(200),
    @c17 int,
    @c18 int,
    @c19 datetime,
    @c20 nvarchar(25),
    @c21 datetime,
    @c22 nvarchar(25),
    @c23 bit,
    @c24 int,
    @c25 datetime,
    @c26 int,
    @c27 int,
    @c28 int
as
begin
	insert into [dbo].[datTechnicalProfileExt] (
		[TechnicalProfileExtID],
		[TechnicalProfileID],
		[LastTrichoViewDate],
		[LastExtServiceDate],
		[HairHealthID],
		[ScalpHealthID],
		[CleanserUsedSalesCodeID],
		[ElixirFormulation],
		[MassagePressureID],
		[LaserDeviceSalesCodeID],
		[CleanserSalesCodeID],
		[ConditionerSalesCodeID],
		[IsMinoxidilUsed],
		[MinoxidilSalesCodeID],
		[IsScalpEnzymeCleanserUsed],
		[Other],
		[ServiceDuration],
		[ServiceTimeUnitID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[IsSurgeryClient],
		[GraftCount],
		[LastSurgeryDate],
		[OtherServiceSalesCodeID],
		[OtherServiceDuration],
		[OtherServiceTimeUnitID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		default,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28	)
end
GO
