/* CreateDate: 05/05/2020 17:42:40.833 , ModifyDate: 05/05/2020 17:42:40.833 */
GO
create procedure [sp_MSins_dbocfgMembershipPromotion]
    @c1 int,
    @c2 int,
    @c3 nvarchar(100),
    @c4 nvarchar(10),
    @c5 int,
    @c6 datetime,
    @c7 datetime,
    @c8 decimal(6,2),
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 int,
    @c13 int,
    @c14 int,
    @c15 bit,
    @c16 datetime,
    @c17 nvarchar(25),
    @c18 datetime,
    @c19 nvarchar(25),
    @c20 int,
    @c21 int,
    @c22 int,
    @c23 int
as
begin
	insert into [dbo].[cfgMembershipPromotion] (
		[MembershipPromotionID],
		[MembershipPromotionSortOrder],
		[MembershipPromotionDescription],
		[MembershipPromotionDescriptionShort],
		[MembershipPromotionTypeID],
		[BeginDate],
		[EndDate],
		[Amount],
		[RevenueGroupID],
		[BusinessSegmentID],
		[AdditionalSystems],
		[AdditionalServices],
		[AdditionalSolutions],
		[AdditionalProductKits],
		[IsActiveFlag],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[AdditionalHCSL],
		[AdditionalStrands],
		[MembershipPromotionGroupID],
		[MembershipPromotionAdjustmentTypeID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		default,
		@c20,
		@c21,
		@c22,
		@c23	)
end
GO
