/* CreateDate: 05/05/2020 17:42:47.600 , ModifyDate: 05/05/2020 17:42:47.600 */
GO
create procedure [sp_MSins_dbodatAppointment]
    @c1 uniqueidentifier,
    @c2 int,
    @c3 uniqueidentifier,
    @c4 uniqueidentifier,
    @c5 uniqueidentifier,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 date,
    @c12 time(0),
    @c13 time(0),
    @c14 datetime,
    @c15 datetime,
    @c16 nvarchar(500),
    @c17 bit,
    @c18 bit,
    @c19 varchar(1024),
    @c20 datetime,
    @c21 nvarchar(25),
    @c22 datetime,
    @c23 nvarchar(25),
    @c24 int,
    @c25 bit,
    @c26 nchar(10),
    @c27 nchar(10),
    @c28 bit,
    @c29 nvarchar(25),
    @c30 datetime,
    @c31 int,
    @c32 int,
    @c33 int,
    @c34 bit,
    @c35 nvarchar(18),
    @c36 nvarchar(18),
    @c37 int,
    @c38 datetime,
    @c39 datetime,
    @c40 bit
as
begin
	insert into [dbo].[datAppointment] (
		[AppointmentGUID],
		[AppointmentID_Temp],
		[ClientGUID],
		[ClientMembershipGUID],
		[ParentAppointmentGUID],
		[CenterID],
		[ClientHomeCenterID],
		[ResourceID],
		[ConfirmationTypeID],
		[AppointmentTypeID],
		[AppointmentDate],
		[StartTime],
		[EndTime],
		[CheckinTime],
		[CheckoutTime],
		[AppointmentSubject],
		[CanPrintCommentFlag],
		[IsNonAppointmentFlag],
		[RecurrenceRule],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[AppointmentStatusID],
		[IsDeletedFlag],
		[OnContactActivityID],
		[OnContactContactID],
		[IsAuthorizedFlag],
		[LastChangeUser],
		[LastChangeDate],
		[ScalpHealthID],
		[AppointmentPriorityColorID],
		[CompletedVisitTypeID],
		[IsFullTrichoView],
		[SalesforceContactID],
		[SalesforceTaskID],
		[KorvueID],
		[ServiceStartTime],
		[ServiceEndTime],
		[IsClientContactInformationConfirmed]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		default,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40	)
end
GO
