/* CreateDate: 05/05/2020 17:42:42.020 , ModifyDate: 05/05/2020 17:42:42.020 */
GO
create procedure [sp_MSins_dbolkpHairSystemCurl]
    @c1 int,
    @c2 int,
    @c3 nvarchar(100),
    @c4 nvarchar(10),
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 bit,
    @c10 datetime,
    @c11 nvarchar(25),
    @c12 datetime,
    @c13 nvarchar(25),
    @c14 bit,
    @c15 bit,
    @c16 int,
    @c17 bit,
    @c18 bit
as
begin
	insert into [dbo].[lkpHairSystemCurl] (
		[HairSystemCurlID],
		[HairSystemCurlSortOrder],
		[HairSystemCurlDescription],
		[HairSystemCurlDescriptionShort],
		[HumanHairLengthMinimum],
		[HumanHairLengthMaximum],
		[SyntheticHairLengthMinimum],
		[SyntheticHairLengthMaximum],
		[IsActiveFlag],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[IsAllowHumanGreyPercentageFlag],
		[IsAllowSyntheticGreyPercentageFlag],
		[HairSystemCurlGroupID],
		[IsCuticleIntactAvailableFlag],
		[IsRootShadowingAvailableFlag]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		default,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18	)
end
GO
