/* CreateDate: 05/05/2020 17:42:48.447 , ModifyDate: 05/05/2020 17:42:48.447 */
GO
create procedure [sp_MSins_dbodatAccumulatorAdjustment]
    @c1 uniqueidentifier,
    @c2 uniqueidentifier,
    @c3 uniqueidentifier,
    @c4 uniqueidentifier,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 decimal(21,6),
    @c12 decimal(21,6),
    @c13 date,
    @c14 date,
    @c15 datetime,
    @c16 nvarchar(25),
    @c17 datetime,
    @c18 nvarchar(25),
    @c19 uniqueidentifier,
    @c20 int
as
begin
	insert into [dbo].[datAccumulatorAdjustment] (
		[AccumulatorAdjustmentGUID],
		[ClientMembershipGUID],
		[SalesOrderDetailGUID],
		[AppointmentGUID],
		[AccumulatorID],
		[AccumulatorActionTypeID],
		[QuantityUsedOriginal],
		[QuantityUsedAdjustment],
		[QuantityTotalOriginal],
		[QuantityTotalAdjustment],
		[MoneyOriginal],
		[MoneyAdjustment],
		[DateOriginal],
		[DateAdjustment],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[SalesOrderTenderGuid],
		[ClientMembershipAddOnID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		default,
		@c19,
		@c20	)
end
GO
