/* CreateDate: 05/05/2020 17:42:48.130 , ModifyDate: 05/05/2020 17:42:48.130 */
GO
create procedure [sp_MSins_dbodatSalesOrderDetail]
    @c1 uniqueidentifier,
    @c2 int,
    @c3 uniqueidentifier,
    @c4 int,
    @c5 int,
    @c6 decimal(21,6),
    @c7 money,
    @c8 money,
    @c9 money,
    @c10 decimal(6,5),
    @c11 decimal(6,5),
    @c12 bit,
    @c13 uniqueidentifier,
    @c14 int,
    @c15 money,
    @c16 uniqueidentifier,
    @c17 uniqueidentifier,
    @c18 uniqueidentifier,
    @c19 uniqueidentifier,
    @c20 uniqueidentifier,
    @c21 int,
    @c22 datetime,
    @c23 nvarchar(25),
    @c24 datetime,
    @c25 nvarchar(25),
    @c26 int,
    @c27 varchar(10),
    @c28 varchar(10),
    @c29 decimal(21,6),
    @c30 int,
    @c31 int,
    @c32 uniqueidentifier,
    @c33 int,
    @c34 bit,
    @c35 int,
    @c36 int,
    @c37 nvarchar(200),
    @c38 nvarchar(50),
    @c39 nvarchar(20),
    @c40 uniqueidentifier,
    @c41 datetime,
    @c42 bit,
    @c43 money,
    @c44 int,
    @c45 int,
    @c46 int,
    @c47 int
as
begin
	insert into [dbo].[datSalesOrderDetail] (
		[SalesOrderDetailGUID],
		[TransactionNumber_Temp],
		[SalesOrderGUID],
		[SalesCodeID],
		[Quantity],
		[Price],
		[Discount],
		[Tax1],
		[Tax2],
		[TaxRate1],
		[TaxRate2],
		[IsRefundedFlag],
		[RefundedSalesOrderDetailGUID],
		[RefundedTotalQuantity],
		[RefundedTotalPrice],
		[Employee1GUID],
		[Employee2GUID],
		[Employee3GUID],
		[Employee4GUID],
		[PreviousClientMembershipGUID],
		[NewCenterID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[Center_Temp],
		[performer_temp],
		[performer2_temp],
		[Member1Price_temp],
		[CancelReasonID],
		[EntrySortOrder],
		[HairSystemOrderGUID],
		[DiscountTypeID],
		[BenefitTrackingEnabledFlag],
		[MembershipPromotionID],
		[MembershipOrderReasonID],
		[MembershipNotes],
		[GenericSalesCodeDescription],
		[SalesCodeSerialNumber],
		[WriteOffSalesOrderDetailGUID],
		[NSFBouncedDate],
		[IsWrittenOffFlag],
		[InterCompanyPrice],
		[TaxType1ID],
		[TaxType2ID],
		[ClientMembershipAddOnID],
		[NCCMembershipPromotionID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		default,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40,
		@c41,
		@c42,
		@c43,
		@c44,
		@c45,
		@c46,
		@c47	)
end
GO
