/* CreateDate: 05/05/2020 17:42:49.257 , ModifyDate: 05/05/2020 17:42:49.257 */
GO
create procedure [sp_MSins_dbodatClientEFT]
    @c1 uniqueidentifier,
    @c2 uniqueidentifier,
    @c3 uniqueidentifier,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 nvarchar(4),
    @c9 date,
    @c10 nvarchar(100),
    @c11 nvarchar(15),
    @c12 nvarchar(25),
    @c13 nvarchar(25),
    @c14 nvarchar(50),
    @c15 datetime,
    @c16 bit,
    @c17 datetime,
    @c18 nvarchar(25),
    @c19 datetime,
    @c20 nvarchar(25),
    @c21 datetime,
    @c22 datetime,
    @c23 datetime,
    @c24 int,
    @c25 nvarchar(50),
    @c26 bit,
    @c27 int,
    @c28 nvarchar(100)
as
begin
	insert into [dbo].[datClientEFT] (
		[ClientEFTGUID],
		[ClientGUID],
		[ClientMembershipGUID],
		[EFTAccountTypeID],
		[EFTStatusID],
		[FeePayCycleID],
		[CreditCardTypeID],
		[AccountNumberLast4Digits],
		[AccountExpiration],
		[BankName],
		[BankPhone],
		[BankRoutingNumber],
		[BankAccountNumber],
		[EFTProcessorToken],
		[LastRun],
		[IsActiveFlag],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[Freeze_Start],
		[Freeze_End],
		[LastPaymentDate],
		[FeeFreezeReasonId],
		[CardHolderName],
		[IsEFTTokenValidFlag],
		[BankCountryID],
		[FeeFreezeReasonDescription]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		default,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28	)
end
GO
