/* CreateDate: 05/05/2020 17:42:52.353 , ModifyDate: 05/05/2020 17:42:52.353 */
GO
create procedure [sp_MSins_dbodatTechnicalProfileBio]
    @c1 int,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 bit,
    @c12 nvarchar(50),
    @c13 datetime,
    @c14 datetime,
    @c15 int,
    @c16 int,
    @c17 int,
    @c18 int,
    @c19 int,
    @c20 int,
    @c21 int,
    @c22 datetime,
    @c23 nvarchar(25),
    @c24 datetime,
    @c25 nvarchar(25),
    @c26 bit,
    @c27 bit,
    @c28 bit
as
begin
	insert into [dbo].[datTechnicalProfileBio] (
		[TechnicalProfileBioID],
		[TechnicalProfileID],
		[HairSystemID],
		[AdhesiveFront1ID],
		[AdhesiveFront2ID],
		[AdhesivePerimeter1ID],
		[AdhesivePerimeter2ID],
		[AdhesivePerimeter3ID],
		[RemovalProcessID],
		[AdhesiveSolventID],
		[IsClientUsingOwnHairline],
		[DistanceHairlineToNose],
		[LastTemplateDate],
		[LastTrimDate],
		[ApplicationDuration],
		[ApplicationTimeUnitID],
		[FullServiceDuration],
		[FullServiceTimeUnitID],
		[OtherServiceSalesCodeID],
		[OtherServiceDuration],
		[OtherServiceTimeUnitID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[IsHairOrderReviewRequired],
		[IsHairSystemColorRequired],
		[IsHairSystemHighlightRequired]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		default,
		@c26,
		@c27,
		@c28	)
end
GO
