/* CreateDate: 05/05/2020 17:42:47.800 , ModifyDate: 05/05/2020 17:42:47.800 */
GO
create procedure [sp_MSins_dbodatSalesOrder]
    @c1 uniqueidentifier,
    @c2 int,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 uniqueidentifier,
    @c8 uniqueidentifier,
    @c9 uniqueidentifier,
    @c10 uniqueidentifier,
    @c11 datetime,
    @c12 nvarchar(50),
    @c13 bit,
    @c14 bit,
    @c15 bit,
    @c16 uniqueidentifier,
    @c17 uniqueidentifier,
    @c18 nvarchar(15),
    @c19 bit,
    @c20 bit,
    @c21 uniqueidentifier,
    @c22 datetime,
    @c23 nvarchar(25),
    @c24 datetime,
    @c25 nvarchar(25),
    @c26 uniqueidentifier,
    @c27 bit,
    @c28 bit,
    @c29 varchar(10),
    @c30 datetime,
    @c31 uniqueidentifier,
    @c32 uniqueidentifier,
    @c33 int,
    @c34 uniqueidentifier,
    @c35 int,
    @c36 uniqueidentifier,
    @c37 uniqueidentifier,
    @c38 uniqueidentifier,
    @c39 int,
    @c40 int,
    @c41 nvarchar(100)
as
begin
	insert into [dbo].[datSalesOrder] (
		[SalesOrderGUID],
		[TenderTransactionNumber_Temp],
		[TicketNumber_Temp],
		[CenterID],
		[ClientHomeCenterID],
		[SalesOrderTypeID],
		[ClientGUID],
		[ClientMembershipGUID],
		[AppointmentGUID],
		[HairSystemOrderGUID],
		[OrderDate],
		[InvoiceNumber],
		[IsTaxExemptFlag],
		[IsVoidedFlag],
		[IsClosedFlag],
		[RegisterCloseGUID],
		[EmployeeGUID],
		[FulfillmentNumber],
		[IsWrittenOffFlag],
		[IsRefundedFlag],
		[RefundedSalesOrderGUID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[ParentSalesOrderGUID],
		[IsSurgeryReversalFlag],
		[IsGuaranteeFlag],
		[cashier_temp],
		[ctrOrderDate],
		[CenterFeeBatchGUID],
		[CenterDeclineBatchGUID],
		[RegisterID],
		[EndOfDayGUID],
		[IncomingRequestID],
		[WriteOffSalesOrderGUID],
		[NSFSalesOrderGUID],
		[ChargeBackSalesOrderGUID],
		[ChargebackReasonID],
		[InterCompanyTransactionID],
		[WriteOffReasonDescription]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		default,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40,
		@c41	)
end
GO
