/* CreateDate: 05/05/2020 17:42:53.503 , ModifyDate: 05/05/2020 17:42:53.503 */
GO
create procedure [sp_MSins_dbodatTechnicalProfileXtrands]
    @c1 int,
    @c2 int,
    @c3 datetime,
    @c4 datetime,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 nvarchar(200),
    @c11 bit,
    @c12 int,
    @c13 int,
    @c14 int,
    @c15 datetime,
    @c16 nvarchar(25),
    @c17 datetime,
    @c18 nvarchar(25),
    @c19 int,
    @c20 int,
    @c21 int,
    @c22 int
as
begin
	insert into [dbo].[datTechnicalProfileXtrands] (
		[TechnicalProfileXtrandsID],
		[TechnicalProfileID],
		[LastTrichoViewDate],
		[LastXtrandsServiceDate],
		[HairStrandGroupID],
		[HairHealthID],
		[LaserDeviceSalesCodeID],
		[ShampooSalesCodeID],
		[ConditionerSalesCodeID],
		[Other],
		[IsMinoxidilUsed],
		[MinoxidilSalesCodeID],
		[ServiceDuration],
		[ServiceTimeUnitID],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp],
		[Strands],
		[OtherServiceSalesCodeID],
		[OtherServiceDuration],
		[OtherServiceTimeUnitID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		default,
		@c19,
		@c20,
		@c21,
		@c22	)
end
GO
