/* CreateDate: 05/05/2020 17:42:51.637 , ModifyDate: 05/05/2020 17:42:51.637 */
GO
create procedure [sp_MSins_dbodatPayCycleTransaction]
    @c1 uniqueidentifier,
    @c2 int,
    @c3 uniqueidentifier,
    @c4 uniqueidentifier,
    @c5 uniqueidentifier,
    @c6 uniqueidentifier,
    @c7 bigint,
    @c8 nvarchar(50),
    @c9 money,
    @c10 money,
    @c11 money,
    @c12 nvarchar(100),
    @c13 nvarchar(30),
    @c14 nvarchar(30),
    @c15 nvarchar(4),
    @c16 nvarchar(10),
    @c17 bit,
    @c18 bit,
    @c19 bit,
    @c20 bit,
    @c21 nvarchar(max),
    @c22 nvarchar(20),
    @c23 nchar(1),
    @c24 datetime,
    @c25 nvarchar(25),
    @c26 datetime,
    @c27 nvarchar(25)
as
begin
	insert into [dbo].[datPayCycleTransaction] (
		[PayCycleTransactionGUID],
		[PayCycleTransactionTypeID],
		[CenterFeeBatchGUID],
		[CenterDeclineBatchGUID],
		[SalesOrderGUID],
		[ClientGUID],
		[ProcessorTransactionID],
		[ApprovalCode],
		[FeeAmount],
		[TaxAmount],
		[ChargeAmount],
		[Verbiage],
		[SoftCode],
		[HardCode],
		[Last4Digits],
		[ExpirationDate],
		[IsTokenUsedFlag],
		[IsCardPresentFlag],
		[IsSuccessfulFlag],
		[IsReprocessFlag],
		[TransactionErrorMessage],
		[AVSResult],
		[HCStatusCode],
		[CreateDate],
		[CreateUser],
		[LastUpdate],
		[LastUpdateUser],
		[UpdateStamp]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		default	)
end
GO
