/* CreateDate: 03/17/2022 15:12:17.067 , ModifyDate: 03/17/2022 15:12:17.067 */
GO
CREATE PROCEDURE [SF].[sp_Account_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Account])
RETURN ;

BEGIN TRY
;MERGE [SF].[Account] AS [t]
USING [SFStaging].[Account] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[IsDeleted] = [t].[IsDeleted]
	, [t].[MasterRecordId] = [t].[MasterRecordId]
	, [t].[Name] = [t].[Name]
	, [t].[LastName] = [t].[LastName]
	, [t].[FirstName] = [t].[FirstName]
	, [t].[Salutation] = [t].[Salutation]
	, [t].[MiddleName] = [t].[MiddleName]
	, [t].[Suffix] = [t].[Suffix]
	, [t].[Type] = [t].[Type]
	, [t].[RecordTypeId] = [t].[RecordTypeId]
	, [t].[ParentId] = [t].[ParentId]
	, [t].[BillingStreet] = [t].[BillingStreet]
	, [t].[BillingCity] = [t].[BillingCity]
	, [t].[BillingState] = [t].[BillingState]
	, [t].[BillingPostalCode] = [t].[BillingPostalCode]
	, [t].[BillingCountry] = [t].[BillingCountry]
	, [t].[BillingStateCode] = [t].[BillingStateCode]
	, [t].[BillingCountryCode] = [t].[BillingCountryCode]
	, [t].[BillingLatitude] = [t].[BillingLatitude]
	, [t].[BillingLongitude] = [t].[BillingLongitude]
	, [t].[BillingGeocodeAccuracy] = [t].[BillingGeocodeAccuracy]
	, [t].[ShippingStreet] = [t].[ShippingStreet]
	, [t].[ShippingCity] = [t].[ShippingCity]
	, [t].[ShippingState] = [t].[ShippingState]
	, [t].[ShippingPostalCode] = [t].[ShippingPostalCode]
	, [t].[ShippingCountry] = [t].[ShippingCountry]
	, [t].[ShippingStateCode] = [t].[ShippingStateCode]
	, [t].[ShippingCountryCode] = [t].[ShippingCountryCode]
	, [t].[ShippingLatitude] = [t].[ShippingLatitude]
	, [t].[ShippingLongitude] = [t].[ShippingLongitude]
	, [t].[ShippingGeocodeAccuracy] = [t].[ShippingGeocodeAccuracy]
	, [t].[Phone] = [t].[Phone]
	, [t].[Fax] = [t].[Fax]
	, [t].[AccountNumber] = [t].[AccountNumber]
	, [t].[Website] = [t].[Website]
	, [t].[PhotoUrl] = [t].[PhotoUrl]
	, [t].[Sic] = [t].[Sic]
	, [t].[Industry] = [t].[Industry]
	, [t].[AnnualRevenue] = [t].[AnnualRevenue]
	, [t].[NumberOfEmployees] = [t].[NumberOfEmployees]
	, [t].[Ownership] = [t].[Ownership]
	, [t].[TickerSymbol] = [t].[TickerSymbol]
	, [t].[Description] = [t].[Description]
	, [t].[Rating] = [t].[Rating]
	, [t].[Site] = [t].[Site]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[OwnerId] = [t].[OwnerId]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastActivityDate] = [t].[LastActivityDate]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[PersonContactId] = [t].[PersonContactId]
	, [t].[IsPersonAccount] = [t].[IsPersonAccount]
	, [t].[PersonMailingStreet] = [t].[PersonMailingStreet]
	, [t].[PersonMailingCity] = [t].[PersonMailingCity]
	, [t].[PersonMailingState] = [t].[PersonMailingState]
	, [t].[PersonMailingPostalCode] = [t].[PersonMailingPostalCode]
	, [t].[PersonMailingCountry] = [t].[PersonMailingCountry]
	, [t].[PersonMailingStateCode] = [t].[PersonMailingStateCode]
	, [t].[PersonMailingCountryCode] = [t].[PersonMailingCountryCode]
	, [t].[PersonMailingLatitude] = [t].[PersonMailingLatitude]
	, [t].[PersonMailingLongitude] = [t].[PersonMailingLongitude]
	, [t].[PersonMailingGeocodeAccuracy] = [t].[PersonMailingGeocodeAccuracy]
	, [t].[PersonMobilePhone] = [t].[PersonMobilePhone]
	, [t].[PersonHomePhone] = [t].[PersonHomePhone]
	, [t].[PersonOtherPhone] = [t].[PersonOtherPhone]
	, [t].[PersonAssistantPhone] = [t].[PersonAssistantPhone]
	, [t].[PersonEmail] = [t].[PersonEmail]
	, [t].[PersonTitle] = [t].[PersonTitle]
	, [t].[PersonDepartment] = [t].[PersonDepartment]
	, [t].[PersonDoNotCall] = [t].[PersonDoNotCall]
	, [t].[PersonLastCURequestDate] = [t].[PersonLastCURequestDate]
	, [t].[PersonLastCUUpdateDate] = [t].[PersonLastCUUpdateDate]
	, [t].[PersonEmailBouncedReason] = [t].[PersonEmailBouncedReason]
	, [t].[PersonEmailBouncedDate] = [t].[PersonEmailBouncedDate]
	, [t].[Jigsaw] = [t].[Jigsaw]
	, [t].[JigsawCompanyId] = [t].[JigsawCompanyId]
	, [t].[AccountSource] = [t].[AccountSource]
	, [t].[SicDesc] = [t].[SicDesc]
	, [t].[OperatingHoursId] = [t].[OperatingHoursId]
	, [t].[Active__c] = [t].[Active__c]
	, [t].[Company__c] = [t].[Company__c]
	, [t].[ConectCreationDate__c] = [t].[ConectCreationDate__c]
	, [t].[ConectLastUpdate__c] = [t].[ConectLastUpdate__c]
	, [t].[External_Id__c] = [t].[External_Id__c]
	, [t].[PersonMobilePhone_Number_Normalized__c] = [t].[PersonMobilePhone_Number_Normalized__c]
	, [t].[Status__c] = [t].[Status__c]
	, [t].[Count_Close_Won_Opportunities__c] = [t].[Count_Close_Won_Opportunities__c]
	, [t].[ClientIdentifier__c] = [t].[ClientIdentifier__c]
	, [t].[Occupation__c] = [t].[Occupation__c]
	, [t].[AreaManager__c] = [t].[AreaManager__c]
	, [t].[Area__c] = [t].[Area__c]
	, [t].[AssistantManager__c] = [t].[AssistantManager__c]
	, [t].[BackLinePhone__c] = [t].[BackLinePhone__c]
	, [t].[BestTressedOffered__c] = [t].[BestTressedOffered__c]
	, [t].[CenterAlert__c] = [t].[CenterAlert__c]
	, [t].[CenterOwner__c] = [t].[CenterOwner__c]
	, [t].[CenterType__c] = [t].[CenterType__c]
	, [t].[CompanyID__c] = [t].[CompanyID__c]
	, [t].[ConfirmationCallerIDEnglish__c] = [t].[ConfirmationCallerIDEnglish__c]
	, [t].[ConfirmationCallerIDFrench__c] = [t].[ConfirmationCallerIDFrench__c]
	, [t].[ConfirmationCallerIDSpanish__c] = [t].[ConfirmationCallerIDSpanish__c]
	, [t].[CustomerServiceLine__c] = [t].[CustomerServiceLine__c]
	, [t].[Customer_Status__c] = [t].[Customer_Status__c]
	, [t].[DNCDateMobilePhone__c] = [t].[DNCDateMobilePhone__c]
	, [t].[DNCDatePhone__c] = [t].[DNCDatePhone__c]
	, [t].[DNCValidationMobilePhone__c] = [t].[DNCValidationMobilePhone__c]
	, [t].[DNCValidationPhone__c] = [t].[DNCValidationPhone__c]
	, [t].[DisplayName__c] = [t].[DisplayName__c]
	, [t].[ImageConsultant__c] = [t].[ImageConsultant__c]
	, [t].[MDPOffered__c] = [t].[MDPOffered__c]
	, [t].[MDPPerformed__c] = [t].[MDPPerformed__c]
	, [t].[ManagerName__c] = [t].[ManagerName__c]
	, [t].[MgrCellPhone__c] = [t].[MgrCellPhone__c]
	, [t].[OfferPRP__c] = [t].[OfferPRP__c]
	, [t].[OtherCallerIDEnglish__c] = [t].[OtherCallerIDEnglish__c]
	, [t].[OtherCallerIDFrench__c] = [t].[OtherCallerIDFrench__c]
	, [t].[OtherCallerIDSpanish__c] = [t].[OtherCallerIDSpanish__c]
	, [t].[OutboundDialingAllowed__c] = [t].[OutboundDialingAllowed__c]
	, [t].[ProfileCode__c] = [t].[ProfileCode__c]
	, [t].[Region__c] = [t].[Region__c]
	, [t].[Service_Territory__c] = [t].[Service_Territory__c]
	, [t].[SurgeryOffered__c] = [t].[SurgeryOffered__c]
	, [t].[TimeZone__c] = [t].[TimeZone__c]
	, [t].[Virtual__c] = [t].[Virtual__c]
	, [t].[WebPhone__c] = [t].[WebPhone__c]
	, [t].[X1Apptperslot__c] = [t].[X1Apptperslot__c]
	, [t].[ClientGUID__c] = [t].[ClientGUID__c]
	, [t].[Goals_Expectations__c] = [t].[Goals_Expectations__c]
	, [t].[How_many_times_a_week_do_you_think__c] = [t].[How_many_times_a_week_do_you_think__c]
	, [t].[How_much_time_a_week_do_you_spend__c] = [t].[How_much_time_a_week_do_you_spend__c]
	, [t].[Other_Reason__c] = [t].[Other_Reason__c]
	, [t].[What_are_your_main_concerns_today__c] = [t].[What_are_your_main_concerns_today__c]
	, [t].[What_else_would_be_helpful_for_your__c] = [t].[What_else_would_be_helpful_for_your__c]
	, [t].[What_methods_have_you_used_or_currently__c] = [t].[What_methods_have_you_used_or_currently__c]
	, [t].[fferpcore__ExemptionCertificate__c] = [t].[fferpcore__ExemptionCertificate__c]
	, [t].[fferpcore__IsBillingAddressValidated__c] = [t].[fferpcore__IsBillingAddressValidated__c]
	, [t].[fferpcore__IsShippingAddressValidated__c] = [t].[fferpcore__IsShippingAddressValidated__c]
	, [t].[fferpcore__MaterializedBillingAddressValidated__c] = [t].[fferpcore__MaterializedBillingAddressValidated__c]
	, [t].[fferpcore__MaterializedShippingAddressValidated__c] = [t].[fferpcore__MaterializedShippingAddressValidated__c]
	, [t].[fferpcore__OutputVatCode__c] = [t].[fferpcore__OutputVatCode__c]
	, [t].[fferpcore__SalesTaxStatus__c] = [t].[fferpcore__SalesTaxStatus__c]
	, [t].[fferpcore__TaxCode1__c] = [t].[fferpcore__TaxCode1__c]
	, [t].[fferpcore__TaxCode2__c] = [t].[fferpcore__TaxCode2__c]
	, [t].[fferpcore__TaxCode3__c] = [t].[fferpcore__TaxCode3__c]
	, [t].[fferpcore__TaxCountryCode__c] = [t].[fferpcore__TaxCountryCode__c]
	, [t].[fferpcore__ValidatedBillingCity__c] = [t].[fferpcore__ValidatedBillingCity__c]
	, [t].[fferpcore__ValidatedBillingCountry__c] = [t].[fferpcore__ValidatedBillingCountry__c]
	, [t].[fferpcore__ValidatedBillingPostalCode__c] = [t].[fferpcore__ValidatedBillingPostalCode__c]
	, [t].[fferpcore__ValidatedBillingState__c] = [t].[fferpcore__ValidatedBillingState__c]
	, [t].[fferpcore__ValidatedBillingStreet__c] = [t].[fferpcore__ValidatedBillingStreet__c]
	, [t].[fferpcore__ValidatedShippingCity__c] = [t].[fferpcore__ValidatedShippingCity__c]
	, [t].[fferpcore__ValidatedShippingCountry__c] = [t].[fferpcore__ValidatedShippingCountry__c]
	, [t].[fferpcore__ValidatedShippingPostalCode__c] = [t].[fferpcore__ValidatedShippingPostalCode__c]
	, [t].[fferpcore__ValidatedShippingState__c] = [t].[fferpcore__ValidatedShippingState__c]
	, [t].[fferpcore__ValidatedShippingStreet__c] = [t].[fferpcore__ValidatedShippingStreet__c]
	, [t].[fferpcore__VatRegistrationNumber__c] = [t].[fferpcore__VatRegistrationNumber__c]
	, [t].[fferpcore__VatStatus__c] = [t].[fferpcore__VatStatus__c]
	, [t].[ffbf__AccountParticulars__c] = [t].[ffbf__AccountParticulars__c]
	, [t].[ffbf__BankBIC__c] = [t].[ffbf__BankBIC__c]
	, [t].[ffbf__PaymentCode__c] = [t].[ffbf__PaymentCode__c]
	, [t].[ffbf__PaymentCountryISO__c] = [t].[ffbf__PaymentCountryISO__c]
	, [t].[ffbf__PaymentPriority__c] = [t].[ffbf__PaymentPriority__c]
	, [t].[ffbf__PaymentRoutingMethod__c] = [t].[ffbf__PaymentRoutingMethod__c]
	, [t].[SCMFFA__Company_Name__c] = [t].[SCMFFA__Company_Name__c]
	, [t].[ffaci__CurrencyCulture__c] = [t].[ffaci__CurrencyCulture__c]
	, [t].[Service_Territory_Time_Zone__c] = [t].[Service_Territory_Time_Zone__c]
	, [t].[rh2__testCurrency__c] = [t].[rh2__testCurrency__c]
	, [t].[Initial_Campaign_Source__c] = [t].[Initial_Campaign_Source__c]
	, [t].[Landing_Page_Form_Submitted_Date__c] = [t].[Landing_Page_Form_Submitted_Date__c]
	, [t].[Age__pc] = [t].[Age__pc]
	, [t].[Birthdate__pc] = [t].[Birthdate__pc]
	, [t].[DoNotContact__pc] = [t].[DoNotContact__pc]
	, [t].[DoNotEmail__pc] = [t].[DoNotEmail__pc]
	, [t].[DoNotMail__pc] = [t].[DoNotMail__pc]
	, [t].[DoNotText__pc] = [t].[DoNotText__pc]
	, [t].[Ethnicity__pc] = [t].[Ethnicity__pc]
	, [t].[Gender__pc] = [t].[Gender__pc]
	, [t].[HairLossExperience__pc] = [t].[HairLossExperience__pc]
	, [t].[HairLossFamily__pc] = [t].[HairLossFamily__pc]
	, [t].[HairLossOrVolume__pc] = [t].[HairLossOrVolume__pc]
	, [t].[HairLossProductOther__pc] = [t].[HairLossProductOther__pc]
	, [t].[HairLossProductUsed__pc] = [t].[HairLossProductUsed__pc]
	, [t].[HairLossSpot__pc] = [t].[HairLossSpot__pc]
	, [t].[HardCopyPreferred__pc] = [t].[HardCopyPreferred__pc]
	, [t].[Language__pc] = [t].[Language__pc]
	, [t].[MaritalStatus__pc] = [t].[MaritalStatus__pc]
	, [t].[Text_Reminder_Opt_In__pc] = [t].[Text_Reminder_Opt_In__pc]
	, [t].[rh2__Currency_Test__pc] = [t].[rh2__Currency_Test__pc]
	, [t].[rh2__Describe__pc] = [t].[rh2__Describe__pc]
	, [t].[rh2__Formula_Test__pc] = [t].[rh2__Formula_Test__pc]
	, [t].[rh2__Integer_Test__pc] = [t].[rh2__Integer_Test__pc]
	, [t].[Next_Milestone_Event__pc] = [t].[Next_Milestone_Event__pc]
	, [t].[Next_Milestone_Event_Date__pc] = [t].[Next_Milestone_Event_Date__pc]
	, [t].[Bosley_Center_Number__pc] = [t].[Bosley_Center_Number__pc]
	, [t].[Bosley_Client_Id__pc] = [t].[Bosley_Client_Id__pc]
	, [t].[Bosley_Legacy_Source_Code__pc] = [t].[Bosley_Legacy_Source_Code__pc]
	, [t].[Bosley_Salesforce_Id__pc] = [t].[Bosley_Salesforce_Id__pc]
	, [t].[Bosley_Siebel_Id__pc] = [t].[Bosley_Siebel_Id__pc]
	, [t].[Contact_ID_18_dig__pc] = [t].[Contact_ID_18_dig__pc]
	, [t].[Landing_Page_Form_Submitted_Date__pc] = [t].[Landing_Page_Form_Submitted_Date__pc]
	, [t].[Personal_Photo__pc] = [t].[Personal_Photo__pc]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [IsDeleted]
	, [MasterRecordId]
	, [Name]
	, [LastName]
	, [FirstName]
	, [Salutation]
	, [MiddleName]
	, [Suffix]
	, [Type]
	, [RecordTypeId]
	, [ParentId]
	, [BillingStreet]
	, [BillingCity]
	, [BillingState]
	, [BillingPostalCode]
	, [BillingCountry]
	, [BillingStateCode]
	, [BillingCountryCode]
	, [BillingLatitude]
	, [BillingLongitude]
	, [BillingGeocodeAccuracy]
	, [ShippingStreet]
	, [ShippingCity]
	, [ShippingState]
	, [ShippingPostalCode]
	, [ShippingCountry]
	, [ShippingStateCode]
	, [ShippingCountryCode]
	, [ShippingLatitude]
	, [ShippingLongitude]
	, [ShippingGeocodeAccuracy]
	, [Phone]
	, [Fax]
	, [AccountNumber]
	, [Website]
	, [PhotoUrl]
	, [Sic]
	, [Industry]
	, [AnnualRevenue]
	, [NumberOfEmployees]
	, [Ownership]
	, [TickerSymbol]
	, [Description]
	, [Rating]
	, [Site]
	, [CurrencyIsoCode]
	, [OwnerId]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastActivityDate]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [PersonContactId]
	, [IsPersonAccount]
	, [PersonMailingStreet]
	, [PersonMailingCity]
	, [PersonMailingState]
	, [PersonMailingPostalCode]
	, [PersonMailingCountry]
	, [PersonMailingStateCode]
	, [PersonMailingCountryCode]
	, [PersonMailingLatitude]
	, [PersonMailingLongitude]
	, [PersonMailingGeocodeAccuracy]
	, [PersonMobilePhone]
	, [PersonHomePhone]
	, [PersonOtherPhone]
	, [PersonAssistantPhone]
	, [PersonEmail]
	, [PersonTitle]
	, [PersonDepartment]
	, [PersonDoNotCall]
	, [PersonLastCURequestDate]
	, [PersonLastCUUpdateDate]
	, [PersonEmailBouncedReason]
	, [PersonEmailBouncedDate]
	, [Jigsaw]
	, [JigsawCompanyId]
	, [AccountSource]
	, [SicDesc]
	, [OperatingHoursId]
	, [Active__c]
	, [Company__c]
	, [ConectCreationDate__c]
	, [ConectLastUpdate__c]
	, [External_Id__c]
	, [PersonMobilePhone_Number_Normalized__c]
	, [Status__c]
	, [Count_Close_Won_Opportunities__c]
	, [ClientIdentifier__c]
	, [Occupation__c]
	, [AreaManager__c]
	, [Area__c]
	, [AssistantManager__c]
	, [BackLinePhone__c]
	, [BestTressedOffered__c]
	, [CenterAlert__c]
	, [CenterOwner__c]
	, [CenterType__c]
	, [CompanyID__c]
	, [ConfirmationCallerIDEnglish__c]
	, [ConfirmationCallerIDFrench__c]
	, [ConfirmationCallerIDSpanish__c]
	, [CustomerServiceLine__c]
	, [Customer_Status__c]
	, [DNCDateMobilePhone__c]
	, [DNCDatePhone__c]
	, [DNCValidationMobilePhone__c]
	, [DNCValidationPhone__c]
	, [DisplayName__c]
	, [ImageConsultant__c]
	, [MDPOffered__c]
	, [MDPPerformed__c]
	, [ManagerName__c]
	, [MgrCellPhone__c]
	, [OfferPRP__c]
	, [OtherCallerIDEnglish__c]
	, [OtherCallerIDFrench__c]
	, [OtherCallerIDSpanish__c]
	, [OutboundDialingAllowed__c]
	, [ProfileCode__c]
	, [Region__c]
	, [Service_Territory__c]
	, [SurgeryOffered__c]
	, [TimeZone__c]
	, [Virtual__c]
	, [WebPhone__c]
	, [X1Apptperslot__c]
	, [ClientGUID__c]
	, [Goals_Expectations__c]
	, [How_many_times_a_week_do_you_think__c]
	, [How_much_time_a_week_do_you_spend__c]
	, [Other_Reason__c]
	, [What_are_your_main_concerns_today__c]
	, [What_else_would_be_helpful_for_your__c]
	, [What_methods_have_you_used_or_currently__c]
	, [fferpcore__ExemptionCertificate__c]
	, [fferpcore__IsBillingAddressValidated__c]
	, [fferpcore__IsShippingAddressValidated__c]
	, [fferpcore__MaterializedBillingAddressValidated__c]
	, [fferpcore__MaterializedShippingAddressValidated__c]
	, [fferpcore__OutputVatCode__c]
	, [fferpcore__SalesTaxStatus__c]
	, [fferpcore__TaxCode1__c]
	, [fferpcore__TaxCode2__c]
	, [fferpcore__TaxCode3__c]
	, [fferpcore__TaxCountryCode__c]
	, [fferpcore__ValidatedBillingCity__c]
	, [fferpcore__ValidatedBillingCountry__c]
	, [fferpcore__ValidatedBillingPostalCode__c]
	, [fferpcore__ValidatedBillingState__c]
	, [fferpcore__ValidatedBillingStreet__c]
	, [fferpcore__ValidatedShippingCity__c]
	, [fferpcore__ValidatedShippingCountry__c]
	, [fferpcore__ValidatedShippingPostalCode__c]
	, [fferpcore__ValidatedShippingState__c]
	, [fferpcore__ValidatedShippingStreet__c]
	, [fferpcore__VatRegistrationNumber__c]
	, [fferpcore__VatStatus__c]
	, [ffbf__AccountParticulars__c]
	, [ffbf__BankBIC__c]
	, [ffbf__PaymentCode__c]
	, [ffbf__PaymentCountryISO__c]
	, [ffbf__PaymentPriority__c]
	, [ffbf__PaymentRoutingMethod__c]
	, [SCMFFA__Company_Name__c]
	, [ffaci__CurrencyCulture__c]
	, [Service_Territory_Time_Zone__c]
	, [rh2__testCurrency__c]
	, [Initial_Campaign_Source__c]
	, [Landing_Page_Form_Submitted_Date__c]
	, [Age__pc]
	, [Birthdate__pc]
	, [DoNotContact__pc]
	, [DoNotEmail__pc]
	, [DoNotMail__pc]
	, [DoNotText__pc]
	, [Ethnicity__pc]
	, [Gender__pc]
	, [HairLossExperience__pc]
	, [HairLossFamily__pc]
	, [HairLossOrVolume__pc]
	, [HairLossProductOther__pc]
	, [HairLossProductUsed__pc]
	, [HairLossSpot__pc]
	, [HardCopyPreferred__pc]
	, [Language__pc]
	, [MaritalStatus__pc]
	, [Text_Reminder_Opt_In__pc]
	, [rh2__Currency_Test__pc]
	, [rh2__Describe__pc]
	, [rh2__Formula_Test__pc]
	, [rh2__Integer_Test__pc]
	, [Next_Milestone_Event__pc]
	, [Next_Milestone_Event_Date__pc]
	, [Bosley_Center_Number__pc]
	, [Bosley_Client_Id__pc]
	, [Bosley_Legacy_Source_Code__pc]
	, [Bosley_Salesforce_Id__pc]
	, [Bosley_Siebel_Id__pc]
	, [Contact_ID_18_dig__pc]
	, [Landing_Page_Form_Submitted_Date__pc]
	, [Personal_Photo__pc]
	)
	VALUES(
	[s].[Id]
	, [s].[IsDeleted]
	, [s].[MasterRecordId]
	, [s].[Name]
	, [s].[LastName]
	, [s].[FirstName]
	, [s].[Salutation]
	, [s].[MiddleName]
	, [s].[Suffix]
	, [s].[Type]
	, [s].[RecordTypeId]
	, [s].[ParentId]
	, [s].[BillingStreet]
	, [s].[BillingCity]
	, [s].[BillingState]
	, [s].[BillingPostalCode]
	, [s].[BillingCountry]
	, [s].[BillingStateCode]
	, [s].[BillingCountryCode]
	, [s].[BillingLatitude]
	, [s].[BillingLongitude]
	, [s].[BillingGeocodeAccuracy]
	, [s].[ShippingStreet]
	, [s].[ShippingCity]
	, [s].[ShippingState]
	, [s].[ShippingPostalCode]
	, [s].[ShippingCountry]
	, [s].[ShippingStateCode]
	, [s].[ShippingCountryCode]
	, [s].[ShippingLatitude]
	, [s].[ShippingLongitude]
	, [s].[ShippingGeocodeAccuracy]
	, [s].[Phone]
	, [s].[Fax]
	, [s].[AccountNumber]
	, [s].[Website]
	, [s].[PhotoUrl]
	, [s].[Sic]
	, [s].[Industry]
	, [s].[AnnualRevenue]
	, [s].[NumberOfEmployees]
	, [s].[Ownership]
	, [s].[TickerSymbol]
	, [s].[Description]
	, [s].[Rating]
	, [s].[Site]
	, [s].[CurrencyIsoCode]
	, [s].[OwnerId]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastActivityDate]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[PersonContactId]
	, [s].[IsPersonAccount]
	, [s].[PersonMailingStreet]
	, [s].[PersonMailingCity]
	, [s].[PersonMailingState]
	, [s].[PersonMailingPostalCode]
	, [s].[PersonMailingCountry]
	, [s].[PersonMailingStateCode]
	, [s].[PersonMailingCountryCode]
	, [s].[PersonMailingLatitude]
	, [s].[PersonMailingLongitude]
	, [s].[PersonMailingGeocodeAccuracy]
	, [s].[PersonMobilePhone]
	, [s].[PersonHomePhone]
	, [s].[PersonOtherPhone]
	, [s].[PersonAssistantPhone]
	, [s].[PersonEmail]
	, [s].[PersonTitle]
	, [s].[PersonDepartment]
	, [s].[PersonDoNotCall]
	, [s].[PersonLastCURequestDate]
	, [s].[PersonLastCUUpdateDate]
	, [s].[PersonEmailBouncedReason]
	, [s].[PersonEmailBouncedDate]
	, [s].[Jigsaw]
	, [s].[JigsawCompanyId]
	, [s].[AccountSource]
	, [s].[SicDesc]
	, [s].[OperatingHoursId]
	, [s].[Active__c]
	, [s].[Company__c]
	, [s].[ConectCreationDate__c]
	, [s].[ConectLastUpdate__c]
	, [s].[External_Id__c]
	, [s].[PersonMobilePhone_Number_Normalized__c]
	, [s].[Status__c]
	, [s].[Count_Close_Won_Opportunities__c]
	, [s].[ClientIdentifier__c]
	, [s].[Occupation__c]
	, [s].[AreaManager__c]
	, [s].[Area__c]
	, [s].[AssistantManager__c]
	, [s].[BackLinePhone__c]
	, [s].[BestTressedOffered__c]
	, [s].[CenterAlert__c]
	, [s].[CenterOwner__c]
	, [s].[CenterType__c]
	, [s].[CompanyID__c]
	, [s].[ConfirmationCallerIDEnglish__c]
	, [s].[ConfirmationCallerIDFrench__c]
	, [s].[ConfirmationCallerIDSpanish__c]
	, [s].[CustomerServiceLine__c]
	, [s].[Customer_Status__c]
	, [s].[DNCDateMobilePhone__c]
	, [s].[DNCDatePhone__c]
	, [s].[DNCValidationMobilePhone__c]
	, [s].[DNCValidationPhone__c]
	, [s].[DisplayName__c]
	, [s].[ImageConsultant__c]
	, [s].[MDPOffered__c]
	, [s].[MDPPerformed__c]
	, [s].[ManagerName__c]
	, [s].[MgrCellPhone__c]
	, [s].[OfferPRP__c]
	, [s].[OtherCallerIDEnglish__c]
	, [s].[OtherCallerIDFrench__c]
	, [s].[OtherCallerIDSpanish__c]
	, [s].[OutboundDialingAllowed__c]
	, [s].[ProfileCode__c]
	, [s].[Region__c]
	, [s].[Service_Territory__c]
	, [s].[SurgeryOffered__c]
	, [s].[TimeZone__c]
	, [s].[Virtual__c]
	, [s].[WebPhone__c]
	, [s].[X1Apptperslot__c]
	, [s].[ClientGUID__c]
	, [s].[Goals_Expectations__c]
	, [s].[How_many_times_a_week_do_you_think__c]
	, [s].[How_much_time_a_week_do_you_spend__c]
	, [s].[Other_Reason__c]
	, [s].[What_are_your_main_concerns_today__c]
	, [s].[What_else_would_be_helpful_for_your__c]
	, [s].[What_methods_have_you_used_or_currently__c]
	, [s].[fferpcore__ExemptionCertificate__c]
	, [s].[fferpcore__IsBillingAddressValidated__c]
	, [s].[fferpcore__IsShippingAddressValidated__c]
	, [s].[fferpcore__MaterializedBillingAddressValidated__c]
	, [s].[fferpcore__MaterializedShippingAddressValidated__c]
	, [s].[fferpcore__OutputVatCode__c]
	, [s].[fferpcore__SalesTaxStatus__c]
	, [s].[fferpcore__TaxCode1__c]
	, [s].[fferpcore__TaxCode2__c]
	, [s].[fferpcore__TaxCode3__c]
	, [s].[fferpcore__TaxCountryCode__c]
	, [s].[fferpcore__ValidatedBillingCity__c]
	, [s].[fferpcore__ValidatedBillingCountry__c]
	, [s].[fferpcore__ValidatedBillingPostalCode__c]
	, [s].[fferpcore__ValidatedBillingState__c]
	, [s].[fferpcore__ValidatedBillingStreet__c]
	, [s].[fferpcore__ValidatedShippingCity__c]
	, [s].[fferpcore__ValidatedShippingCountry__c]
	, [s].[fferpcore__ValidatedShippingPostalCode__c]
	, [s].[fferpcore__ValidatedShippingState__c]
	, [s].[fferpcore__ValidatedShippingStreet__c]
	, [s].[fferpcore__VatRegistrationNumber__c]
	, [s].[fferpcore__VatStatus__c]
	, [s].[ffbf__AccountParticulars__c]
	, [s].[ffbf__BankBIC__c]
	, [s].[ffbf__PaymentCode__c]
	, [s].[ffbf__PaymentCountryISO__c]
	, [s].[ffbf__PaymentPriority__c]
	, [s].[ffbf__PaymentRoutingMethod__c]
	, [s].[SCMFFA__Company_Name__c]
	, [s].[ffaci__CurrencyCulture__c]
	, [s].[Service_Territory_Time_Zone__c]
	, [s].[rh2__testCurrency__c]
	, [s].[Initial_Campaign_Source__c]
	, [s].[Landing_Page_Form_Submitted_Date__c]
	, [s].[Age__pc]
	, [s].[Birthdate__pc]
	, [s].[DoNotContact__pc]
	, [s].[DoNotEmail__pc]
	, [s].[DoNotMail__pc]
	, [s].[DoNotText__pc]
	, [s].[Ethnicity__pc]
	, [s].[Gender__pc]
	, [s].[HairLossExperience__pc]
	, [s].[HairLossFamily__pc]
	, [s].[HairLossOrVolume__pc]
	, [s].[HairLossProductOther__pc]
	, [s].[HairLossProductUsed__pc]
	, [s].[HairLossSpot__pc]
	, [s].[HardCopyPreferred__pc]
	, [s].[Language__pc]
	, [s].[MaritalStatus__pc]
	, [s].[Text_Reminder_Opt_In__pc]
	, [s].[rh2__Currency_Test__pc]
	, [s].[rh2__Describe__pc]
	, [s].[rh2__Formula_Test__pc]
	, [s].[rh2__Integer_Test__pc]
	, [s].[Next_Milestone_Event__pc]
	, [s].[Next_Milestone_Event_Date__pc]
	, [s].[Bosley_Center_Number__pc]
	, [s].[Bosley_Client_Id__pc]
	, [s].[Bosley_Legacy_Source_Code__pc]
	, [s].[Bosley_Salesforce_Id__pc]
	, [s].[Bosley_Siebel_Id__pc]
	, [s].[Contact_ID_18_dig__pc]
	, [s].[Landing_Page_Form_Submitted_Date__pc]
	, [s].[Personal_Photo__pc]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Account] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
