/* CreateDate: 03/17/2022 15:12:15.310 , ModifyDate: 03/17/2022 15:12:15.310 */
GO
CREATE PROCEDURE [SF].[sp_Campaign_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Campaign])
RETURN ;

BEGIN TRY
;MERGE [SF].[Campaign] AS [t]
USING [SFStaging].[Campaign] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[IsDeleted] = [t].[IsDeleted]
	, [t].[Name] = [t].[Name]
	, [t].[ParentId] = [t].[ParentId]
	, [t].[Type] = [t].[Type]
	, [t].[RecordTypeId] = [t].[RecordTypeId]
	, [t].[Status] = [t].[Status]
	, [t].[StartDate] = [t].[StartDate]
	, [t].[EndDate] = [t].[EndDate]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[ExpectedRevenue] = [t].[ExpectedRevenue]
	, [t].[BudgetedCost] = [t].[BudgetedCost]
	, [t].[ActualCost] = [t].[ActualCost]
	, [t].[ExpectedResponse] = [t].[ExpectedResponse]
	, [t].[NumberSent] = [t].[NumberSent]
	, [t].[IsActive] = [t].[IsActive]
	, [t].[Description] = [t].[Description]
	, [t].[NumberOfLeads] = [t].[NumberOfLeads]
	, [t].[NumberOfConvertedLeads] = [t].[NumberOfConvertedLeads]
	, [t].[NumberOfContacts] = [t].[NumberOfContacts]
	, [t].[NumberOfResponses] = [t].[NumberOfResponses]
	, [t].[NumberOfOpportunities] = [t].[NumberOfOpportunities]
	, [t].[NumberOfWonOpportunities] = [t].[NumberOfWonOpportunities]
	, [t].[AmountAllOpportunities] = [t].[AmountAllOpportunities]
	, [t].[AmountWonOpportunities] = [t].[AmountWonOpportunities]
	, [t].[HierarchyNumberOfLeads] = [t].[HierarchyNumberOfLeads]
	, [t].[HierarchyNumberOfConvertedLeads] = [t].[HierarchyNumberOfConvertedLeads]
	, [t].[HierarchyNumberOfContacts] = [t].[HierarchyNumberOfContacts]
	, [t].[HierarchyNumberOfResponses] = [t].[HierarchyNumberOfResponses]
	, [t].[HierarchyNumberOfOpportunities] = [t].[HierarchyNumberOfOpportunities]
	, [t].[HierarchyNumberOfWonOpportunities] = [t].[HierarchyNumberOfWonOpportunities]
	, [t].[HierarchyAmountAllOpportunities] = [t].[HierarchyAmountAllOpportunities]
	, [t].[HierarchyAmountWonOpportunities] = [t].[HierarchyAmountWonOpportunities]
	, [t].[HierarchyNumberSent] = [t].[HierarchyNumberSent]
	, [t].[HierarchyExpectedRevenue] = [t].[HierarchyExpectedRevenue]
	, [t].[HierarchyBudgetedCost] = [t].[HierarchyBudgetedCost]
	, [t].[HierarchyActualCost] = [t].[HierarchyActualCost]
	, [t].[OwnerId] = [t].[OwnerId]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastActivityDate] = [t].[LastActivityDate]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[CampaignMemberRecordTypeId] = [t].[CampaignMemberRecordTypeId]
	, [t].[Channel__c] = [t].[Channel__c]
	, [t].[Company__c] = [t].[Company__c]
	, [t].[External_Id__c] = [t].[External_Id__c]
	, [t].[Language__c] = [t].[Language__c]
	, [t].[Priority__c] = [t].[Priority__c]
	, [t].[Promo_Code__c] = [t].[Promo_Code__c]
	, [t].[SourceCode_L__c] = [t].[SourceCode_L__c]
	, [t].[TollFreeNumber__c] = [t].[TollFreeNumber__c]
	, [t].[Audience__c] = [t].[Audience__c]
	, [t].[Format__c] = [t].[Format__c]
	, [t].[Location__c] = [t].[Location__c]
	, [t].[Media__c] = [t].[Media__c]
	, [t].[DPNCode__c] = [t].[DPNCode__c]
	, [t].[DWCCode__c] = [t].[DWCCode__c]
	, [t].[DWFCode__c] = [t].[DWFCode__c]
	, [t].[MPNCode__c] = [t].[MPNCode__c]
	, [t].[MWCCode__c] = [t].[MWCCode__c]
	, [t].[MWFCode__c] = [t].[MWFCode__c]
	, [t].[Gleam_Id__c] = [t].[Gleam_Id__c]
	, [t].[DialerMiscCode__c] = [t].[DialerMiscCode__c]
	, [t].[Origin__c] = [t].[Origin__c]
	, [t].[Dialer_Misc_Code__c] = [t].[Dialer_Misc_Code__c]
	, [t].[Toll_Free_Desktop__c] = [t].[Toll_Free_Desktop__c]
	, [t].[Toll_Free_Mobile__c] = [t].[Toll_Free_Mobile__c]
	, [t].[DB_Campaign_Tactic__c] = [t].[DB_Campaign_Tactic__c]
	, [t].[CampaignSource__c] = [t].[CampaignSource__c]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [IsDeleted]
	, [Name]
	, [ParentId]
	, [Type]
	, [RecordTypeId]
	, [Status]
	, [StartDate]
	, [EndDate]
	, [CurrencyIsoCode]
	, [ExpectedRevenue]
	, [BudgetedCost]
	, [ActualCost]
	, [ExpectedResponse]
	, [NumberSent]
	, [IsActive]
	, [Description]
	, [NumberOfLeads]
	, [NumberOfConvertedLeads]
	, [NumberOfContacts]
	, [NumberOfResponses]
	, [NumberOfOpportunities]
	, [NumberOfWonOpportunities]
	, [AmountAllOpportunities]
	, [AmountWonOpportunities]
	, [HierarchyNumberOfLeads]
	, [HierarchyNumberOfConvertedLeads]
	, [HierarchyNumberOfContacts]
	, [HierarchyNumberOfResponses]
	, [HierarchyNumberOfOpportunities]
	, [HierarchyNumberOfWonOpportunities]
	, [HierarchyAmountAllOpportunities]
	, [HierarchyAmountWonOpportunities]
	, [HierarchyNumberSent]
	, [HierarchyExpectedRevenue]
	, [HierarchyBudgetedCost]
	, [HierarchyActualCost]
	, [OwnerId]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastActivityDate]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [CampaignMemberRecordTypeId]
	, [Channel__c]
	, [Company__c]
	, [External_Id__c]
	, [Language__c]
	, [Priority__c]
	, [Promo_Code__c]
	, [SourceCode_L__c]
	, [TollFreeNumber__c]
	, [Audience__c]
	, [Format__c]
	, [Location__c]
	, [Media__c]
	, [DPNCode__c]
	, [DWCCode__c]
	, [DWFCode__c]
	, [MPNCode__c]
	, [MWCCode__c]
	, [MWFCode__c]
	, [Gleam_Id__c]
	, [DialerMiscCode__c]
	, [Origin__c]
	, [Dialer_Misc_Code__c]
	, [Toll_Free_Desktop__c]
	, [Toll_Free_Mobile__c]
	, [DB_Campaign_Tactic__c]
	, [CampaignSource__c]
	)
	VALUES(
	[s].[Id]
	, [s].[IsDeleted]
	, [s].[Name]
	, [s].[ParentId]
	, [s].[Type]
	, [s].[RecordTypeId]
	, [s].[Status]
	, [s].[StartDate]
	, [s].[EndDate]
	, [s].[CurrencyIsoCode]
	, [s].[ExpectedRevenue]
	, [s].[BudgetedCost]
	, [s].[ActualCost]
	, [s].[ExpectedResponse]
	, [s].[NumberSent]
	, [s].[IsActive]
	, [s].[Description]
	, [s].[NumberOfLeads]
	, [s].[NumberOfConvertedLeads]
	, [s].[NumberOfContacts]
	, [s].[NumberOfResponses]
	, [s].[NumberOfOpportunities]
	, [s].[NumberOfWonOpportunities]
	, [s].[AmountAllOpportunities]
	, [s].[AmountWonOpportunities]
	, [s].[HierarchyNumberOfLeads]
	, [s].[HierarchyNumberOfConvertedLeads]
	, [s].[HierarchyNumberOfContacts]
	, [s].[HierarchyNumberOfResponses]
	, [s].[HierarchyNumberOfOpportunities]
	, [s].[HierarchyNumberOfWonOpportunities]
	, [s].[HierarchyAmountAllOpportunities]
	, [s].[HierarchyAmountWonOpportunities]
	, [s].[HierarchyNumberSent]
	, [s].[HierarchyExpectedRevenue]
	, [s].[HierarchyBudgetedCost]
	, [s].[HierarchyActualCost]
	, [s].[OwnerId]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastActivityDate]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[CampaignMemberRecordTypeId]
	, [s].[Channel__c]
	, [s].[Company__c]
	, [s].[External_Id__c]
	, [s].[Language__c]
	, [s].[Priority__c]
	, [s].[Promo_Code__c]
	, [s].[SourceCode_L__c]
	, [s].[TollFreeNumber__c]
	, [s].[Audience__c]
	, [s].[Format__c]
	, [s].[Location__c]
	, [s].[Media__c]
	, [s].[DPNCode__c]
	, [s].[DWCCode__c]
	, [s].[DWFCode__c]
	, [s].[MPNCode__c]
	, [s].[MWCCode__c]
	, [s].[MWFCode__c]
	, [s].[Gleam_Id__c]
	, [s].[DialerMiscCode__c]
	, [s].[Origin__c]
	, [s].[Dialer_Misc_Code__c]
	, [s].[Toll_Free_Desktop__c]
	, [s].[Toll_Free_Mobile__c]
	, [s].[DB_Campaign_Tactic__c]
	, [s].[CampaignSource__c]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Campaign] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
