/* CreateDate: 03/17/2022 15:12:16.187 , ModifyDate: 03/17/2022 15:12:16.187 */
GO
CREATE PROCEDURE [SF].[sp_Quote_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Quote])
RETURN ;

BEGIN TRY
;MERGE [SF].[Quote] AS [t]
USING [SFStaging].[Quote] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[OwnerId] = [t].[OwnerId]
	, [t].[IsDeleted] = [t].[IsDeleted]
	, [t].[Name] = [t].[Name]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[OpportunityId] = [t].[OpportunityId]
	, [t].[Pricebook2Id] = [t].[Pricebook2Id]
	, [t].[ContactId] = [t].[ContactId]
	, [t].[QuoteNumber] = [t].[QuoteNumber]
	, [t].[IsSyncing] = [t].[IsSyncing]
	, [t].[ShippingHandling] = [t].[ShippingHandling]
	, [t].[Tax] = [t].[Tax]
	, [t].[Status] = [t].[Status]
	, [t].[ExpirationDate] = [t].[ExpirationDate]
	, [t].[Description] = [t].[Description]
	, [t].[Subtotal] = [t].[Subtotal]
	, [t].[TotalPrice] = [t].[TotalPrice]
	, [t].[LineItemCount] = [t].[LineItemCount]
	, [t].[BillingStreet] = [t].[BillingStreet]
	, [t].[BillingCity] = [t].[BillingCity]
	, [t].[BillingState] = [t].[BillingState]
	, [t].[BillingPostalCode] = [t].[BillingPostalCode]
	, [t].[BillingCountry] = [t].[BillingCountry]
	, [t].[BillingStateCode] = [t].[BillingStateCode]
	, [t].[BillingCountryCode] = [t].[BillingCountryCode]
	, [t].[BillingLatitude] = [t].[BillingLatitude]
	, [t].[BillingLongitude] = [t].[BillingLongitude]
	, [t].[BillingGeocodeAccuracy] = [t].[BillingGeocodeAccuracy]
	, [t].[BillingAddress] = [t].[BillingAddress]
	, [t].[ShippingStreet] = [t].[ShippingStreet]
	, [t].[ShippingCity] = [t].[ShippingCity]
	, [t].[ShippingState] = [t].[ShippingState]
	, [t].[ShippingPostalCode] = [t].[ShippingPostalCode]
	, [t].[ShippingCountry] = [t].[ShippingCountry]
	, [t].[ShippingStateCode] = [t].[ShippingStateCode]
	, [t].[ShippingCountryCode] = [t].[ShippingCountryCode]
	, [t].[ShippingLatitude] = [t].[ShippingLatitude]
	, [t].[ShippingLongitude] = [t].[ShippingLongitude]
	, [t].[ShippingGeocodeAccuracy] = [t].[ShippingGeocodeAccuracy]
	, [t].[ShippingAddress] = [t].[ShippingAddress]
	, [t].[QuoteToStreet] = [t].[QuoteToStreet]
	, [t].[QuoteToCity] = [t].[QuoteToCity]
	, [t].[QuoteToState] = [t].[QuoteToState]
	, [t].[QuoteToPostalCode] = [t].[QuoteToPostalCode]
	, [t].[QuoteToCountry] = [t].[QuoteToCountry]
	, [t].[QuoteToStateCode] = [t].[QuoteToStateCode]
	, [t].[QuoteToCountryCode] = [t].[QuoteToCountryCode]
	, [t].[QuoteToLatitude] = [t].[QuoteToLatitude]
	, [t].[QuoteToLongitude] = [t].[QuoteToLongitude]
	, [t].[QuoteToGeocodeAccuracy] = [t].[QuoteToGeocodeAccuracy]
	, [t].[QuoteToAddress] = [t].[QuoteToAddress]
	, [t].[AdditionalStreet] = [t].[AdditionalStreet]
	, [t].[AdditionalCity] = [t].[AdditionalCity]
	, [t].[AdditionalState] = [t].[AdditionalState]
	, [t].[AdditionalPostalCode] = [t].[AdditionalPostalCode]
	, [t].[AdditionalCountry] = [t].[AdditionalCountry]
	, [t].[AdditionalStateCode] = [t].[AdditionalStateCode]
	, [t].[AdditionalCountryCode] = [t].[AdditionalCountryCode]
	, [t].[AdditionalLatitude] = [t].[AdditionalLatitude]
	, [t].[AdditionalLongitude] = [t].[AdditionalLongitude]
	, [t].[AdditionalGeocodeAccuracy] = [t].[AdditionalGeocodeAccuracy]
	, [t].[AdditionalAddress] = [t].[AdditionalAddress]
	, [t].[BillingName] = [t].[BillingName]
	, [t].[ShippingName] = [t].[ShippingName]
	, [t].[QuoteToName] = [t].[QuoteToName]
	, [t].[AdditionalName] = [t].[AdditionalName]
	, [t].[Email] = [t].[Email]
	, [t].[Phone] = [t].[Phone]
	, [t].[Fax] = [t].[Fax]
	, [t].[ContractId] = [t].[ContractId]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[Discount] = [t].[Discount]
	, [t].[GrandTotal] = [t].[GrandTotal]
	, [t].[CanCreateQuoteLineItems] = [t].[CanCreateQuoteLineItems]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [OwnerId]
	, [IsDeleted]
	, [Name]
	, [CurrencyIsoCode]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [OpportunityId]
	, [Pricebook2Id]
	, [ContactId]
	, [QuoteNumber]
	, [IsSyncing]
	, [ShippingHandling]
	, [Tax]
	, [Status]
	, [ExpirationDate]
	, [Description]
	, [Subtotal]
	, [TotalPrice]
	, [LineItemCount]
	, [BillingStreet]
	, [BillingCity]
	, [BillingState]
	, [BillingPostalCode]
	, [BillingCountry]
	, [BillingStateCode]
	, [BillingCountryCode]
	, [BillingLatitude]
	, [BillingLongitude]
	, [BillingGeocodeAccuracy]
	, [BillingAddress]
	, [ShippingStreet]
	, [ShippingCity]
	, [ShippingState]
	, [ShippingPostalCode]
	, [ShippingCountry]
	, [ShippingStateCode]
	, [ShippingCountryCode]
	, [ShippingLatitude]
	, [ShippingLongitude]
	, [ShippingGeocodeAccuracy]
	, [ShippingAddress]
	, [QuoteToStreet]
	, [QuoteToCity]
	, [QuoteToState]
	, [QuoteToPostalCode]
	, [QuoteToCountry]
	, [QuoteToStateCode]
	, [QuoteToCountryCode]
	, [QuoteToLatitude]
	, [QuoteToLongitude]
	, [QuoteToGeocodeAccuracy]
	, [QuoteToAddress]
	, [AdditionalStreet]
	, [AdditionalCity]
	, [AdditionalState]
	, [AdditionalPostalCode]
	, [AdditionalCountry]
	, [AdditionalStateCode]
	, [AdditionalCountryCode]
	, [AdditionalLatitude]
	, [AdditionalLongitude]
	, [AdditionalGeocodeAccuracy]
	, [AdditionalAddress]
	, [BillingName]
	, [ShippingName]
	, [QuoteToName]
	, [AdditionalName]
	, [Email]
	, [Phone]
	, [Fax]
	, [ContractId]
	, [AccountId]
	, [Discount]
	, [GrandTotal]
	, [CanCreateQuoteLineItems]
	)
	VALUES(
	[s].[Id]
	, [s].[OwnerId]
	, [s].[IsDeleted]
	, [s].[Name]
	, [s].[CurrencyIsoCode]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[OpportunityId]
	, [s].[Pricebook2Id]
	, [s].[ContactId]
	, [s].[QuoteNumber]
	, [s].[IsSyncing]
	, [s].[ShippingHandling]
	, [s].[Tax]
	, [s].[Status]
	, [s].[ExpirationDate]
	, [s].[Description]
	, [s].[Subtotal]
	, [s].[TotalPrice]
	, [s].[LineItemCount]
	, [s].[BillingStreet]
	, [s].[BillingCity]
	, [s].[BillingState]
	, [s].[BillingPostalCode]
	, [s].[BillingCountry]
	, [s].[BillingStateCode]
	, [s].[BillingCountryCode]
	, [s].[BillingLatitude]
	, [s].[BillingLongitude]
	, [s].[BillingGeocodeAccuracy]
	, [s].[BillingAddress]
	, [s].[ShippingStreet]
	, [s].[ShippingCity]
	, [s].[ShippingState]
	, [s].[ShippingPostalCode]
	, [s].[ShippingCountry]
	, [s].[ShippingStateCode]
	, [s].[ShippingCountryCode]
	, [s].[ShippingLatitude]
	, [s].[ShippingLongitude]
	, [s].[ShippingGeocodeAccuracy]
	, [s].[ShippingAddress]
	, [s].[QuoteToStreet]
	, [s].[QuoteToCity]
	, [s].[QuoteToState]
	, [s].[QuoteToPostalCode]
	, [s].[QuoteToCountry]
	, [s].[QuoteToStateCode]
	, [s].[QuoteToCountryCode]
	, [s].[QuoteToLatitude]
	, [s].[QuoteToLongitude]
	, [s].[QuoteToGeocodeAccuracy]
	, [s].[QuoteToAddress]
	, [s].[AdditionalStreet]
	, [s].[AdditionalCity]
	, [s].[AdditionalState]
	, [s].[AdditionalPostalCode]
	, [s].[AdditionalCountry]
	, [s].[AdditionalStateCode]
	, [s].[AdditionalCountryCode]
	, [s].[AdditionalLatitude]
	, [s].[AdditionalLongitude]
	, [s].[AdditionalGeocodeAccuracy]
	, [s].[AdditionalAddress]
	, [s].[BillingName]
	, [s].[ShippingName]
	, [s].[QuoteToName]
	, [s].[AdditionalName]
	, [s].[Email]
	, [s].[Phone]
	, [s].[Fax]
	, [s].[ContractId]
	, [s].[AccountId]
	, [s].[Discount]
	, [s].[GrandTotal]
	, [s].[CanCreateQuoteLineItems]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Quote] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
