/* CreateDate: 03/17/2022 15:12:15.567 , ModifyDate: 03/17/2022 15:12:15.567 */
GO
CREATE PROCEDURE [SF].[sp_Contract_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Contract])
RETURN ;

BEGIN TRY
;MERGE [SF].[Contract] AS [t]
USING [SFStaging].[Contract] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[AccountId] = [t].[AccountId]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[Pricebook2Id] = [t].[Pricebook2Id]
	, [t].[OwnerExpirationNotice] = [t].[OwnerExpirationNotice]
	, [t].[StartDate] = [t].[StartDate]
	, [t].[EndDate] = [t].[EndDate]
	, [t].[BillingStreet] = [t].[BillingStreet]
	, [t].[BillingCity] = [t].[BillingCity]
	, [t].[BillingState] = [t].[BillingState]
	, [t].[BillingPostalCode] = [t].[BillingPostalCode]
	, [t].[BillingCountry] = [t].[BillingCountry]
	, [t].[BillingStateCode] = [t].[BillingStateCode]
	, [t].[BillingCountryCode] = [t].[BillingCountryCode]
	, [t].[BillingLatitude] = [t].[BillingLatitude]
	, [t].[BillingLongitude] = [t].[BillingLongitude]
	, [t].[BillingGeocodeAccuracy] = [t].[BillingGeocodeAccuracy]
	, [t].[BillingAddress] = [t].[BillingAddress]
	, [t].[ShippingStreet] = [t].[ShippingStreet]
	, [t].[ShippingCity] = [t].[ShippingCity]
	, [t].[ShippingState] = [t].[ShippingState]
	, [t].[ShippingPostalCode] = [t].[ShippingPostalCode]
	, [t].[ShippingCountry] = [t].[ShippingCountry]
	, [t].[ShippingStateCode] = [t].[ShippingStateCode]
	, [t].[ShippingCountryCode] = [t].[ShippingCountryCode]
	, [t].[ShippingLatitude] = [t].[ShippingLatitude]
	, [t].[ShippingLongitude] = [t].[ShippingLongitude]
	, [t].[ShippingGeocodeAccuracy] = [t].[ShippingGeocodeAccuracy]
	, [t].[ShippingAddress] = [t].[ShippingAddress]
	, [t].[ContractTerm] = [t].[ContractTerm]
	, [t].[OwnerId] = [t].[OwnerId]
	, [t].[Status] = [t].[Status]
	, [t].[CompanySignedId] = [t].[CompanySignedId]
	, [t].[CompanySignedDate] = [t].[CompanySignedDate]
	, [t].[CustomerSignedId] = [t].[CustomerSignedId]
	, [t].[CustomerSignedTitle] = [t].[CustomerSignedTitle]
	, [t].[CustomerSignedDate] = [t].[CustomerSignedDate]
	, [t].[SpecialTerms] = [t].[SpecialTerms]
	, [t].[ActivatedById] = [t].[ActivatedById]
	, [t].[ActivatedDate] = [t].[ActivatedDate]
	, [t].[StatusCode] = [t].[StatusCode]
	, [t].[Description] = [t].[Description]
	, [t].[IsDeleted] = [t].[IsDeleted]
	, [t].[ContractNumber] = [t].[ContractNumber]
	, [t].[LastApprovedDate] = [t].[LastApprovedDate]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastActivityDate] = [t].[LastActivityDate]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [AccountId]
	, [CurrencyIsoCode]
	, [Pricebook2Id]
	, [OwnerExpirationNotice]
	, [StartDate]
	, [EndDate]
	, [BillingStreet]
	, [BillingCity]
	, [BillingState]
	, [BillingPostalCode]
	, [BillingCountry]
	, [BillingStateCode]
	, [BillingCountryCode]
	, [BillingLatitude]
	, [BillingLongitude]
	, [BillingGeocodeAccuracy]
	, [BillingAddress]
	, [ShippingStreet]
	, [ShippingCity]
	, [ShippingState]
	, [ShippingPostalCode]
	, [ShippingCountry]
	, [ShippingStateCode]
	, [ShippingCountryCode]
	, [ShippingLatitude]
	, [ShippingLongitude]
	, [ShippingGeocodeAccuracy]
	, [ShippingAddress]
	, [ContractTerm]
	, [OwnerId]
	, [Status]
	, [CompanySignedId]
	, [CompanySignedDate]
	, [CustomerSignedId]
	, [CustomerSignedTitle]
	, [CustomerSignedDate]
	, [SpecialTerms]
	, [ActivatedById]
	, [ActivatedDate]
	, [StatusCode]
	, [Description]
	, [IsDeleted]
	, [ContractNumber]
	, [LastApprovedDate]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastActivityDate]
	, [LastViewedDate]
	, [LastReferencedDate]
	)
	VALUES(
	[s].[Id]
	, [s].[AccountId]
	, [s].[CurrencyIsoCode]
	, [s].[Pricebook2Id]
	, [s].[OwnerExpirationNotice]
	, [s].[StartDate]
	, [s].[EndDate]
	, [s].[BillingStreet]
	, [s].[BillingCity]
	, [s].[BillingState]
	, [s].[BillingPostalCode]
	, [s].[BillingCountry]
	, [s].[BillingStateCode]
	, [s].[BillingCountryCode]
	, [s].[BillingLatitude]
	, [s].[BillingLongitude]
	, [s].[BillingGeocodeAccuracy]
	, [s].[BillingAddress]
	, [s].[ShippingStreet]
	, [s].[ShippingCity]
	, [s].[ShippingState]
	, [s].[ShippingPostalCode]
	, [s].[ShippingCountry]
	, [s].[ShippingStateCode]
	, [s].[ShippingCountryCode]
	, [s].[ShippingLatitude]
	, [s].[ShippingLongitude]
	, [s].[ShippingGeocodeAccuracy]
	, [s].[ShippingAddress]
	, [s].[ContractTerm]
	, [s].[OwnerId]
	, [s].[Status]
	, [s].[CompanySignedId]
	, [s].[CompanySignedDate]
	, [s].[CustomerSignedId]
	, [s].[CustomerSignedTitle]
	, [s].[CustomerSignedDate]
	, [s].[SpecialTerms]
	, [s].[ActivatedById]
	, [s].[ActivatedDate]
	, [s].[StatusCode]
	, [s].[Description]
	, [s].[IsDeleted]
	, [s].[ContractNumber]
	, [s].[LastApprovedDate]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastActivityDate]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Contract] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
