/* CreateDate: 03/15/2022 10:28:20.383 , ModifyDate: 03/15/2022 11:27:32.820 */
GO
CREATE TABLE [dbo].[SFDC_HCM_LeadAddress](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Lead__c] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OncContactAddressID__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OncContactID__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street3__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street4__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Zip__c] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DoNotMail__c] [bit] NULL,
	[Primary__c] [bit] NULL,
	[Status__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime2](7) NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[BatchID] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Converted__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Lead__c] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_OncContactAddressID__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_OncContactID__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Street__c] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Street2__c] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Street3__c] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Street4__c] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_City__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_State__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Zip__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Country__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_DoNotMail__c] [bit] NULL,
	[Dest_Primary__c] [bit] NULL,
	[Dest_Status__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CreatedDate] [datetime] NULL,
	[Dest_LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_LastModifiedDate] [datetime] NULL,
	[Dest_BatchID] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Converted__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsProcessedFlag] [bit] NULL,
	[IsExcludedFlag] [bit] NULL,
	[cst_sfdc_lead_id] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
