/* CreateDate: 10/30/2017 09:10:59.090 , ModifyDate: 10/30/2017 09:10:59.090 */
GO
CREATE TABLE [dbo].[HCM_SFDC_ErrorLogStaging_LeadPhone](
	[placeholder] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT_ID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CST_DO_NOT_CALL] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTACT_PHONE_ID] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[placeholder3] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE_TYPE_CODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder4] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COUNTRY_CODE_PREFIX] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder5] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AREA_CODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder6] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PHONE_NUMBER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder7] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTENSION] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder8] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATUS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder9] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SORT_ORDER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder10] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATION_DATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder11] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDATED_DATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder12] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIMARY_FLAG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder13] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CST_VALID_FLAG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder14] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CST_LAST_DNC_DATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder15] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CST_FULL_PHONE_NUMBER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder16] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DNC_FLAG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder17] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBR_DNC_FLAG] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder18] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBR_DNC_DATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder19] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERROR] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[placeholder20] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
