/* CreateDate: 03/15/2022 10:26:36.847 , ModifyDate: 03/15/2022 11:29:51.680 */
GO
CREATE TABLE [dbo].[SFDC_HCM_LeadPhone](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Lead__c] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactPhoneID__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OncContactID__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhoneAbr__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DoNotCall__c] [bit] NULL,
	[DoNotText__c] [bit] NULL,
	[DNCFlag__c] [bit] NULL,
	[EBRDNC__c] [bit] NULL,
	[EBRDNCDate__c] [date] NULL,
	[Wireless__c] [bit] NULL,
	[Primary__c] [bit] NULL,
	[SortOrder__c] [real] NULL,
	[Status__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ValidFlag__c] [bit] NULL,
	[Type__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime2](7) NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[BatchID] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Converted__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Lead__c] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_ContactPhoneID__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_OncContactID__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Name] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_PhoneAbr__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_DoNotCall__c] [bit] NULL,
	[Dest_DoNotText__c] [bit] NULL,
	[Dest_DNCFlag__c] [bit] NULL,
	[Dest_EBRDNC__c] [bit] NULL,
	[Dest_EBRDNCDate__c] [date] NULL,
	[Dest_Wireless__c] [bit] NULL,
	[Dest_Primary__c] [bit] NULL,
	[Dest_SortOrder__c] [float] NULL,
	[Dest_Status__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_ValidFlag__c] [bit] NULL,
	[Dest_Type__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CreatedDate] [datetime] NULL,
	[Dest_LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_LastModifiedDate] [datetime] NULL,
	[Dest_BatchID] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Converted__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsProcessedFlag] [bit] NULL,
	[IsExcludedFlag] [bit] NULL,
	[cst_sfdc_lead_id] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
