/* CreateDate: 03/15/2022 10:31:40.747 , ModifyDate: 03/15/2022 10:31:40.747 */
GO
CREATE TABLE [dbo].[SFDC_HCM_Lead](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactID__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterNumber__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CenterID__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Gender__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Language__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Source_Code_Legacy__c] [nvarchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Promo_Code_Legacy__c] [nvarchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DoNotContact__c] [bit] NULL,
	[DoNotCall] [bit] NULL,
	[DoNotEmail__c] [bit] NULL,
	[DoNotMail__c] [bit] NULL,
	[DoNotText__c] [bit] NULL,
	[ContactStatus__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SiebelID__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsConverted] [bit] NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime2](7) NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[GCLID__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimeZone__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BatchID] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_ContactID__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CenterNumber__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CenterID__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_FirstName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_LastName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Gender__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Language__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Source_Code_Legacy__c] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_Promo_Code_Legacy__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_DoNotContact__c] [bit] NULL,
	[Dest_DoNotCall] [bit] NULL,
	[Dest_DoNotEmail__c] [bit] NULL,
	[Dest_DoNotMail__c] [bit] NULL,
	[Dest_DoNotText__c] [bit] NULL,
	[Dest_ContactStatus__c] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_SiebelID__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_IsConverted] [bit] NULL,
	[Dest_CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_CreatedDate] [datetime] NULL,
	[Dest_LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_LastModifiedDate] [datetime] NULL,
	[Dest_BatchID] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_GCLID__c] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dest_TimeZone__c] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
