/* CreateDate: 11/10/2017 09:13:56.607 , ModifyDate: 11/10/2017 09:13:56.913 */
GO
CREATE TABLE [dbo].[SFDC_HCM_Batch](
	[BatchID] [int] IDENTITY(1,1) NOT NULL,
	[Status] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LSET] [datetime] NULL,
	[CET] [datetime] NULL,
 CONSTRAINT [PK_SFDC_HCM_Batch] PRIMARY KEY CLUSTERED
(
	[BatchID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
