/* CreateDate: 05/10/2018 17:53:20.900 , ModifyDate: 05/10/2018 17:53:20.900 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatabaseInfo](
	[BackupStatus] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ComputerName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InstanceName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SqlInstance] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastRead] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastWrite] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SizeMB] [float] NULL,
	[Compatibility] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastFullBackup] [datetime2](7) NULL,
	[LastDiffBackup] [datetime2](7) NULL,
	[LastLogBackup] [datetime2](7) NULL,
	[Parent] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ActiveConnections] [int] NULL,
	[AnsiNullDefault] [bit] NULL,
	[AnsiNullsEnabled] [bit] NULL,
	[AnsiPaddingEnabled] [bit] NULL,
	[AnsiWarningsEnabled] [bit] NULL,
	[ArithmeticAbortEnabled] [bit] NULL,
	[AutoClose] [bit] NULL,
	[AutoCreateIncrementalStatisticsEnabled] [bit] NULL,
	[AutoCreateStatisticsEnabled] [bit] NULL,
	[AutoShrink] [bit] NULL,
	[AutoUpdateStatisticsAsync] [bit] NULL,
	[AutoUpdateStatisticsEnabled] [bit] NULL,
	[AvailabilityDatabaseSynchronizationState] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AvailabilityGroupName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrokerEnabled] [bit] NULL,
	[CaseSensitive] [bit] NULL,
	[ChangeTrackingAutoCleanUp] [bit] NULL,
	[ChangeTrackingEnabled] [bit] NULL,
	[ChangeTrackingRetentionPeriod] [int] NULL,
	[ChangeTrackingRetentionPeriodUnits] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CloseCursorsOnCommitEnabled] [bit] NULL,
	[Collation] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompatibilityLevel] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConcatenateNullYieldsNull] [bit] NULL,
	[ContainmentType] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreateDate] [datetime2](7) NULL,
	[DatabaseGuid] [uniqueidentifier] NULL,
	[DatabaseSnapshotBaseName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DataSpaceUsage] [float] NULL,
	[DateCorrelationOptimization] [bit] NULL,
	[DboLogin] [bit] NULL,
	[DefaultFileGroup] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultFileStreamFileGroup] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultFullTextCatalog] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultSchema] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DelayedDurability] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EncryptionEnabled] [bit] NULL,
	[FilestreamDirectoryName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FilestreamNonTransactedAccess] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HasFileInCloud] [bit] NULL,
	[HasMemoryOptimizedObjects] [bit] NULL,
	[HonorBrokerPriority] [bit] NULL,
	[ID] [int] NULL,
	[IndexSpaceUsage] [float] NULL,
	[IsAccessible] [bit] NULL,
	[IsDatabaseSnapshot] [bit] NULL,
	[IsDatabaseSnapshotBase] [bit] NULL,
	[IsDbAccessAdmin] [bit] NULL,
	[IsDbBackupOperator] [bit] NULL,
	[IsDbDatareader] [bit] NULL,
	[IsDbDatawriter] [bit] NULL,
	[IsDbDdlAdmin] [bit] NULL,
	[IsDbDenyDatareader] [bit] NULL,
	[IsDbDenyDatawriter] [bit] NULL,
	[IsDbOwner] [bit] NULL,
	[IsDbSecurityAdmin] [bit] NULL,
	[IsFullTextEnabled] [bit] NULL,
	[IsMailHost] [bit] NULL,
	[IsManagementDataWarehouse] [bit] NULL,
	[IsMirroringEnabled] [bit] NULL,
	[IsParameterizationForced] [bit] NULL,
	[IsReadCommittedSnapshotOn] [bit] NULL,
	[IsSqlDw] [bit] NULL,
	[IsSystemObject] [bit] NULL,
	[IsUpdateable] [bit] NULL,
	[LastBackupDate] [datetime2](7) NULL,
	[LastDifferentialBackupDate] [datetime2](7) NULL,
	[LastLogBackupDate] [datetime2](7) NULL,
	[LocalCursorsDefault] [bit] NULL,
	[LogReuseWaitStatus] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MemoryAllocatedToMemoryOptimizedObjectsInKB] [float] NULL,
	[MemoryUsedByMemoryOptimizedObjectsInKB] [float] NULL,
	[MirroringFailoverLogSequenceNumber] [decimal](20, 5) NULL,
	[MirroringID] [uniqueidentifier] NULL,
	[MirroringPartner] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MirroringPartnerInstance] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MirroringRedoQueueMaxSize] [int] NULL,
	[MirroringRoleSequence] [int] NULL,
	[MirroringSafetyLevel] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MirroringSafetySequence] [int] NULL,
	[MirroringStatus] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MirroringTimeout] [int] NULL,
	[MirroringWitness] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MirroringWitnessStatus] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NestedTriggersEnabled] [bit] NULL,
	[NumericRoundAbortEnabled] [bit] NULL,
	[Owner] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PageVerify] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrimaryFilePath] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuotedIdentifiersEnabled] [bit] NULL,
	[ReadOnly] [bit] NULL,
	[RecoveryForkGuid] [uniqueidentifier] NULL,
	[RecoveryModel] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecursiveTriggersEnabled] [bit] NULL,
	[RemoteDataArchiveCredential] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemoteDataArchiveEnabled] [bit] NULL,
	[RemoteDataArchiveEndpoint] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemoteDataArchiveLinkedServer] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemoteDataArchiveUseFederatedServiceAccount] [bit] NULL,
	[RemoteDatabaseName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReplicationOptions] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceBrokerGuid] [uniqueidentifier] NULL,
	[Size] [float] NULL,
	[SnapshotIsolationState] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpaceAvailable] [float] NULL,
	[Status] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TargetRecoveryTime] [int] NULL,
	[TransformNoiseWords] [bit] NULL,
	[Trustworthy] [bit] NULL,
	[TwoDigitYearCutoff] [int] NULL,
	[UserAccess] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Version] [int] NULL,
	[AzureEdition] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AzureServiceObjective] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDbManager] [bit] NULL,
	[IsFederationMember] [bit] NULL,
	[IsLoginManager] [bit] NULL,
	[IsSqlDwEdition] [bit] NULL,
	[MaxSizeInBytes] [float] NULL,
	[TemporalHistoryRetentionEnabled] [bit] NULL,
	[Events] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExecutionManager] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseEngineType] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseEngineEdition] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WarnOnRename] [bit] NULL,
	[DatabaseOwnershipChaining] [bit] NULL,
	[ExtendedProperties] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseOptions] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QueryStoreOptions] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Synonyms] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sequences] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Federations] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Tables] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseScopedCredentials] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StoredProcedures] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Assemblies] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserDefinedTypes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserDefinedAggregates] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FullTextCatalogs] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FullTextStopLists] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SearchPropertyLists] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecurityPolicies] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseScopedConfigurations] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExternalDataSources] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExternalFileFormats] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Certificates] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ColumnMasterKeys] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ColumnEncryptionKeys] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SymmetricKeys] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AsymmetricKeys] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseEncryptionKey] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExtendedStoredProcedures] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserDefinedFunctions] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Views] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Users] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatabaseAuditSpecifications] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Schemas] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Roles] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ApplicationRoles] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LogFiles] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FileGroups] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PlanGuides] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Defaults] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Rules] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserDefinedDataTypes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserDefinedTableTypes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XmlSchemaCollections] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PartitionFunctions] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PartitionSchemes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ActiveDirectory] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MasterKey] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Triggers] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultLanguage] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefaultFullTextLanguage] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceBroker] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaxDop] [int] NULL,
	[MaxDopForSecondary] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LegacyCardinalityEstimation] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LegacyCardinalityEstimationForSecondary] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParameterSniffing] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParameterSniffingForSecondary] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QueryOptimizerHotfixes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QueryOptimizerHotfixesForSecondary] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsVarDecimalStorageFormatEnabled] [bit] NULL,
	[Urn] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Properties] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserData] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDesignMode] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
