/* CreateDate: 03/04/2022 08:19:53.647 , ModifyDate: 03/04/2022 08:19:53.647 */
GO
CREATE PROCEDURE [SF].[sp_Order_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Order])
RETURN ;

SET XACT_ABORT ON

BEGIN TRANSACTION

;MERGE [SF].[Order] AS [t]
USING [SFStaging].[Order] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[OwnerId] = [t].[OwnerId]
	, [t].[ContractId] = [t].[ContractId]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[Pricebook2Id] = [t].[Pricebook2Id]
	, [t].[OriginalOrderId] = [t].[OriginalOrderId]
	, [t].[EffectiveDate] = [t].[EffectiveDate]
	, [t].[EndDate] = [t].[EndDate]
	, [t].[IsReductionOrder] = [t].[IsReductionOrder]
	, [t].[Status] = [t].[Status]
	, [t].[Description] = [t].[Description]
	, [t].[CustomerAuthorizedById] = [t].[CustomerAuthorizedById]
	, [t].[CompanyAuthorizedById] = [t].[CompanyAuthorizedById]
	, [t].[Type] = [t].[Type]
	, [t].[BillingStreet] = [t].[BillingStreet]
	, [t].[BillingCity] = [t].[BillingCity]
	, [t].[BillingState] = [t].[BillingState]
	, [t].[BillingPostalCode] = [t].[BillingPostalCode]
	, [t].[BillingCountry] = [t].[BillingCountry]
	, [t].[BillingStateCode] = [t].[BillingStateCode]
	, [t].[BillingCountryCode] = [t].[BillingCountryCode]
	, [t].[BillingLatitude] = [t].[BillingLatitude]
	, [t].[BillingLongitude] = [t].[BillingLongitude]
	, [t].[BillingGeocodeAccuracy] = [t].[BillingGeocodeAccuracy]
	, [t].[BillingAddress] = [t].[BillingAddress]
	, [t].[ShippingStreet] = [t].[ShippingStreet]
	, [t].[ShippingCity] = [t].[ShippingCity]
	, [t].[ShippingState] = [t].[ShippingState]
	, [t].[ShippingPostalCode] = [t].[ShippingPostalCode]
	, [t].[ShippingCountry] = [t].[ShippingCountry]
	, [t].[ShippingStateCode] = [t].[ShippingStateCode]
	, [t].[ShippingCountryCode] = [t].[ShippingCountryCode]
	, [t].[ShippingLatitude] = [t].[ShippingLatitude]
	, [t].[ShippingLongitude] = [t].[ShippingLongitude]
	, [t].[ShippingGeocodeAccuracy] = [t].[ShippingGeocodeAccuracy]
	, [t].[ShippingAddress] = [t].[ShippingAddress]
	, [t].[ActivatedDate] = [t].[ActivatedDate]
	, [t].[ActivatedById] = [t].[ActivatedById]
	, [t].[StatusCode] = [t].[StatusCode]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[OrderNumber] = [t].[OrderNumber]
	, [t].[TotalAmount] = [t].[TotalAmount]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[IsDeleted] = [t].[IsDeleted]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [OwnerId]
	, [ContractId]
	, [AccountId]
	, [Pricebook2Id]
	, [OriginalOrderId]
	, [EffectiveDate]
	, [EndDate]
	, [IsReductionOrder]
	, [Status]
	, [Description]
	, [CustomerAuthorizedById]
	, [CompanyAuthorizedById]
	, [Type]
	, [BillingStreet]
	, [BillingCity]
	, [BillingState]
	, [BillingPostalCode]
	, [BillingCountry]
	, [BillingStateCode]
	, [BillingCountryCode]
	, [BillingLatitude]
	, [BillingLongitude]
	, [BillingGeocodeAccuracy]
	, [BillingAddress]
	, [ShippingStreet]
	, [ShippingCity]
	, [ShippingState]
	, [ShippingPostalCode]
	, [ShippingCountry]
	, [ShippingStateCode]
	, [ShippingCountryCode]
	, [ShippingLatitude]
	, [ShippingLongitude]
	, [ShippingGeocodeAccuracy]
	, [ShippingAddress]
	, [ActivatedDate]
	, [ActivatedById]
	, [StatusCode]
	, [CurrencyIsoCode]
	, [OrderNumber]
	, [TotalAmount]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [IsDeleted]
	, [SystemModstamp]
	, [LastViewedDate]
	, [LastReferencedDate]
	)
	VALUES(
	[s].[Id]
	, [s].[OwnerId]
	, [s].[ContractId]
	, [s].[AccountId]
	, [s].[Pricebook2Id]
	, [s].[OriginalOrderId]
	, [s].[EffectiveDate]
	, [s].[EndDate]
	, [s].[IsReductionOrder]
	, [s].[Status]
	, [s].[Description]
	, [s].[CustomerAuthorizedById]
	, [s].[CompanyAuthorizedById]
	, [s].[Type]
	, [s].[BillingStreet]
	, [s].[BillingCity]
	, [s].[BillingState]
	, [s].[BillingPostalCode]
	, [s].[BillingCountry]
	, [s].[BillingStateCode]
	, [s].[BillingCountryCode]
	, [s].[BillingLatitude]
	, [s].[BillingLongitude]
	, [s].[BillingGeocodeAccuracy]
	, [s].[BillingAddress]
	, [s].[ShippingStreet]
	, [s].[ShippingCity]
	, [s].[ShippingState]
	, [s].[ShippingPostalCode]
	, [s].[ShippingCountry]
	, [s].[ShippingStateCode]
	, [s].[ShippingCountryCode]
	, [s].[ShippingLatitude]
	, [s].[ShippingLongitude]
	, [s].[ShippingGeocodeAccuracy]
	, [s].[ShippingAddress]
	, [s].[ActivatedDate]
	, [s].[ActivatedById]
	, [s].[StatusCode]
	, [s].[CurrencyIsoCode]
	, [s].[OrderNumber]
	, [s].[TotalAmount]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[IsDeleted]
	, [s].[SystemModstamp]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Order] ;

COMMIT ;
GO
