/* CreateDate: 03/04/2022 08:19:53.857 , ModifyDate: 03/04/2022 08:19:53.857 */
GO
CREATE PROCEDURE [SF].[sp_ServiceAppointment_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[ServiceAppointment])
RETURN ;

SET XACT_ABORT ON

BEGIN TRANSACTION

;MERGE [SF].[ServiceAppointment] AS [t]
USING [SFStaging].[ServiceAppointment] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[OwnerId] = [t].[OwnerId]
	, [t].[IsDeleted] = [t].[IsDeleted]
	, [t].[AppointmentNumber] = [t].[AppointmentNumber]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[ParentRecordId] = [t].[ParentRecordId]
	, [t].[ParentRecordType] = [t].[ParentRecordType]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[WorkTypeId] = [t].[WorkTypeId]
	, [t].[ContactId] = [t].[ContactId]
	, [t].[Street] = [t].[Street]
	, [t].[City] = [t].[City]
	, [t].[State] = [t].[State]
	, [t].[PostalCode] = [t].[PostalCode]
	, [t].[Country] = [t].[Country]
	, [t].[StateCode] = [t].[StateCode]
	, [t].[CountryCode] = [t].[CountryCode]
	, [t].[Latitude] = [t].[Latitude]
	, [t].[Longitude] = [t].[Longitude]
	, [t].[GeocodeAccuracy] = [t].[GeocodeAccuracy]
	, [t].[Address] = [t].[Address]
	, [t].[Description] = [t].[Description]
	, [t].[EarliestStartTime] = [t].[EarliestStartTime]
	, [t].[DueDate] = [t].[DueDate]
	, [t].[Duration] = [t].[Duration]
	, [t].[ArrivalWindowStartTime] = [t].[ArrivalWindowStartTime]
	, [t].[ArrivalWindowEndTime] = [t].[ArrivalWindowEndTime]
	, [t].[Status] = [t].[Status]
	, [t].[SchedStartTime] = [t].[SchedStartTime]
	, [t].[SchedEndTime] = [t].[SchedEndTime]
	, [t].[ActualStartTime] = [t].[ActualStartTime]
	, [t].[ActualEndTime] = [t].[ActualEndTime]
	, [t].[ActualDuration] = [t].[ActualDuration]
	, [t].[DurationType] = [t].[DurationType]
	, [t].[DurationInMinutes] = [t].[DurationInMinutes]
	, [t].[ServiceTerritoryId] = [t].[ServiceTerritoryId]
	, [t].[Subject] = [t].[Subject]
	, [t].[ParentRecordStatusCategory] = [t].[ParentRecordStatusCategory]
	, [t].[StatusCategory] = [t].[StatusCategory]
	, [t].[ServiceNote] = [t].[ServiceNote]
	, [t].[AppointmentType] = [t].[AppointmentType]
	, [t].[Email] = [t].[Email]
	, [t].[Phone] = [t].[Phone]
	, [t].[CancellationReason] = [t].[CancellationReason]
	, [t].[AdditionalInformation] = [t].[AdditionalInformation]
	, [t].[Comments] = [t].[Comments]
	, [t].[IsAnonymousBooking] = [t].[IsAnonymousBooking]
	, [t].[IsOffsiteAppointment] = [t].[IsOffsiteAppointment]
	, [t].[ApptBookingInfoUrl] = [t].[ApptBookingInfoUrl]
	, [t].[Confirmer_User__c] = [t].[Confirmer_User__c]
	, [t].[External_Id__c] = [t].[External_Id__c]
	, [t].[Meeting_Platform_Id__c] = [t].[Meeting_Platform_Id__c]
	, [t].[Meeting_Platform__c] = [t].[Meeting_Platform__c]
	, [t].[Service_Appointment__c] = [t].[Service_Appointment__c]
	, [t].[Work_Type_Group__c] = [t].[Work_Type_Group__c]
	, [t].[Appointment_Type__c] = [t].[Appointment_Type__c]
	, [t].[Scheduled_End_Text__c] = [t].[Scheduled_End_Text__c]
	, [t].[Scheduled_Start_Text__c] = [t].[Scheduled_Start_Text__c]
	, [t].[Agent_Appointment_Link__c] = [t].[Agent_Appointment_Link__c]
	, [t].[Automatic_Trigger__c] = [t].[Automatic_Trigger__c]
	, [t].[Guest_Appointment_Link__c] = [t].[Guest_Appointment_Link__c]
	, [t].[Meeting_Point__c] = [t].[Meeting_Point__c]
	, [t].[Video_Session_Mode__c] = [t].[Video_Session_Mode__c]
	, [t].[Agent_Link__c] = [t].[Agent_Link__c]
	, [t].[Guest_Link__c] = [t].[Guest_Link__c]
	, [t].[Is_Video_Appointment__c] = [t].[Is_Video_Appointment__c]
	, [t].[Sightcall_Appointment__c] = [t].[Sightcall_Appointment__c]
	, [t].[Test_date__c] = [t].[Test_date__c]
	, [t].[Are_you_sure_confirm__c] = [t].[Are_you_sure_confirm__c]
	, [t].[Appointment_Start_Date__c] = [t].[Appointment_Start_Date__c]
	, [t].[Appointment_End_Date__c] = [t].[Appointment_End_Date__c]
	, [t].[Lead__c] = [t].[Lead__c]
	, [t].[Person_Account__c] = [t].[Person_Account__c]
	, [t].[Parent_Record_Type__c] = [t].[Parent_Record_Type__c]
	, [t].[Scheduled_Start_Date_Value__c] = [t].[Scheduled_Start_Date_Value__c]
	, [t].[Service_Territory_Number__c] = [t].[Service_Territory_Number__c]
	, [t].[Result__c] = [t].[Result__c]
	, [t].[Created_By_Title__c] = [t].[Created_By_Title__c]
	, [t].[Bosley_Center_Number__c] = [t].[Bosley_Center_Number__c]
	, [t].[Gender__c] = [t].[Gender__c]
	, [t].[Previous_Appt_Same_Day__c] = [t].[Previous_Appt_Same_Day__c]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [OwnerId]
	, [IsDeleted]
	, [AppointmentNumber]
	, [CurrencyIsoCode]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [ParentRecordId]
	, [ParentRecordType]
	, [AccountId]
	, [WorkTypeId]
	, [ContactId]
	, [Street]
	, [City]
	, [State]
	, [PostalCode]
	, [Country]
	, [StateCode]
	, [CountryCode]
	, [Latitude]
	, [Longitude]
	, [GeocodeAccuracy]
	, [Address]
	, [Description]
	, [EarliestStartTime]
	, [DueDate]
	, [Duration]
	, [ArrivalWindowStartTime]
	, [ArrivalWindowEndTime]
	, [Status]
	, [SchedStartTime]
	, [SchedEndTime]
	, [ActualStartTime]
	, [ActualEndTime]
	, [ActualDuration]
	, [DurationType]
	, [DurationInMinutes]
	, [ServiceTerritoryId]
	, [Subject]
	, [ParentRecordStatusCategory]
	, [StatusCategory]
	, [ServiceNote]
	, [AppointmentType]
	, [Email]
	, [Phone]
	, [CancellationReason]
	, [AdditionalInformation]
	, [Comments]
	, [IsAnonymousBooking]
	, [IsOffsiteAppointment]
	, [ApptBookingInfoUrl]
	, [Confirmer_User__c]
	, [External_Id__c]
	, [Meeting_Platform_Id__c]
	, [Meeting_Platform__c]
	, [Service_Appointment__c]
	, [Work_Type_Group__c]
	, [Appointment_Type__c]
	, [Scheduled_End_Text__c]
	, [Scheduled_Start_Text__c]
	, [Agent_Appointment_Link__c]
	, [Automatic_Trigger__c]
	, [Guest_Appointment_Link__c]
	, [Meeting_Point__c]
	, [Video_Session_Mode__c]
	, [Agent_Link__c]
	, [Guest_Link__c]
	, [Is_Video_Appointment__c]
	, [Sightcall_Appointment__c]
	, [Test_date__c]
	, [Are_you_sure_confirm__c]
	, [Appointment_Start_Date__c]
	, [Appointment_End_Date__c]
	, [Lead__c]
	, [Person_Account__c]
	, [Parent_Record_Type__c]
	, [Scheduled_Start_Date_Value__c]
	, [Service_Territory_Number__c]
	, [Result__c]
	, [Created_By_Title__c]
	, [Bosley_Center_Number__c]
	, [Gender__c]
	, [Previous_Appt_Same_Day__c]
	)
	VALUES(
	[s].[Id]
	, [s].[OwnerId]
	, [s].[IsDeleted]
	, [s].[AppointmentNumber]
	, [s].[CurrencyIsoCode]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[ParentRecordId]
	, [s].[ParentRecordType]
	, [s].[AccountId]
	, [s].[WorkTypeId]
	, [s].[ContactId]
	, [s].[Street]
	, [s].[City]
	, [s].[State]
	, [s].[PostalCode]
	, [s].[Country]
	, [s].[StateCode]
	, [s].[CountryCode]
	, [s].[Latitude]
	, [s].[Longitude]
	, [s].[GeocodeAccuracy]
	, [s].[Address]
	, [s].[Description]
	, [s].[EarliestStartTime]
	, [s].[DueDate]
	, [s].[Duration]
	, [s].[ArrivalWindowStartTime]
	, [s].[ArrivalWindowEndTime]
	, [s].[Status]
	, [s].[SchedStartTime]
	, [s].[SchedEndTime]
	, [s].[ActualStartTime]
	, [s].[ActualEndTime]
	, [s].[ActualDuration]
	, [s].[DurationType]
	, [s].[DurationInMinutes]
	, [s].[ServiceTerritoryId]
	, [s].[Subject]
	, [s].[ParentRecordStatusCategory]
	, [s].[StatusCategory]
	, [s].[ServiceNote]
	, [s].[AppointmentType]
	, [s].[Email]
	, [s].[Phone]
	, [s].[CancellationReason]
	, [s].[AdditionalInformation]
	, [s].[Comments]
	, [s].[IsAnonymousBooking]
	, [s].[IsOffsiteAppointment]
	, [s].[ApptBookingInfoUrl]
	, [s].[Confirmer_User__c]
	, [s].[External_Id__c]
	, [s].[Meeting_Platform_Id__c]
	, [s].[Meeting_Platform__c]
	, [s].[Service_Appointment__c]
	, [s].[Work_Type_Group__c]
	, [s].[Appointment_Type__c]
	, [s].[Scheduled_End_Text__c]
	, [s].[Scheduled_Start_Text__c]
	, [s].[Agent_Appointment_Link__c]
	, [s].[Automatic_Trigger__c]
	, [s].[Guest_Appointment_Link__c]
	, [s].[Meeting_Point__c]
	, [s].[Video_Session_Mode__c]
	, [s].[Agent_Link__c]
	, [s].[Guest_Link__c]
	, [s].[Is_Video_Appointment__c]
	, [s].[Sightcall_Appointment__c]
	, [s].[Test_date__c]
	, [s].[Are_you_sure_confirm__c]
	, [s].[Appointment_Start_Date__c]
	, [s].[Appointment_End_Date__c]
	, [s].[Lead__c]
	, [s].[Person_Account__c]
	, [s].[Parent_Record_Type__c]
	, [s].[Scheduled_Start_Date_Value__c]
	, [s].[Service_Territory_Number__c]
	, [s].[Result__c]
	, [s].[Created_By_Title__c]
	, [s].[Bosley_Center_Number__c]
	, [s].[Gender__c]
	, [s].[Previous_Appt_Same_Day__c]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[ServiceAppointment] ;

COMMIT ;
GO
