/* CreateDate: 03/04/2022 08:19:54.840 , ModifyDate: 03/04/2022 08:19:54.840 */
GO
CREATE PROCEDURE [SF].[sp_Contact_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Contact])
RETURN ;

SET XACT_ABORT ON

BEGIN TRANSACTION

;MERGE [SF].[Contact] AS [t]
USING [SFStaging].[Contact] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[IsDeleted] = [t].[IsDeleted]
	, [t].[MasterRecordId] = [t].[MasterRecordId]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[IsPersonAccount] = [t].[IsPersonAccount]
	, [t].[LastName] = [t].[LastName]
	, [t].[FirstName] = [t].[FirstName]
	, [t].[Salutation] = [t].[Salutation]
	, [t].[MiddleName] = [t].[MiddleName]
	, [t].[Suffix] = [t].[Suffix]
	, [t].[Name] = [t].[Name]
	, [t].[MailingStreet] = [t].[MailingStreet]
	, [t].[MailingCity] = [t].[MailingCity]
	, [t].[MailingState] = [t].[MailingState]
	, [t].[MailingPostalCode] = [t].[MailingPostalCode]
	, [t].[MailingCountry] = [t].[MailingCountry]
	, [t].[MailingStateCode] = [t].[MailingStateCode]
	, [t].[MailingCountryCode] = [t].[MailingCountryCode]
	, [t].[MailingLatitude] = [t].[MailingLatitude]
	, [t].[MailingLongitude] = [t].[MailingLongitude]
	, [t].[MailingGeocodeAccuracy] = [t].[MailingGeocodeAccuracy]
	, [t].[Phone] = [t].[Phone]
	, [t].[Fax] = [t].[Fax]
	, [t].[MobilePhone] = [t].[MobilePhone]
	, [t].[HomePhone] = [t].[HomePhone]
	, [t].[OtherPhone] = [t].[OtherPhone]
	, [t].[AssistantPhone] = [t].[AssistantPhone]
	, [t].[ReportsToId] = [t].[ReportsToId]
	, [t].[Email] = [t].[Email]
	, [t].[Title] = [t].[Title]
	, [t].[Department] = [t].[Department]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[OwnerId] = [t].[OwnerId]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastActivityDate] = [t].[LastActivityDate]
	, [t].[LastCURequestDate] = [t].[LastCURequestDate]
	, [t].[LastCUUpdateDate] = [t].[LastCUUpdateDate]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[EmailBouncedReason] = [t].[EmailBouncedReason]
	, [t].[EmailBouncedDate] = [t].[EmailBouncedDate]
	, [t].[IsEmailBounced] = [t].[IsEmailBounced]
	, [t].[PhotoUrl] = [t].[PhotoUrl]
	, [t].[Jigsaw] = [t].[Jigsaw]
	, [t].[JigsawContactId] = [t].[JigsawContactId]
	, [t].[Age__c] = [t].[Age__c]
	, [t].[Birthdate__c] = [t].[Birthdate__c]
	, [t].[DoNotContact__c] = [t].[DoNotContact__c]
	, [t].[DoNotEmail__c] = [t].[DoNotEmail__c]
	, [t].[DoNotMail__c] = [t].[DoNotMail__c]
	, [t].[DoNotText__c] = [t].[DoNotText__c]
	, [t].[Ethnicity__c] = [t].[Ethnicity__c]
	, [t].[Gender__c] = [t].[Gender__c]
	, [t].[HairLossExperience__c] = [t].[HairLossExperience__c]
	, [t].[HairLossFamily__c] = [t].[HairLossFamily__c]
	, [t].[HairLossOrVolume__c] = [t].[HairLossOrVolume__c]
	, [t].[HairLossProductOther__c] = [t].[HairLossProductOther__c]
	, [t].[HairLossProductUsed__c] = [t].[HairLossProductUsed__c]
	, [t].[HairLossSpot__c] = [t].[HairLossSpot__c]
	, [t].[HardCopyPreferred__c] = [t].[HardCopyPreferred__c]
	, [t].[Language__c] = [t].[Language__c]
	, [t].[MaritalStatus__c] = [t].[MaritalStatus__c]
	, [t].[Text_Reminder_Opt_In__c] = [t].[Text_Reminder_Opt_In__c]
	, [t].[rh2__Currency_Test__c] = [t].[rh2__Currency_Test__c]
	, [t].[rh2__Describe__c] = [t].[rh2__Describe__c]
	, [t].[rh2__Formula_Test__c] = [t].[rh2__Formula_Test__c]
	, [t].[rh2__Integer_Test__c] = [t].[rh2__Integer_Test__c]
	, [t].[Next_Milestone_Event__c] = [t].[Next_Milestone_Event__c]
	, [t].[Next_Milestone_Event_Date__c] = [t].[Next_Milestone_Event_Date__c]
	, [t].[Bosley_Center_Number__c] = [t].[Bosley_Center_Number__c]
	, [t].[Bosley_Client_Id__c] = [t].[Bosley_Client_Id__c]
	, [t].[Bosley_Legacy_Source_Code__c] = [t].[Bosley_Legacy_Source_Code__c]
	, [t].[Bosley_Salesforce_Id__c] = [t].[Bosley_Salesforce_Id__c]
	, [t].[Bosley_Siebel_Id__c] = [t].[Bosley_Siebel_Id__c]
	, [t].[Contact_ID_18_dig__c] = [t].[Contact_ID_18_dig__c]
	, [t].[Landing_Page_Form_Submitted_Date__c] = [t].[Landing_Page_Form_Submitted_Date__c]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [IsDeleted]
	, [MasterRecordId]
	, [AccountId]
	, [IsPersonAccount]
	, [LastName]
	, [FirstName]
	, [Salutation]
	, [MiddleName]
	, [Suffix]
	, [Name]
	, [MailingStreet]
	, [MailingCity]
	, [MailingState]
	, [MailingPostalCode]
	, [MailingCountry]
	, [MailingStateCode]
	, [MailingCountryCode]
	, [MailingLatitude]
	, [MailingLongitude]
	, [MailingGeocodeAccuracy]
	, [Phone]
	, [Fax]
	, [MobilePhone]
	, [HomePhone]
	, [OtherPhone]
	, [AssistantPhone]
	, [ReportsToId]
	, [Email]
	, [Title]
	, [Department]
	, [CurrencyIsoCode]
	, [OwnerId]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastActivityDate]
	, [LastCURequestDate]
	, [LastCUUpdateDate]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [EmailBouncedReason]
	, [EmailBouncedDate]
	, [IsEmailBounced]
	, [PhotoUrl]
	, [Jigsaw]
	, [JigsawContactId]
	, [Age__c]
	, [Birthdate__c]
	, [DoNotContact__c]
	, [DoNotEmail__c]
	, [DoNotMail__c]
	, [DoNotText__c]
	, [Ethnicity__c]
	, [Gender__c]
	, [HairLossExperience__c]
	, [HairLossFamily__c]
	, [HairLossOrVolume__c]
	, [HairLossProductOther__c]
	, [HairLossProductUsed__c]
	, [HairLossSpot__c]
	, [HardCopyPreferred__c]
	, [Language__c]
	, [MaritalStatus__c]
	, [Text_Reminder_Opt_In__c]
	, [rh2__Currency_Test__c]
	, [rh2__Describe__c]
	, [rh2__Formula_Test__c]
	, [rh2__Integer_Test__c]
	, [Next_Milestone_Event__c]
	, [Next_Milestone_Event_Date__c]
	, [Bosley_Center_Number__c]
	, [Bosley_Client_Id__c]
	, [Bosley_Legacy_Source_Code__c]
	, [Bosley_Salesforce_Id__c]
	, [Bosley_Siebel_Id__c]
	, [Contact_ID_18_dig__c]
	, [Landing_Page_Form_Submitted_Date__c]
	)
	VALUES(
	[s].[Id]
	, [s].[IsDeleted]
	, [s].[MasterRecordId]
	, [s].[AccountId]
	, [s].[IsPersonAccount]
	, [s].[LastName]
	, [s].[FirstName]
	, [s].[Salutation]
	, [s].[MiddleName]
	, [s].[Suffix]
	, [s].[Name]
	, [s].[MailingStreet]
	, [s].[MailingCity]
	, [s].[MailingState]
	, [s].[MailingPostalCode]
	, [s].[MailingCountry]
	, [s].[MailingStateCode]
	, [s].[MailingCountryCode]
	, [s].[MailingLatitude]
	, [s].[MailingLongitude]
	, [s].[MailingGeocodeAccuracy]
	, [s].[Phone]
	, [s].[Fax]
	, [s].[MobilePhone]
	, [s].[HomePhone]
	, [s].[OtherPhone]
	, [s].[AssistantPhone]
	, [s].[ReportsToId]
	, [s].[Email]
	, [s].[Title]
	, [s].[Department]
	, [s].[CurrencyIsoCode]
	, [s].[OwnerId]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastActivityDate]
	, [s].[LastCURequestDate]
	, [s].[LastCUUpdateDate]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[EmailBouncedReason]
	, [s].[EmailBouncedDate]
	, [s].[IsEmailBounced]
	, [s].[PhotoUrl]
	, [s].[Jigsaw]
	, [s].[JigsawContactId]
	, [s].[Age__c]
	, [s].[Birthdate__c]
	, [s].[DoNotContact__c]
	, [s].[DoNotEmail__c]
	, [s].[DoNotMail__c]
	, [s].[DoNotText__c]
	, [s].[Ethnicity__c]
	, [s].[Gender__c]
	, [s].[HairLossExperience__c]
	, [s].[HairLossFamily__c]
	, [s].[HairLossOrVolume__c]
	, [s].[HairLossProductOther__c]
	, [s].[HairLossProductUsed__c]
	, [s].[HairLossSpot__c]
	, [s].[HardCopyPreferred__c]
	, [s].[Language__c]
	, [s].[MaritalStatus__c]
	, [s].[Text_Reminder_Opt_In__c]
	, [s].[rh2__Currency_Test__c]
	, [s].[rh2__Describe__c]
	, [s].[rh2__Formula_Test__c]
	, [s].[rh2__Integer_Test__c]
	, [s].[Next_Milestone_Event__c]
	, [s].[Next_Milestone_Event_Date__c]
	, [s].[Bosley_Center_Number__c]
	, [s].[Bosley_Client_Id__c]
	, [s].[Bosley_Legacy_Source_Code__c]
	, [s].[Bosley_Salesforce_Id__c]
	, [s].[Bosley_Siebel_Id__c]
	, [s].[Contact_ID_18_dig__c]
	, [s].[Landing_Page_Form_Submitted_Date__c]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Contact] ;

COMMIT ;
GO
