/* CreateDate: 10/04/2019 14:09:30.240 , ModifyDate: 10/04/2019 14:09:30.240 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [sp_MSupd_dboCampaign]
		@c1 nvarchar(18) = NULL,
		@c2 nvarchar(80) = NULL,
		@c3 bit = NULL,
		@c4 nvarchar(18) = NULL,
		@c5 nvarchar(50) = NULL,
		@c6 nvarchar(50) = NULL,
		@c7 nvarchar(50) = NULL,
		@c8 nvarchar(50) = NULL,
		@c9 nvarchar(50) = NULL,
		@c10 nvarchar(50) = NULL,
		@c11 nvarchar(50) = NULL,
		@c12 nvarchar(50) = NULL,
		@c13 nvarchar(50) = NULL,
		@c14 nvarchar(50) = NULL,
		@c15 nvarchar(50) = NULL,
		@c16 nvarchar(50) = NULL,
		@c17 nvarchar(50) = NULL,
		@c18 nvarchar(30) = NULL,
		@c19 nvarchar(50) = NULL,
		@c20 datetime = NULL,
		@c21 datetime = NULL,
		@c22 nvarchar(50) = NULL,
		@c23 nvarchar(50) = NULL,
		@c24 nvarchar(50) = NULL,
		@c25 nvarchar(50) = NULL,
		@c26 nvarchar(50) = NULL,
		@c27 nvarchar(255) = NULL,
		@c28 bit = NULL,
		@c29 nvarchar(50) = NULL,
		@c30 nvarchar(50) = NULL,
		@c31 nvarchar(50) = NULL,
		@c32 nvarchar(50) = NULL,
		@c33 nvarchar(50) = NULL,
		@c34 nvarchar(50) = NULL,
		@c35 nvarchar(255) = NULL,
		@c36 nvarchar(50) = NULL,
		@c37 nvarchar(50) = NULL,
		@c38 nvarchar(50) = NULL,
		@c39 nvarchar(50) = NULL,
		@c40 nvarchar(255) = NULL,
		@c41 nvarchar(255) = NULL,
		@c42 nvarchar(255) = NULL,
		@c43 nvarchar(50) = NULL,
		@c44 nvarchar(255) = NULL,
		@c45 int = NULL,
		@c46 float = NULL,
		@c47 money = NULL,
		@c48 money = NULL,
		@c49 money = NULL,
		@c50 int = NULL,
		@c51 int = NULL,
		@c52 int = NULL,
		@c53 int = NULL,
		@c54 int = NULL,
		@c55 int = NULL,
		@c56 money = NULL,
		@c57 money = NULL,
		@c58 nvarchar(100) = NULL,
		@c59 nvarchar(50) = NULL,
		@c60 nvarchar(100) = NULL,
		@c61 nvarchar(10) = NULL,
		@c62 nvarchar(50) = NULL,
		@c63 nvarchar(50) = NULL,
		@c64 nvarchar(50) = NULL,
		@c65 nvarchar(50) = NULL,
		@c66 nvarchar(50) = NULL,
		@c67 nvarchar(50) = NULL,
		@c68 nvarchar(50) = NULL,
		@c69 nvarchar(255) = NULL,
		@c70 nvarchar(50) = NULL,
		@c71 nvarchar(50) = NULL,
		@c72 nvarchar(50) = NULL,
		@c73 nvarchar(50) = NULL,
		@c74 nvarchar(50) = NULL,
		@c75 nvarchar(50) = NULL,
		@c76 nvarchar(50) = NULL,
		@c77 nvarchar(50) = NULL,
		@c78 nvarchar(50) = NULL,
		@c79 nvarchar(50) = NULL,
		@c80 nvarchar(50) = NULL,
		@c81 nvarchar(50) = NULL,
		@c82 bit = NULL,
		@c83 nvarchar(18) = NULL,
		@c84 datetime = NULL,
		@c85 nvarchar(18) = NULL,
		@c86 datetime = NULL,
		@pkc1 nvarchar(18) = NULL,
		@bitmap binary(11)
as
begin
	declare @primarykey_text nvarchar(100) = ''
if (substring(@bitmap,1,1) & 1 = 1)
begin
update [dbo].[Campaign] set
		[Id] = case substring(@bitmap,1,1) & 1 when 1 then @c1 else [Id] end,
		[Name] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [Name] end,
		[IsActive] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [IsActive] end,
		[ParentId] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [ParentId] end,
		[Type] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [Type] end,
		[PromoCode__c] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [PromoCode__c] end,
		[Channel__c] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [Channel__c] end,
		[ShortcodeChannel__c] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [ShortcodeChannel__c] end,
		[Language__c] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [Language__c] end,
		[Media__c] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Media__c] end,
		[ShortcodeMedia__c] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [ShortcodeMedia__c] end,
		[Source__c] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [Source__c] end,
		[ShortcodeOrigin__c] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [ShortcodeOrigin__c] end,
		[Format__c] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Format__c] end,
		[ShortcodeFormat__c] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [ShortcodeFormat__c] end,
		[Goal__c] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Goal__c] end,
		[PromoCodeName__c] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [PromoCodeName__c] end,
		[SourceCodeNumber__c] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [SourceCodeNumber__c] end,
		[Status] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [Status] end,
		[StartDate] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [StartDate] end,
		[EndDate] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [EndDate] end,
		[Gender__c] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [Gender__c] end,
		[CampaignType__c] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [CampaignType__c] end,
		[CommunicationType__c] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [CommunicationType__c] end,
		[TollFreeName__c] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [TollFreeName__c] end,
		[TollFreeMobileName__c] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [TollFreeMobileName__c] end,
		[URLDomain__c] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [URLDomain__c] end,
		[GenerateCodes__c] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [GenerateCodes__c] end,
		[SourceCode_L__c] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [SourceCode_L__c] end,
		[DPNCode__c] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [DPNCode__c] end,
		[DWFCode__c] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [DWFCode__c] end,
		[DWCCode__c] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [DWCCode__c] end,
		[DNIS__c] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [DNIS__c] end,
		[DNISMobile__c] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [DNISMobile__c] end,
		[Referrer__c] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [Referrer__c] end,
		[SCNumber__c] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [SCNumber__c] end,
		[MPNCode__c] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [MPNCode__c] end,
		[MWFCode__c] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [MWFCode__c] end,
		[MWCCode__c] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [MWCCode__c] end,
		[ACE_Decription__c] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [ACE_Decription__c] end,
		[Description] = case substring(@bitmap,6,1) & 1 when 1 then @c41 else [Description] end,
		[WebCode__c] = case substring(@bitmap,6,1) & 2 when 2 then @c42 else [WebCode__c] end,
		[Location__c] = case substring(@bitmap,6,1) & 4 when 4 then @c43 else [Location__c] end,
		[PromoCodeDisplay__c] = case substring(@bitmap,6,1) & 8 when 8 then @c44 else [PromoCodeDisplay__c] end,
		[NumberSent] = case substring(@bitmap,6,1) & 16 when 16 then @c45 else [NumberSent] end,
		[ExpectedResponse] = case substring(@bitmap,6,1) & 32 when 32 then @c46 else [ExpectedResponse] end,
		[BudgetedCost] = case substring(@bitmap,6,1) & 64 when 64 then @c47 else [BudgetedCost] end,
		[ActualCost] = case substring(@bitmap,6,1) & 128 when 128 then @c48 else [ActualCost] end,
		[ExpectedRevenue] = case substring(@bitmap,7,1) & 1 when 1 then @c49 else [ExpectedRevenue] end,
		[NumberOfResponses] = case substring(@bitmap,7,1) & 2 when 2 then @c50 else [NumberOfResponses] end,
		[NumberOfLeads] = case substring(@bitmap,7,1) & 4 when 4 then @c51 else [NumberOfLeads] end,
		[NumberOfConvertedLeads] = case substring(@bitmap,7,1) & 8 when 8 then @c52 else [NumberOfConvertedLeads] end,
		[NumberOfContacts] = case substring(@bitmap,7,1) & 16 when 16 then @c53 else [NumberOfContacts] end,
		[NumberOfOpportunities] = case substring(@bitmap,7,1) & 32 when 32 then @c54 else [NumberOfOpportunities] end,
		[NumberOfWonOpportunities] = case substring(@bitmap,7,1) & 64 when 64 then @c55 else [NumberOfWonOpportunities] end,
		[AmountAllOpportunities] = case substring(@bitmap,7,1) & 128 when 128 then @c56 else [AmountAllOpportunities] end,
		[AmountWonOpportunities] = case substring(@bitmap,8,1) & 1 when 1 then @c57 else [AmountWonOpportunities] end,
		[Promo_Code_L__c] = case substring(@bitmap,8,1) & 2 when 2 then @c58 else [Promo_Code_L__c] end,
		[SourceID_L__c] = case substring(@bitmap,8,1) & 4 when 4 then @c59 else [SourceID_L__c] end,
		[SourceName_L__c] = case substring(@bitmap,8,1) & 8 when 8 then @c60 else [SourceName_L__c] end,
		[IsInHouseSourceFlag_L__c] = case substring(@bitmap,8,1) & 16 when 16 then @c61 else [IsInHouseSourceFlag_L__c] end,
		[PhoneID_L__c] = case substring(@bitmap,8,1) & 32 when 32 then @c62 else [PhoneID_L__c] end,
		[Number_L__c] = case substring(@bitmap,8,1) & 64 when 64 then @c63 else [Number_L__c] end,
		[NumberTypeID_L__c] = case substring(@bitmap,8,1) & 128 when 128 then @c64 else [NumberTypeID_L__c] end,
		[NumberType_L__c] = case substring(@bitmap,9,1) & 1 when 1 then @c65 else [NumberType_L__c] end,
		[MediaID_L__c] = case substring(@bitmap,9,1) & 2 when 2 then @c66 else [MediaID_L__c] end,
		[Media_L__c] = case substring(@bitmap,9,1) & 4 when 4 then @c67 else [Media_L__c] end,
		[MediaCode_L__c] = case substring(@bitmap,9,1) & 8 when 8 then @c68 else [MediaCode_L__c] end,
		[Notes_L__c] = case substring(@bitmap,9,1) & 16 when 16 then @c69 else [Notes_L__c] end,
		[Campaign_Counter__c] = case substring(@bitmap,9,1) & 32 when 32 then @c70 else [Campaign_Counter__c] end,
		[Level02LocationCode_L__c] = case substring(@bitmap,9,1) & 64 when 64 then @c71 else [Level02LocationCode_L__c] end,
		[Level02Location_L__c] = case substring(@bitmap,9,1) & 128 when 128 then @c72 else [Level02Location_L__c] end,
		[Level03ID_L__c] = case substring(@bitmap,10,1) & 1 when 1 then @c73 else [Level03ID_L__c] end,
		[Level03LanguageCode_L__c] = case substring(@bitmap,10,1) & 2 when 2 then @c74 else [Level03LanguageCode_L__c] end,
		[Level03Language_L__c] = case substring(@bitmap,10,1) & 4 when 4 then @c75 else [Level03Language_L__c] end,
		[Level04ID_L__c] = case substring(@bitmap,10,1) & 8 when 8 then @c76 else [Level04ID_L__c] end,
		[Level04FormatCode_L__c] = case substring(@bitmap,10,1) & 16 when 16 then @c77 else [Level04FormatCode_L__c] end,
		[Level04Format_L__c] = case substring(@bitmap,10,1) & 32 when 32 then @c78 else [Level04Format_L__c] end,
		[Level05ID_L__c] = case substring(@bitmap,10,1) & 64 when 64 then @c79 else [Level05ID_L__c] end,
		[Level05CreativeCode_L__c] = case substring(@bitmap,10,1) & 128 when 128 then @c80 else [Level05CreativeCode_L__c] end,
		[Level05Creative_L__c] = case substring(@bitmap,11,1) & 1 when 1 then @c81 else [Level05Creative_L__c] end,
		[IsDeleted] = case substring(@bitmap,11,1) & 2 when 2 then @c82 else [IsDeleted] end,
		[CreatedById] = case substring(@bitmap,11,1) & 4 when 4 then @c83 else [CreatedById] end,
		[CreatedDate] = case substring(@bitmap,11,1) & 8 when 8 then @c84 else [CreatedDate] end,
		[LastModifiedById] = case substring(@bitmap,11,1) & 16 when 16 then @c85 else [LastModifiedById] end,
		[LastModifiedDate] = case substring(@bitmap,11,1) & 32 when 32 then @c86 else [LastModifiedDate] end
	where [Id] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
		Begin
			if exists (Select * from sys.all_parameters where object_id = OBJECT_ID('sp_MSreplraiserror') and [name] = '@param3')
			Begin

				set @primarykey_text = @primarykey_text + '[Id] = ' + convert(nvarchar(100),@pkc1,1)
				exec sp_MSreplraiserror @errorid=20598, @param1=N'[dbo].[Campaign]', @param2=@primarykey_text, @param3=13233
			End
			Else
				exec sp_MSreplraiserror @errorid=20598
		End
end
else
begin
update [dbo].[Campaign] set
		[Name] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [Name] end,
		[IsActive] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [IsActive] end,
		[ParentId] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [ParentId] end,
		[Type] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [Type] end,
		[PromoCode__c] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [PromoCode__c] end,
		[Channel__c] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [Channel__c] end,
		[ShortcodeChannel__c] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [ShortcodeChannel__c] end,
		[Language__c] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [Language__c] end,
		[Media__c] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Media__c] end,
		[ShortcodeMedia__c] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [ShortcodeMedia__c] end,
		[Source__c] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [Source__c] end,
		[ShortcodeOrigin__c] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [ShortcodeOrigin__c] end,
		[Format__c] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Format__c] end,
		[ShortcodeFormat__c] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [ShortcodeFormat__c] end,
		[Goal__c] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Goal__c] end,
		[PromoCodeName__c] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [PromoCodeName__c] end,
		[SourceCodeNumber__c] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [SourceCodeNumber__c] end,
		[Status] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [Status] end,
		[StartDate] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [StartDate] end,
		[EndDate] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [EndDate] end,
		[Gender__c] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [Gender__c] end,
		[CampaignType__c] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [CampaignType__c] end,
		[CommunicationType__c] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [CommunicationType__c] end,
		[TollFreeName__c] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [TollFreeName__c] end,
		[TollFreeMobileName__c] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [TollFreeMobileName__c] end,
		[URLDomain__c] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [URLDomain__c] end,
		[GenerateCodes__c] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [GenerateCodes__c] end,
		[SourceCode_L__c] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [SourceCode_L__c] end,
		[DPNCode__c] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [DPNCode__c] end,
		[DWFCode__c] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [DWFCode__c] end,
		[DWCCode__c] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [DWCCode__c] end,
		[DNIS__c] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [DNIS__c] end,
		[DNISMobile__c] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [DNISMobile__c] end,
		[Referrer__c] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [Referrer__c] end,
		[SCNumber__c] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [SCNumber__c] end,
		[MPNCode__c] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [MPNCode__c] end,
		[MWFCode__c] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [MWFCode__c] end,
		[MWCCode__c] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [MWCCode__c] end,
		[ACE_Decription__c] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [ACE_Decription__c] end,
		[Description] = case substring(@bitmap,6,1) & 1 when 1 then @c41 else [Description] end,
		[WebCode__c] = case substring(@bitmap,6,1) & 2 when 2 then @c42 else [WebCode__c] end,
		[Location__c] = case substring(@bitmap,6,1) & 4 when 4 then @c43 else [Location__c] end,
		[PromoCodeDisplay__c] = case substring(@bitmap,6,1) & 8 when 8 then @c44 else [PromoCodeDisplay__c] end,
		[NumberSent] = case substring(@bitmap,6,1) & 16 when 16 then @c45 else [NumberSent] end,
		[ExpectedResponse] = case substring(@bitmap,6,1) & 32 when 32 then @c46 else [ExpectedResponse] end,
		[BudgetedCost] = case substring(@bitmap,6,1) & 64 when 64 then @c47 else [BudgetedCost] end,
		[ActualCost] = case substring(@bitmap,6,1) & 128 when 128 then @c48 else [ActualCost] end,
		[ExpectedRevenue] = case substring(@bitmap,7,1) & 1 when 1 then @c49 else [ExpectedRevenue] end,
		[NumberOfResponses] = case substring(@bitmap,7,1) & 2 when 2 then @c50 else [NumberOfResponses] end,
		[NumberOfLeads] = case substring(@bitmap,7,1) & 4 when 4 then @c51 else [NumberOfLeads] end,
		[NumberOfConvertedLeads] = case substring(@bitmap,7,1) & 8 when 8 then @c52 else [NumberOfConvertedLeads] end,
		[NumberOfContacts] = case substring(@bitmap,7,1) & 16 when 16 then @c53 else [NumberOfContacts] end,
		[NumberOfOpportunities] = case substring(@bitmap,7,1) & 32 when 32 then @c54 else [NumberOfOpportunities] end,
		[NumberOfWonOpportunities] = case substring(@bitmap,7,1) & 64 when 64 then @c55 else [NumberOfWonOpportunities] end,
		[AmountAllOpportunities] = case substring(@bitmap,7,1) & 128 when 128 then @c56 else [AmountAllOpportunities] end,
		[AmountWonOpportunities] = case substring(@bitmap,8,1) & 1 when 1 then @c57 else [AmountWonOpportunities] end,
		[Promo_Code_L__c] = case substring(@bitmap,8,1) & 2 when 2 then @c58 else [Promo_Code_L__c] end,
		[SourceID_L__c] = case substring(@bitmap,8,1) & 4 when 4 then @c59 else [SourceID_L__c] end,
		[SourceName_L__c] = case substring(@bitmap,8,1) & 8 when 8 then @c60 else [SourceName_L__c] end,
		[IsInHouseSourceFlag_L__c] = case substring(@bitmap,8,1) & 16 when 16 then @c61 else [IsInHouseSourceFlag_L__c] end,
		[PhoneID_L__c] = case substring(@bitmap,8,1) & 32 when 32 then @c62 else [PhoneID_L__c] end,
		[Number_L__c] = case substring(@bitmap,8,1) & 64 when 64 then @c63 else [Number_L__c] end,
		[NumberTypeID_L__c] = case substring(@bitmap,8,1) & 128 when 128 then @c64 else [NumberTypeID_L__c] end,
		[NumberType_L__c] = case substring(@bitmap,9,1) & 1 when 1 then @c65 else [NumberType_L__c] end,
		[MediaID_L__c] = case substring(@bitmap,9,1) & 2 when 2 then @c66 else [MediaID_L__c] end,
		[Media_L__c] = case substring(@bitmap,9,1) & 4 when 4 then @c67 else [Media_L__c] end,
		[MediaCode_L__c] = case substring(@bitmap,9,1) & 8 when 8 then @c68 else [MediaCode_L__c] end,
		[Notes_L__c] = case substring(@bitmap,9,1) & 16 when 16 then @c69 else [Notes_L__c] end,
		[Campaign_Counter__c] = case substring(@bitmap,9,1) & 32 when 32 then @c70 else [Campaign_Counter__c] end,
		[Level02LocationCode_L__c] = case substring(@bitmap,9,1) & 64 when 64 then @c71 else [Level02LocationCode_L__c] end,
		[Level02Location_L__c] = case substring(@bitmap,9,1) & 128 when 128 then @c72 else [Level02Location_L__c] end,
		[Level03ID_L__c] = case substring(@bitmap,10,1) & 1 when 1 then @c73 else [Level03ID_L__c] end,
		[Level03LanguageCode_L__c] = case substring(@bitmap,10,1) & 2 when 2 then @c74 else [Level03LanguageCode_L__c] end,
		[Level03Language_L__c] = case substring(@bitmap,10,1) & 4 when 4 then @c75 else [Level03Language_L__c] end,
		[Level04ID_L__c] = case substring(@bitmap,10,1) & 8 when 8 then @c76 else [Level04ID_L__c] end,
		[Level04FormatCode_L__c] = case substring(@bitmap,10,1) & 16 when 16 then @c77 else [Level04FormatCode_L__c] end,
		[Level04Format_L__c] = case substring(@bitmap,10,1) & 32 when 32 then @c78 else [Level04Format_L__c] end,
		[Level05ID_L__c] = case substring(@bitmap,10,1) & 64 when 64 then @c79 else [Level05ID_L__c] end,
		[Level05CreativeCode_L__c] = case substring(@bitmap,10,1) & 128 when 128 then @c80 else [Level05CreativeCode_L__c] end,
		[Level05Creative_L__c] = case substring(@bitmap,11,1) & 1 when 1 then @c81 else [Level05Creative_L__c] end,
		[IsDeleted] = case substring(@bitmap,11,1) & 2 when 2 then @c82 else [IsDeleted] end,
		[CreatedById] = case substring(@bitmap,11,1) & 4 when 4 then @c83 else [CreatedById] end,
		[CreatedDate] = case substring(@bitmap,11,1) & 8 when 8 then @c84 else [CreatedDate] end,
		[LastModifiedById] = case substring(@bitmap,11,1) & 16 when 16 then @c85 else [LastModifiedById] end,
		[LastModifiedDate] = case substring(@bitmap,11,1) & 32 when 32 then @c86 else [LastModifiedDate] end
	where [Id] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
		Begin
			if exists (Select * from sys.all_parameters where object_id = OBJECT_ID('sp_MSreplraiserror') and [name] = '@param3')
			Begin

				set @primarykey_text = @primarykey_text + '[Id] = ' + convert(nvarchar(100),@pkc1,1)
				exec sp_MSreplraiserror @errorid=20598, @param1=N'[dbo].[Campaign]', @param2=@primarykey_text, @param3=13233
			End
			Else
				exec sp_MSreplraiserror @errorid=20598
		End
end
end
GO
