/* CreateDate: 10/13/2015 12:56:36.483 , ModifyDate: 10/13/2015 12:56:36.483 */
GO
CREATE TABLE [SignalR].[Schema](
	[SchemaVersion] [int] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[SchemaVersion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
