SELECT
    [Date]
  , [Month]
  , [BudgetType]
  , [Agency]
  , [Channel]
  , [Medium]
  , [Source]
  , [Budget]
  , [Location]
  , CAST(REPLACE([BudgetAmount], ',', '') AS NUMERIC(20, 2)) AS [BudgetAmount]
  , CAST(REPLACE([TargetLeads], ',', '') AS NUMERIC(20, 2)) AS [TargetLeads]
  , [CurrencyConversion]
  , [Fee]
  , [DataStreamID]
  , [DataStreamName]
FROM [#temp] ;

SELECT *
FROM [ODS].[MA_Targets] ;

SELECT TOP 100
       [FactDate]
     , [Month]
     , [BudgetType]
     , [Agency]
     , [Channel]
     , [Medium]
     , [Source]
     , [Budget]
     , [Location]
     , [BudgetAmount]
     , [TargetLeads]
     , [CurrencyConversion]
     , [DWH_LoadDate]
     , [DWH_UpdatedDate]
     , [Fee]
     , [DataStreamID]
     , [DataStreamName]
FROM [dbo].[FactMarketingBudget] ;

SET XACT_ABORT ON ;
GO
BEGIN TRANSACTION ;

INSERT [dbo].[FactMarketingBudget]( [FactDate]
                                  , [Month]
                                  , [BudgetType]
                                  , [Agency]
                                  , [Channel]
                                  , [Medium]
                                  , [Source]
                                  , [Budget]
                                  , [Location]
                                  , [BudgetAmount]
                                  , [TargetLeads]
                                  , [CurrencyConversion]
                                  , [DWH_LoadDate]
                                  , [DWH_UpdatedDate]
                                  , [Fee]
                                  , [DataStreamID]
                                  , [DataStreamName] )
SELECT
    [date] AS [FactDate]
  , [t].[Month]
  , [t].[BudgetType]
  , [t].[Agency]
  , [t].[Channel]
  , [t].[Medium]
  , [t].[Source]
  , [t].[Budget]
  , [t].[Location]
  , [t].[BudgetAmount]
  , [t].[TargetLeads]
  , [t].[CurrencyConversion]
  , GETDATE() AS [DWH_LoadDate]
  , GETDATE() AS [DWH_UpdatedDate]
  , [t].[Fee]
  , [t].[DataStreamID]
  , [t].[DataStreamName]
FROM( SELECT
          [Date]
        , [Month]
        , [BudgetType]
        , [Agency]
        , [Channel]
        , [Medium]
        , [Source]
        , [Budget]
        , [Location]
        , CAST(REPLACE([BudgetAmount], ',', '') AS NUMERIC(20, 2)) AS [BudgetAmount]
        , CAST(REPLACE([TargetLeads], ',', '') AS NUMERIC(20, 2)) AS [TargetLeads]
        , [CurrencyConversion]
        , [Fee]
        , [DataStreamID]
        , [DataStreamName]
      FROM [#temp] ) AS [t] ;

INSERT [ODS].[MA_Targets]( [Date]
                         , [Month]
                         , [BudgetType]
                         , [Agency]
                         , [Channel]
                         , [Medium]
                         , [Source]
                         , [Budget]
                         , [Location]
                         , [BudgetAmount]
                         , [TargetLeads]
                         , [CurrencyConversion]
                         , [Fee]
                         , [DataStreamID]
                         , [DataStreamName] )
SELECT
    [t].[Date]
  , [t].[Month]
  , [t].[BudgetType]
  , [t].[Agency]
  , [t].[Channel]
  , [t].[Medium]
  , [t].[Source]
  , [t].[Budget]
  , [t].[Location]
  , [t].[BudgetAmount]
  , [t].[TargetLeads]
  , [t].[CurrencyConversion]
  , [t].[Fee]
  , [t].[DataStreamID]
  , [t].[DataStreamName]
FROM( SELECT
          [Date]
        , [Month]
        , [BudgetType]
        , [Agency]
        , [Channel]
        , [Medium]
        , [Source]
        , [Budget]
        , [Location]
        , CAST(REPLACE([BudgetAmount], ',', '') AS NUMERIC(20, 2)) AS [BudgetAmount]
        , CAST(REPLACE([TargetLeads], ',', '') AS NUMERIC(20, 2)) AS [TargetLeads]
        , [CurrencyConversion]
        , [Fee]
        , [DataStreamID]
        , [DataStreamName]
      FROM [#temp] ) AS [t] ;

COMMIT ;
