/* CreateDate: 03/21/2022 13:00:03.257 , ModifyDate: 03/21/2022 13:00:04.470 */
GO
CREATE TABLE [dbo].[_DataFlow](
	[DataFlowKey] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TableName] [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Status] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LSET] [datetime] NULL,
	[CET] [datetime] NULL,
 CONSTRAINT [PK_DataFlow] PRIMARY KEY CLUSTERED
(
	[DataFlowKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
