/* CreateDate: 10/08/2021 18:51:05.687 , ModifyDate: 10/08/2021 18:51:05.687 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SF_Event](
	[CreatedDate] [datetime] NULL,
	[Id] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrencyIsoCode] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedById] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[LastModifiedById] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SystemModstamp] [datetime2](7) NULL,
	[IsDeleted] [bit] NULL,
	[Type] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OwnerId] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhoId] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhatId] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhoCount] [int] NULL,
	[WhatCount] [int] NULL,
	[Subject] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Location] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsAllDayEvent] [bit] NULL,
	[ActivityDateTime] [datetime2](7) NULL,
	[ActivityDate] [datetime2](7) NULL,
	[DurationInMinutes] [int] NULL,
	[StartDateTime] [datetime2](7) NULL,
	[EndDateTime] [datetime2](7) NULL,
	[AccountId] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPrivate] [bit] NULL,
	[ShowAs] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsChild] [bit] NULL,
	[IsGroupEvent] [bit] NULL,
	[GroupEventType] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsArchived] [bit] NULL,
	[RecurrenceActivityId] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRecurrence] [bit] NULL,
	[RecurrenceStartDateTime] [datetime2](7) NULL,
	[RecurrenceEndDateOnly] [datetime2](7) NULL,
	[RecurrenceTimeZoneSidKey] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceType] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceInterval] [int] NULL,
	[RecurrenceDayOfWeekMask] [int] NULL,
	[RecurrenceDayOfMonth] [int] NULL,
	[RecurrenceInstance] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceMonthOfYear] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReminderDateTime] [datetime2](7) NULL,
	[IsReminderSet] [bit] NULL,
	[EventSubtype] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRecurrence2Exclusion] [bit] NULL,
	[Recurrence2PatternText] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recurrence2PatternVersion] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRecurrence2] [bit] NULL,
	[IsRecurrence2Exception] [bit] NULL,
	[Recurrence2PatternStartDate] [datetime2](7) NULL,
	[Recurrence2PatternTimeZone] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrightPattern__SPRecordingOrTranscriptURL__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Center_Name__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Completed_Date__c] [datetime2](7) NULL,
	[External_ID__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Lead__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Meeting_Platform_Id__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Meeting_Platform__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Person_Account__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recording_Link__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Result__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPRecordingOrTranscriptURL__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Service_Appointment__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Service_Territory_Caller_Id__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Agent_Link__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Guest_Link__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Opportunity__c] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AcceptedEventInviteeIds] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeclinedEventInviteeIds] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EventWhoIds] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UndecidedEventInviteeIds] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
