/* CreateDate: 12/07/2012 14:18:30.883 , ModifyDate: 12/07/2012 14:18:30.900 */
GO
CREATE TABLE [dbo].[HealthConfig](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ConfigName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ConfigValue] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_HealthConfig] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
