/* CreateDate: 06/13/2008 11:36:25.657 , ModifyDate: 06/14/2009 09:00:16.220 */
GO
CREATE TABLE [dbo].[MediaSourceQwestOptions](
	[QwestID] [smallint] IDENTITY(1,1) NOT NULL,
	[Qwest] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_QwestID] PRIMARY KEY CLUSTERED
(
	[QwestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_Qwest] UNIQUE NONCLUSTERED
(
	[Qwest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
