/* CreateDate: 06/18/2008 11:23:30.453 , ModifyDate: 06/14/2009 09:00:16.127 */
GO
CREATE TABLE [dbo].[MediaSourceNumberTypes](
	[NumberTypeID] [tinyint] IDENTITY(1,1) NOT NULL,
	[NumberType] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_NumberTypeID] PRIMARY KEY CLUSTERED
(
	[NumberTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_NumberType] UNIQUE NONCLUSTERED
(
	[NumberType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
