/* CreateDate: 06/06/2008 16:28:45.253 , ModifyDate: 06/14/2009 09:00:16.113 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MediaSourceMediaTypes](
	[MediaID] [smallint] IDENTITY(1,1) NOT NULL,
	[MediaCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Media] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MediaID] PRIMARY KEY CLUSTERED
(
	[MediaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
