/* CreateDate: 06/16/2008 17:11:43.043 , ModifyDate: 06/14/2009 09:00:16.110 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MediaSourceLevel05](
	[Level05ID] [int] IDENTITY(1,1) NOT NULL,
	[Level05CreativeCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Level05Creative] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MediaSourceLevel05] PRIMARY KEY CLUSTERED
(
	[Level05ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
