/* CreateDate: 12/15/2008 16:10:52.363 , ModifyDate: 12/15/2008 16:10:52.443 */
GO
CREATE TABLE [dbo].[EXTWinBack12152008](
	[CENTERNO] [float] NULL,
	[CENTERNAME] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CENTERPHONE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLIENTID] [float] NULL,
	[FIRSTNAME] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LASTNAME] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRESSLINE1] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRESSLINE2] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITY] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZIPCODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COUNTRY] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRICEPOINT] [money] NULL,
	[PERDAYPRICEPOINT] [money] NULL,
	[MEMBER] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
