/* CreateDate: 08/13/2021 18:01:00.883 , ModifyDate: 09/01/2021 07:28:10.423 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VWLead_MS]
AS
With vwdimLead_CTE as (
    select Id,
           CenterNumber__c,
           FirstName,
           LastName,
           Birthday__c,
           Gender__c,
           Language__c,
           Ethnicity__c,
           MaritalStatus__c,
           Occupation__c,
           NorwoodScale__c,
           LudwigScale__c,
           HairLossFamily__c,
           HairLossProductUsed__c,
           HairLossSpot__c,
           OriginalCampaignID__c,
           DoNotContact__c,
           DoNotCall,
           DoNotEmail__c,
           DoNotMail__c,
           DoNotText__c,
           GCLID__c,
           Status,
           IsDeleted,
           CreatedDate,
           LastModifiedDate,
           RecentSourceCode__c,
           City,
           State,
           PostalCode,
           LeadSource,
           Email,
           Phone,
           MobilePhone,
           isValid,
           externalID,
           CreatedDateEst,
           ConvertedContactId,
           Source_Code_Legacy__c,
           Street,
           IsNew,
           ConvertedAccountId,
           CreatedById,
           LastModifiedById
    from HC_BI_SFDC.dbo.Lead dl
    where convert(date, dl.CreatedDate) <= '2021-06-15'
    UNION ALL
    select leadid,
           CenterNumber,
           LeadFirstName,
           LeadLastname,
           LeadBirthday,
           LeadGender,
           LeadLanguage,
           LeadEthnicity,
           LeadMaritalStatus,
           LeadOccupation,
           NorwoodScale,
           LudwigScale,
           HairLossInFamily,
           HairLossProductUsed,
           HairLossSpot,
           OriginalCampaignId,
           DoNotContact,
           DoNotCall,
           DoNotEmail,
           DoNotMail,
           DoNotText,
           GCLID,
           LeadStatus,
           dl.IsDeleted,
           dl.LeadCreateDateest,
           LastModifiedDate,
           OriginalCampaignSource,
           dl.City,
           dl.State,
           LeadPostalCode,
           LeadSource,
           LeadEmail,
           LeadPhone,
           LeadMobilePhone,
           Isvalid,
           ExternalID,
           LeadCreateDateEst,
           ConvertedContactId,
           dc.SourceCode,
           dl.LeadAddress,
           1 as new,
           ConvertedAccountId,
           dl.CreateUser,
           dl.UpdateUser
    from HC_BI_SFDC.synapse_pool.FactLeadTracking dl
             left join HC_BI_SFDC.Synapse_pool.DimCampaign dc on dl.OriginalCampaignKey = dc.CampaignKey
    where convert(date, dl.LeadCreateDateEst) > '2021-06-15'
      and month(dl.LeadCreateDateEst) <= month(dateadd(month, -1, dateadd(day, -1, getdate())))
    union all
    select Id,
           CenterNumber__c,
           FirstName,
           LastName,
           Birthday__c,
           Gender__c,
           Language__c,
           Ethnicity__c,
           MaritalStatus__c,
           Occupation__c,
           NorwoodScale__c,
           LudwigScale__c,
           HairLossFamily__c,
           HairLossProductUsed__c,
           HairLossSpot__c,
           OriginalCampaignID__c,
           DoNotContact__c,
           DoNotCall,
           DoNotEmail__c,
           DoNotMail__c,
           DoNotText__c,
           GCLID__c,
           Status,
           IsDeleted,
           CreatedDate,
           LastModifiedDate,
           RecentSourceCode__c,
           City,
           State,
           PostalCode,
           LeadSource,
           Email,
           Phone,
           MobilePhone,
           isValid,
           externalID,
           CreatedDateEst,
           ConvertedContactId,
           Source_Code_Legacy__c,
           Street,
           IsNew,
           ConvertedAccountId,
           CreatedById,
           LastModifiedById
    from HC_BI_SFDC.dbo.Lead dl
    where month(convert(date, dl.CreatedDate)) = month(dateadd(day, -1, getdate()))
      and year(convert(date, dl.CreatedDateEst)) = year(dateadd(day, -1, getdate()))
)
select Id,
       CenterNumber__c,
       FirstName,
       LastName,
       Birthday__c,
       Gender__c,
       Language__c,
       Ethnicity__c,
       MaritalStatus__c,
       Occupation__c,
       NorwoodScale__c,
       LudwigScale__c,
       HairLossFamily__c,
       HairLossProductUsed__c,
       HairLossSpot__c,
       OriginalCampaignID__c,
       DoNotContact__c,
       DoNotCall,
       DoNotEmail__c,
       DoNotMail__c,
       DoNotText__c,
       GCLID__c,
       Status,
       IsDeleted,
       CreatedDate,
       LastModifiedDate,
       RecentSourceCode__c,
       City,
       State,
       PostalCode,
       LeadSource,
       Email,
       Phone,
       MobilePhone,
       isValid,
       externalID,
       CreatedDateEst,
       ConvertedContactId,
       Source_Code_Legacy__c,
       Street,
       IsNew,
       ConvertedAccountId,
       CreatedById,
       LastModifiedById
from vwdimLead_CTE
GO
