/* CreateDate: 10/01/2018 08:53:16.853 , ModifyDate: 10/01/2018 08:53:16.853 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[bbtransdata](
	[bbacctid] [int] NOT NULL,
	[bbbatchid] [int] NOT NULL,
	[bbmerchid] [int] NOT NULL,
	[merchbatch] [int] NOT NULL,
	[merchseq] [int] NOT NULL,
	[status] [int] NOT NULL,
	[submit_ts] [bigint] NOT NULL,
	[trantype] [bigint] NOT NULL,
	[cardtype] [int] NOT NULL,
	[tranflags] [bigint] NOT NULL,
	[authts] [bigint] NOT NULL,
	[capturets] [bigint] NOT NULL,
	[account] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[expdate] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[amount] [bigint] NOT NULL,
	[authamount] [bigint] NOT NULL,
	[origauthamount] [bigint] NOT NULL,
	[examount] [bigint] NOT NULL,
	[tax] [bigint] NOT NULL,
	[cashbackamount] [bigint] NOT NULL,
	[currency] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[zip] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ordernum] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ttid] [bigint] NOT NULL,
	[custref] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[shipzip] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[shipcountry] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[discountamount] [bigint] NOT NULL,
	[freightamount] [bigint] NOT NULL,
	[dutyamount] [bigint] NOT NULL,
	[l3num] [int] NOT NULL,
	[divisionnum] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[descmerch] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[descloc] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[installment_num] [int] NOT NULL,
	[installment_total] [int] NOT NULL,
	[bdate] [bigint] NOT NULL,
	[edate] [bigint] NOT NULL,
	[rate] [bigint] NOT NULL,
	[excharge] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[apcode] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[authsource] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[avsresp] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[cardlevel] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[commind] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[cvresp] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[icc] [varchar](2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[netident] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[posdata] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[proccode] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[raci] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[rrefnum] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[settledate] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[sqi] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[stan] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[trandate] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[transid] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[trantime] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[valcode] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED
(
	[bbbatchid] ASC,
	[bbmerchid] ASC,
	[merchbatch] ASC,
	[merchseq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
