/* CreateDate: 09/30/2019 07:07:33.023 , ModifyDate: 09/30/2019 07:07:33.027 */
GO
CREATE TABLE [dbo].[push_events](
	[id] [bigint] NOT NULL,
	[endpoint_id] [bigint] NOT NULL,
	[ts] [bigint] NOT NULL,
	[data] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [i_push_events_endpoint] ON [dbo].[push_events]
(
	[endpoint_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
