/* CreateDate: 05/05/2020 17:42:41.380 , ModifyDate: 05/31/2020 14:27:43.107 */
GO
CREATE TABLE [dbo].[cfgConfigurationCenter](
	[ConfigurationCenterID] [int] NOT NULL,
	[ConfigurationCenterSortOrder] [int] NULL,
	[CenterID] [int] NOT NULL,
	[CreateDate] [datetime] NULL,
	[CreateUser] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastUpdate] [datetime] NULL,
	[LastUpdateUser] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UpdateStamp] [timestamp] NULL,
	[UseCreditCardProcessorFlag] [bit] NOT NULL,
	[AccountingExportFreightBaseRate] [money] NOT NULL,
	[AccountingExportFreightPerItemRate] [money] NOT NULL,
	[AccountingExportReceiveAPDebitGLNumber] [int] NULL,
	[FeeNotificationDays] [int] NOT NULL,
	[IsFeeProcessedCentrallyFlag] [bit] NOT NULL,
	[LastClientEFTUpdate] [datetime] NULL,
	[CenterBusinessTypeID] [int] NOT NULL,
	[HasFullAccess] [bit] NOT NULL,
	[EndOfDayLastRunDate] [datetime] NULL,
	[IsSalesConsultationEnabled] [bit] NOT NULL,
	[IsSalesOrderRoundingEnabled] [bit] NOT NULL,
	[IsScheduleFeatureEnabled] [bit] NOT NULL,
	[IsFulfillmentEnabled] [bit] NOT NULL,
	[IsEnhSalesConsultEnabled] [bit] NOT NULL,
	[IsAutoConfirmEnabled] [bit] NOT NULL,
	[IsNoteDeletionEnabled] [bit] NOT NULL,
	[NACHAFileProfileID] [int] NULL,
	[IsNewClientEnabled] [bit] NOT NULL,
	[LanguageID] [int] NULL,
	[EntityID] [int] NOT NULL,
	[IsAutomatedAgreementEnabled] [bit] NOT NULL,
	[IsAccountReceivableProcEnabled] [bit] NOT NULL,
	[HairOrderDelayDays] [int] NOT NULL,
	[IsActiveForVipAccess] [bit] NOT NULL,
	[UseCreditCardProcessorForCreditCardOnFile] [bit] NOT NULL,
	[NewBusinessSizeID] [int] NULL,
	[RecurringBusinessSizeID] [int] NULL,
	[IsTrichoViewEnabledForMobile] [bit] NOT NULL,
	[IsSalesConsultationEnabledForMobile] [bit] NOT NULL,
	[IsLiveWithBosley] [bit] NOT NULL,
	[CanCompleteVisitNextDay] [bit] NOT NULL,
	[IsNonSerializedInventoryEnabled] [bit] NOT NULL,
	[NewClientMembershipID] [int] NULL,
	[IncludeInNationalPricingRenewal] [bit] NOT NULL,
	[IsTransferToHWEnabled] [bit] NOT NULL,
	[IsConfirmAppointmentClientContactInformationEnabled] [bit] NOT NULL,
	[IsStylistCareerPathEnabled] [bit] NOT NULL,
	[IsHWIntegrationEnabled] [bit] NULL,
 CONSTRAINT [PK_cfgConfigurationCenter] PRIMARY KEY CLUSTERED
(
	[ConfigurationCenterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG_CDC]
) ON [FG_CDC]
GO
