/* CreateDate: 04/08/2015 13:53:53.537 , ModifyDate: 03/01/2017 08:26:13.057 */
GO
CREATE TABLE [dbo].[datTechnicalProfileHistory](
	[TechnicalProfileHistoryGUID] [uniqueidentifier] NOT NULL,
	[TechnicalProfileDate] [datetime] NULL,
	[EmployeeGUID] [uniqueidentifier] NULL,
	[SalesOrderGUID] [uniqueidentifier] NULL,
	[ClientGUID] [uniqueidentifier] NOT NULL,
	[HairSystemID] [int] NULL,
	[AdhesiveFrontID] [int] NULL,
	[AdhesiveFront2ID] [int] NULL,
	[AdhesivePerimeterID] [int] NULL,
	[AdhesivePerimeter2ID] [int] NULL,
	[AdhesivePerimeter3ID] [int] NULL,
	[RemovalProcessID] [int] NULL,
	[AdhesiveSolventID] [int] NULL,
	[ServiceVisitDurationID] [int] NULL,
	[RelaxerBrandID] [int] NULL,
	[RelaxerStrengthID] [int] NULL,
	[RelaxerProcessingTime] [int] NULL,
	[RelaxerProcessingTimeUnitID] [int] NULL,
	[ColorBrandID] [int] NULL,
	[ColorFormula] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ColorFormulaSizeID] [int] NULL,
	[ColorFormula2] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ColorFormulaSize2ID] [int] NULL,
	[ColorFormula3] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ColorFormulaSize3ID] [int] NULL,
	[DeveloperSizeID] [int] NULL,
	[DeveloperVolumeID] [int] NULL,
	[ColorProcessingTime] [int] NULL,
	[ColorProcessingTimeUnitID] [int] NULL,
	[PermBrandID] [int] NULL,
	[PermBrandSystemID] [int] NULL,
	[PermRodColorID] [int] NULL,
	[PermRodColorSystemID] [int] NULL,
	[PermRodColor2ID] [int] NULL,
	[PermRodColor2SystemID] [int] NULL,
	[PermProcessingTime] [int] NULL,
	[PermProcessingTimeUnitID] [int] NULL,
	[PermProcessingTimeSystem] [int] NULL,
	[PermProcessingTimeUnitSystemID] [int] NULL,
	[PermTechniqueID] [int] NULL,
	[PermTechniqueSystemID] [int] NULL,
	[ClientUsingOwnHairline] [bit] NULL,
	[DistanceHairlineToNose] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceVisitDurationApp] [int] NULL,
	[ServiceVisitDurationAppTimeUnitID] [int] NULL,
	[ServiceVisitDurationFull] [int] NULL,
	[ServiceVisitDurationFullTimeUnitID] [int] NULL,
	[ServiceVisitDurationOther] [int] NULL,
	[ServiceVisitDurationOtherTimeUnitID] [int] NULL,
	[Notes] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreateDate] [datetime] NULL,
	[CreateUser] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastUpdate] [datetime] NULL,
	[LastUpdateUser] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UpdateStamp] [timestamp] NULL,
	[LastTemplateDate] [datetime] NULL,
 CONSTRAINT [PK_datTechnicalProfileHistory] PRIMARY KEY CLUSTERED
(
	[TechnicalProfileHistoryGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG_CDC]
) ON [FG_CDC]
GO
