/* CreateDate: 03/23/2022 09:36:20.020 , ModifyDate: 03/23/2022 09:36:20.020 */
GO
Create view vw_SDFC_Lead as
SELECT [Id] as [cst_sfdc_lead_id]
      ,[ContactID__c] as [contact_id]
      ,[CreatedDate] as [create_date]
      ,[LastModifiedDate] as [updated_date]
      ,null as [BatchID]
      ,[CenterID__c] as [CenterID]
      ,[FirstName]
      ,[LastName]
      ,null as [Salutation]
      ,[Gender__c] as [Gender]
      ,[Language__c] as [Language]
      ,[Age__c] as [Age]
      ,[AgeRange__c] as [AgeRange]
      ,[Birthday__c] as [Birthday]
      ,[HairLossExperience__c] as [HairLossExperience]
      ,[HairLossProductOther__c] as [HairLossProductOther]
      ,[HairLossSpot__c] as [HairLossSpot]
      ,[HairLossFamily__c] as [HairLossFamily]
      ,[HairLossProductUsed__c] as [HairLossProductUsed]
      ,[Promo_Code_Legacy__c] as [PromoCode]
      ,[Source_Code_Legacy__c] as [SourceCode]
      ,[SiebelID__c] as [SiebelID]
      ,null as [SessionID]
      ,[OnCAffiliateID__c] as [AffiliateID]
      ,null as [Suffix]
      ,null as [Accommodation]
      ,[Street]
      ,[City]
      ,[PostalCode]
      ,[StateCode]
      ,[CountryCode]
      ,[Phone]
      ,[Email]
      ,[ContactStatus__c] as [ContactStatus]
      ,[DoNotMail__c] as [DoNotMail]
      ,[DoNotText__c] as [DoNotText]
      ,[DoNotCall]
      ,[DoNotEmail__c] as [DoNotEmail]
      ,[CreatedDate] as [LeadCreateDate]
      ,[CreatedById] as [LeadCreateUser]
      ,[LastModifiedDate] as [LeadLastUpdate]
      ,[LastModifiedById] as [LeadLastUpdateUser]
      ,null as [IsReprocessFlag]
      ,null as [IsProcessedFlag]
      ,[CreatedDate]
      ,[CreatedById]
      ,[LastModifiedDate]
      ,[LastModifiedById]
  FROM [HC_BI_SFDC].[dbo].[Lead]
GO
