create procedure [sp_MSins_bi_cms_ddsFactHairSystemOrder]
    @c1 int,
    @c2 uniqueidentifier,
    @c3 int,
    @c4 int,
    @c5 datetime,
    @c6 int,
    @c7 datetime,
    @c8 int,
    @c9 datetime,
    @c10 int,
    @c11 datetime,
    @c12 int,
    @c13 datetime,
    @c14 int,
    @c15 datetime,
    @c16 int,
    @c17 int,
    @c18 int,
    @c19 uniqueidentifier,
    @c20 uniqueidentifier,
    @c21 int,
    @c22 int,
    @c23 int,
    @c24 int,
    @c25 int,
    @c26 int,
    @c27 int,
    @c28 int,
    @c29 int,
    @c30 int,
    @c31 int,
    @c32 int,
    @c33 decimal(10,4),
    @c34 decimal(10,4),
    @c35 decimal(21,6),
    @c36 int,
    @c37 nvarchar(50),
    @c38 int,
    @c39 decimal(21,6),
    @c40 decimal(21,6),
    @c41 decimal(21,6),
    @c42 int,
    @c43 varchar(50),
    @c44 int,
    @c45 varchar(50),
    @c46 bit,
    @c47 int,
    @c48 int,
    @c49 int,
    @c50 int,
    @c51 int,
    @c52 int,
    @c53 int,
    @c54 uniqueidentifier,
    @c55 int
as
begin
	insert into [bi_cms_dds].[FactHairSystemOrder] (
		[HairSystemOrderKey],
		[HairSystemOrderSSID],
		[HairSystemOrderNumber],
		[HairSystemOrderDateKey],
		[HairSystemOrderDate],
		[HairSystemDueDateKey],
		[HairSystemDueDate],
		[HairSystemAllocationDateKey],
		[HairSystemAlocationDate],
		[HairSystemReceivedDateKey],
		[HairSystemReceivedDate],
		[HairSystemShippedDateKey],
		[HairSystemShippedDate],
		[HairSystemAppliedDateKey],
		[HairSystemAppliedDate],
		[CenterKey],
		[ClientKey],
		[ClientMembershipKey],
		[OrigClientSSID],
		[OrigClientMembershipSSID],
		[HairSystemHairLengthKey],
		[HairSystemTypeKey],
		[HairSystemTextureKey],
		[HairSystemMatrixColorKey],
		[HairSystemDensityKey],
		[HairSystemFrontalDensityKey],
		[HairSystemStyleKey],
		[HairSystemDesignTemplateKey],
		[HairSystemRecessionKey],
		[HairSystemTopHairColorKey],
		[MeasurementsByEmployeeKey],
		[CapSizeKey],
		[TemplateWidth],
		[TemplateHeight],
		[TemplateArea],
		[HairSystemVendorContractKey],
		[FactorySSID],
		[HairSystemOrderStatusKey],
		[CostContract],
		[CostActual],
		[PriceContract],
		[HairSystemRepairReasonSSID],
		[HairSystemRepairReasonDescription],
		[HairSystemRedoReasonSSID],
		[HairSystemRedoReasonDescription],
		[IsOnHoldForReviewFlag],
		[IsSampleOrderFlag],
		[IsRepairOrderFlag],
		[IsRedoOrderFlag],
		[IsRushOrderFlag],
		[IsStockInventoryFlag],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[ClientHomeCenterKey]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40,
		@c41,
		@c42,
		@c43,
		@c44,
		@c45,
		@c46,
		@c47,
		@c48,
		@c49,
		@c50,
		@c51,
		@c52,
		@c53,
		default,
		@c54,
		@c55	)
end
