create procedure [sp_MSins_bi_cms_ddsDimSalesCode]
    @c1 int,
    @c2 int,
    @c3 nvarchar(50),
    @c4 nvarchar(15),
    @c5 int,
    @c6 nvarchar(50),
    @c7 nvarchar(10),
    @c8 int,
    @c9 nvarchar(50),
    @c10 nvarchar(10),
    @c11 int,
    @c12 int,
    @c13 nvarchar(25),
    @c14 money,
    @c15 int,
    @c16 int,
    @c17 tinyint,
    @c18 datetime,
    @c19 datetime,
    @c20 varchar(200),
    @c21 tinyint,
    @c22 int,
    @c23 int,
    @c24 uniqueidentifier,
    @c25 int
as
begin
	insert into [bi_cms_dds].[DimSalesCode] (
		[SalesCodeKey],
		[SalesCodeSSID],
		[SalesCodeDescription],
		[SalesCodeDescriptionShort],
		[SalesCodeTypeSSID],
		[SalesCodeTypeDescription],
		[SalesCodeTypeDescriptionShort],
		[ProductVendorSSID],
		[ProductVendorDescription],
		[ProductVendorDescriptionShort],
		[SalesCodeDepartmentKey],
		[SalesCodeDepartmentSSID],
		[Barcode],
		[PriceDefault],
		[GLNumber],
		[ServiceDuration],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[SalesCodeSortOrder]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		default,
		@c24,
		@c25	)
end
