/* CreateDate: 10/03/2019 23:03:40.867 , ModifyDate: 10/03/2019 23:03:40.867 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [sp_MSins_bi_cms_ddsDimHairSystemOrderStatus]
    @c1 int,
    @c2 nvarchar(50),
    @c3 int,
    @c4 nvarchar(50),
    @c5 nvarchar(10),
    @c6 nchar(1),
    @c7 nchar(1),
    @c8 nchar(1),
    @c9 nchar(1),
    @c10 nchar(1),
    @c11 nchar(1),
    @c12 nchar(1),
    @c13 nchar(1),
    @c14 nchar(1),
    @c15 nchar(1),
    @c16 nchar(1),
    @c17 nchar(1),
    @c18 nchar(1),
    @c19 tinyint,
    @c20 datetime,
    @c21 datetime,
    @c22 varchar(200),
    @c23 tinyint,
    @c24 int,
    @c25 int,
    @c26 uniqueidentifier
as
begin
	insert into [bi_cms_dds].[DimHairSystemOrderStatus] (
		[HairSystemOrderStatusKey],
		[HairSystemOrderStatusSSID],
		[HairSystemOrderStatusSortOrder],
		[HairSystemOrderStatusDescription],
		[HairSystemOrderStatusDescriptionShort],
		[CanApplyFlag],
		[CanTransferFlag],
		[CanEditFlag],
		[IsActiveFlag],
		[CanCancelFlag],
		[IsPreallocationFlag],
		[CanRedoFlag],
		[CanRepairFlag],
		[ShowInHistoryFlag],
		[CanAddToStockFlag],
		[IncludeInMembershipCountFlag],
		[CanRequestCreditFlag],
		[Active],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		default,
		@c26	)
end
GO
