create procedure [sp_MSins_bi_cms_ddsDimSalesOrder]
    @c1 int,
    @c2 uniqueidentifier,
    @c3 int,
    @c4 int,
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 int,
    @c12 uniqueidentifier,
    @c13 int,
    @c14 uniqueidentifier,
    @c15 datetime,
    @c16 nvarchar(50),
    @c17 bit,
    @c18 bit,
    @c19 bit,
    @c20 int,
    @c21 uniqueidentifier,
    @c22 nvarchar(15),
    @c23 bit,
    @c24 bit,
    @c25 int,
    @c26 uniqueidentifier,
    @c27 tinyint,
    @c28 datetime,
    @c29 datetime,
    @c30 varchar(200),
    @c31 tinyint,
    @c32 int,
    @c33 int,
    @c34 uniqueidentifier,
    @c35 bit,
    @c36 bit,
    @c37 int
as
begin
	insert into [bi_cms_dds].[DimSalesOrder] (
		[SalesOrderKey],
		[SalesOrderSSID],
		[TenderTransactionNumber_Temp],
		[TicketNumber_Temp],
		[CenterKey],
		[CenterSSID],
		[ClientHomeCenterKey],
		[ClientHomeCenterSSID],
		[SalesOrderTypeKey],
		[SalesOrderTypeSSID],
		[ClientKey],
		[ClientSSID],
		[ClientMembershipKey],
		[ClientMembershipSSID],
		[OrderDate],
		[InvoiceNumber],
		[IsTaxExemptFlag],
		[IsVoidedFlag],
		[IsClosedFlag],
		[EmployeeKey],
		[EmployeeSSID],
		[FulfillmentNumber],
		[IsWrittenOffFlag],
		[IsRefundedFlag],
		[RefundedSalesOrderKey],
		[RefundedSalesOrderSSID],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[IsSurgeryReversalFlag],
		[IsGuaranteeFlag],
		[IncomingRequestID]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		default,
		@c34,
		@c35,
		@c36,
		@c37	)
end
