/* CreateDate: 10/03/2019 23:03:42.450 , ModifyDate: 10/03/2019 23:03:42.450 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[sp_MSupd_bi_cms_ddsFactSalesTransaction]
		@c1 int = NULL,
		@c2 int = NULL,
		@c3 int = NULL,
		@c4 int = NULL,
		@c5 int = NULL,
		@c6 int = NULL,
		@c7 int = NULL,
		@c8 int = NULL,
		@c9 int = NULL,
		@c10 int = NULL,
		@c11 int = NULL,
		@c12 int = NULL,
		@c13 int = NULL,
		@c14 int = NULL,
		@c15 money = NULL,
		@c16 money = NULL,
		@c17 money = NULL,
		@c18 money = NULL,
		@c19 money = NULL,
		@c20 money = NULL,
		@c21 int = NULL,
		@c22 int = NULL,
		@c23 binary(8) = NULL,
		@c24 uniqueidentifier = NULL,
		@c25 tinyint = NULL,
		@c26 tinyint = NULL,
		@c27 int = NULL,
		@c28 int = NULL,
		@c29 int = NULL,
		@c30 int = NULL,
		@c31 int = NULL,
		@c32 int = NULL,
		@c33 int = NULL,
		@c34 int = NULL,
		@c35 int = NULL,
		@c36 int = NULL,
		@c37 int = NULL,
		@c38 int = NULL,
		@c39 money = NULL,
		@c40 money = NULL,
		@c41 int = NULL,
		@c42 float = NULL,
		@c43 int = NULL,
		@c44 money = NULL,
		@c45 money = NULL,
		@c46 int = NULL,
		@c47 float = NULL,
		@c48 int = NULL,
		@c49 money = NULL,
		@c50 int = NULL,
		@c51 money = NULL,
		@c52 int = NULL,
		@c53 int = NULL,
		@c54 money = NULL,
		@c55 int = NULL,
		@c56 int = NULL,
		@c57 money = NULL,
		@c58 int = NULL,
		@c59 money = NULL,
		@c60 int = NULL,
		@c61 money = NULL,
		@c62 int = NULL,
		@c63 int = NULL,
		@c64 int = NULL,
		@c65 money = NULL,
		@c66 money = NULL,
		@c67 money = NULL,
		@c68 money = NULL,
		@c69 money = NULL,
		@c70 money = NULL,
		@c71 money = NULL,
		@c72 int = NULL,
		@c73 money = NULL,
		@c74 int = NULL,
		@c75 int = NULL,
		@c76 money = NULL,
		@c77 int = NULL,
		@c78 int = NULL,
		@c79 int = NULL,
		@c80 int = NULL,
		@c81 money = NULL,
		@c82 int = NULL,
		@c83 int = NULL,
		@c84 money = NULL,
		@c85 varchar(10) = NULL,
		@c86 money = NULL,
		@c87 int = NULL,
		@c88 money = NULL,
		@c89 money = NULL,
		@c90 int = NULL,
		@c91 money = NULL,
		@c92 int = NULL,
		@c93 money = NULL,
		@c94 int = NULL,
		@c95 int = NULL,
		@c96 money = NULL,
		@c97 int = NULL,
		@c98 money = NULL,
		@c99 int = NULL,
		@c100 money = NULL,
		@c101 money = NULL,
		@c102 int = NULL,
		@c103 money = NULL,
		@c104 int = NULL,
		@c105 money = NULL,
		@pkc1 int = NULL,
		@pkc2 int = NULL,
		@pkc3 int = NULL,
		@bitmap binary(14)
as
begin
	declare @primarykey_text nvarchar(100) = ''
if (substring(@bitmap,1,1) & 1 = 1) or
 (substring(@bitmap,1,1) & 2 = 2) or
 (substring(@bitmap,1,1) & 4 = 4)
begin
update [bi_cms_dds].[FactSalesTransaction] set
		[OrderDateKey] = case substring(@bitmap,1,1) & 1 when 1 then @c1 else [OrderDateKey] end,
		[SalesOrderKey] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [SalesOrderKey] end,
		[SalesOrderDetailKey] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [SalesOrderDetailKey] end,
		[SalesOrderTypeKey] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [SalesOrderTypeKey] end,
		[CenterKey] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [CenterKey] end,
		[ClientKey] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [ClientKey] end,
		[MembershipKey] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [MembershipKey] end,
		[ClientMembershipKey] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [ClientMembershipKey] end,
		[SalesCodeKey] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [SalesCodeKey] end,
		[Employee1Key] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Employee1Key] end,
		[Employee2Key] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [Employee2Key] end,
		[Employee3Key] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [Employee3Key] end,
		[Employee4Key] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [Employee4Key] end,
		[Quantity] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Quantity] end,
		[Price] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Price] end,
		[Discount] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Discount] end,
		[Tax1] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [Tax1] end,
		[Tax2] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [Tax2] end,
		[TaxRate1] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [TaxRate1] end,
		[TaxRate2] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [TaxRate2] end,
		[InsertAuditKey] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [InsertAuditKey] end,
		[UpdateAuditKey] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [UpdateAuditKey] end,
		[RowTimeStamp] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [RowTimeStamp] end,
		[msrepl_tran_version] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [msrepl_tran_version] end,
		[IsClosed] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [IsClosed] end,
		[IsVoided] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [IsVoided] end,
		[ContactKey] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [ContactKey] end,
		[SourceKey] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [SourceKey] end,
		[GenderKey] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [GenderKey] end,
		[OccupationKey] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [OccupationKey] end,
		[EthnicityKey] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [EthnicityKey] end,
		[MaritalStatusKey] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [MaritalStatusKey] end,
		[HairLossTypeKey] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [HairLossTypeKey] end,
		[AgeRangeKey] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [AgeRangeKey] end,
		[PromotionCodeKey] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [PromotionCodeKey] end,
		[S1_SaleCnt] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [S1_SaleCnt] end,
		[S_CancelCnt] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [S_CancelCnt] end,
		[S1_NetSalesCnt] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [S1_NetSalesCnt] end,
		[S1_NetSalesAmt] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [S1_NetSalesAmt] end,
		[S1_ContractAmountAmt] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [S1_ContractAmountAmt] end,
		[S1_EstGraftsCnt] = case substring(@bitmap,6,1) & 1 when 1 then @c41 else [S1_EstGraftsCnt] end,
		[S1_EstPerGraftsAmt] = case substring(@bitmap,6,1) & 2 when 2 then @c42 else [S1_EstPerGraftsAmt] end,
		[SA_NetSalesCnt] = case substring(@bitmap,6,1) & 4 when 4 then @c43 else [SA_NetSalesCnt] end,
		[SA_NetSalesAmt] = case substring(@bitmap,6,1) & 8 when 8 then @c44 else [SA_NetSalesAmt] end,
		[SA_ContractAmountAmt] = case substring(@bitmap,6,1) & 16 when 16 then @c45 else [SA_ContractAmountAmt] end,
		[SA_EstGraftsCnt] = case substring(@bitmap,6,1) & 32 when 32 then @c46 else [SA_EstGraftsCnt] end,
		[SA_EstPerGraftAmt] = case substring(@bitmap,6,1) & 64 when 64 then @c47 else [SA_EstPerGraftAmt] end,
		[S_PostExtCnt] = case substring(@bitmap,6,1) & 128 when 128 then @c48 else [S_PostExtCnt] end,
		[S_PostExtAmt] = case substring(@bitmap,7,1) & 1 when 1 then @c49 else [S_PostExtAmt] end,
		[S_SurgeryPerformedCnt] = case substring(@bitmap,7,1) & 2 when 2 then @c50 else [S_SurgeryPerformedCnt] end,
		[S_SurgeryPerformedAmt] = case substring(@bitmap,7,1) & 4 when 4 then @c51 else [S_SurgeryPerformedAmt] end,
		[S_SurgeryGraftsCnt] = case substring(@bitmap,7,1) & 8 when 8 then @c52 else [S_SurgeryGraftsCnt] end,
		[S1_DepositsTakenCnt] = case substring(@bitmap,7,1) & 16 when 16 then @c53 else [S1_DepositsTakenCnt] end,
		[S1_DepositsTakenAmt] = case substring(@bitmap,7,1) & 32 when 32 then @c54 else [S1_DepositsTakenAmt] end,
		[NB_GrossNB1Cnt] = case substring(@bitmap,7,1) & 64 when 64 then @c55 else [NB_GrossNB1Cnt] end,
		[NB_TradCnt] = case substring(@bitmap,7,1) & 128 when 128 then @c56 else [NB_TradCnt] end,
		[NB_TradAmt] = case substring(@bitmap,8,1) & 1 when 1 then @c57 else [NB_TradAmt] end,
		[NB_GradCnt] = case substring(@bitmap,8,1) & 2 when 2 then @c58 else [NB_GradCnt] end,
		[NB_GradAmt] = case substring(@bitmap,8,1) & 4 when 4 then @c59 else [NB_GradAmt] end,
		[NB_ExtCnt] = case substring(@bitmap,8,1) & 8 when 8 then @c60 else [NB_ExtCnt] end,
		[NB_ExtAmt] = case substring(@bitmap,8,1) & 16 when 16 then @c61 else [NB_ExtAmt] end,
		[NB_AppsCnt] = case substring(@bitmap,8,1) & 32 when 32 then @c62 else [NB_AppsCnt] end,
		[NB_BIOConvCnt] = case substring(@bitmap,8,1) & 64 when 64 then @c63 else [NB_BIOConvCnt] end,
		[NB_EXTConvCnt] = case substring(@bitmap,8,1) & 128 when 128 then @c64 else [NB_EXTConvCnt] end,
		[PCP_NB2Amt] = case substring(@bitmap,9,1) & 1 when 1 then @c65 else [PCP_NB2Amt] end,
		[PCP_PCPAmt] = case substring(@bitmap,9,1) & 2 when 2 then @c66 else [PCP_PCPAmt] end,
		[PCP_BioAmt] = case substring(@bitmap,9,1) & 4 when 4 then @c67 else [PCP_BioAmt] end,
		[PCP_ExtMemAmt] = case substring(@bitmap,9,1) & 8 when 8 then @c68 else [PCP_ExtMemAmt] end,
		[PCPNonPgmAmt] = case substring(@bitmap,9,1) & 16 when 16 then @c69 else [PCPNonPgmAmt] end,
		[ServiceAmt] = case substring(@bitmap,9,1) & 32 when 32 then @c70 else [ServiceAmt] end,
		[RetailAmt] = case substring(@bitmap,9,1) & 64 when 64 then @c71 else [RetailAmt] end,
		[ClientServicedCnt] = case substring(@bitmap,9,1) & 128 when 128 then @c72 else [ClientServicedCnt] end,
		[NetMembershipAmt] = case substring(@bitmap,10,1) & 1 when 1 then @c73 else [NetMembershipAmt] end,
		[S_GrossSurCnt] = case substring(@bitmap,10,1) & 2 when 2 then @c74 else [S_GrossSurCnt] end,
		[S_SurCnt] = case substring(@bitmap,10,1) & 4 when 4 then @c75 else [S_SurCnt] end,
		[S_SurAmt] = case substring(@bitmap,10,1) & 8 when 8 then @c76 else [S_SurAmt] end,
		[AccountID] = case substring(@bitmap,10,1) & 16 when 16 then @c77 else [AccountID] end,
		[PCP_UpgCnt] = case substring(@bitmap,10,1) & 32 when 32 then @c78 else [PCP_UpgCnt] end,
		[PCP_DwnCnt] = case substring(@bitmap,10,1) & 64 when 64 then @c79 else [PCP_DwnCnt] end,
		[NB_RemCnt] = case substring(@bitmap,10,1) & 128 when 128 then @c80 else [NB_RemCnt] end,
		[NB_XTRAmt] = case substring(@bitmap,11,1) & 1 when 1 then @c81 else [NB_XTRAmt] end,
		[NB_XTRCnt] = case substring(@bitmap,11,1) & 2 when 2 then @c82 else [NB_XTRCnt] end,
		[NB_XTRConvCnt] = case substring(@bitmap,11,1) & 4 when 4 then @c83 else [NB_XTRConvCnt] end,
		[PCP_XtrAmt] = case substring(@bitmap,11,1) & 8 when 8 then @c84 else [PCP_XtrAmt] end,
		[MbrPromotion] = case substring(@bitmap,11,1) & 16 when 16 then @c85 else [MbrPromotion] end,
		[NetSalesAmt] = case substring(@bitmap,11,1) & 32 when 32 then @c86 else [NetSalesAmt] end,
		[S_PRPCnt] = case substring(@bitmap,11,1) & 64 when 64 then @c87 else [S_PRPCnt] end,
		[S_PRPAmt] = case substring(@bitmap,11,1) & 128 when 128 then @c88 else [S_PRPAmt] end,
		[LaserAmt] = case substring(@bitmap,12,1) & 1 when 1 then @c89 else [LaserAmt] end,
		[S_StripCnt] = case substring(@bitmap,12,1) & 2 when 2 then @c90 else [S_StripCnt] end,
		[S_StripAmt] = case substring(@bitmap,12,1) & 4 when 4 then @c91 else [S_StripAmt] end,
		[S_ArtasCnt] = case substring(@bitmap,12,1) & 8 when 8 then @c92 else [S_ArtasCnt] end,
		[S_ArtasAmt] = case substring(@bitmap,12,1) & 16 when 16 then @c93 else [S_ArtasAmt] end,
		[LaserCnt] = case substring(@bitmap,12,1) & 32 when 32 then @c94 else [LaserCnt] end,
		[NB_MDPCnt] = case substring(@bitmap,12,1) & 64 when 64 then @c95 else [NB_MDPCnt] end,
		[NB_MDPAmt] = case substring(@bitmap,12,1) & 128 when 128 then @c96 else [NB_MDPAmt] end,
		[NB_LaserCnt] = case substring(@bitmap,13,1) & 1 when 1 then @c97 else [NB_LaserCnt] end,
		[NB_LaserAmt] = case substring(@bitmap,13,1) & 2 when 2 then @c98 else [NB_LaserAmt] end,
		[PCP_LaserCnt] = case substring(@bitmap,13,1) & 4 when 4 then @c99 else [PCP_LaserCnt] end,
		[PCP_LaserAmt] = case substring(@bitmap,13,1) & 8 when 8 then @c100 else [PCP_LaserAmt] end,
		[EMP_RetailAmt] = case substring(@bitmap,13,1) & 16 when 16 then @c101 else [EMP_RetailAmt] end,
		[EMP_NB_LaserCnt] = case substring(@bitmap,13,1) & 32 when 32 then @c102 else [EMP_NB_LaserCnt] end,
		[EMP_NB_LaserAmt] = case substring(@bitmap,13,1) & 64 when 64 then @c103 else [EMP_NB_LaserAmt] end,
		[EMP_PCP_LaserCnt] = case substring(@bitmap,13,1) & 128 when 128 then @c104 else [EMP_PCP_LaserCnt] end,
		[EMP_PCP_LaserAmt] = case substring(@bitmap,14,1) & 1 when 1 then @c105 else [EMP_PCP_LaserAmt] end
	where [OrderDateKey] = @pkc1
  and [SalesOrderKey] = @pkc2
  and [SalesOrderDetailKey] = @pkc3
if @@rowcount = 0
    if @@microsoftversion>0x07320000
		Begin
			if exists (Select * from sys.all_parameters where object_id = OBJECT_ID('sp_MSreplraiserror') and [name] = '@param3')
			Begin

				set @primarykey_text = @primarykey_text + '[OrderDateKey] = ' + convert(nvarchar(100),@pkc1,1) + ', '
				set @primarykey_text = @primarykey_text + '[SalesOrderKey] = ' + convert(nvarchar(100),@pkc2,1) + ', '
				set @primarykey_text = @primarykey_text + '[SalesOrderDetailKey] = ' + convert(nvarchar(100),@pkc3,1)
				exec sp_MSreplraiserror @errorid=20598, @param1=N'[bi_cms_dds].[FactSalesTransaction]', @param2=@primarykey_text, @param3=13233
			End
			Else
				exec sp_MSreplraiserror @errorid=20598
		End
end
else
begin
update [bi_cms_dds].[FactSalesTransaction] set
		[SalesOrderTypeKey] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [SalesOrderTypeKey] end,
		[CenterKey] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [CenterKey] end,
		[ClientKey] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [ClientKey] end,
		[MembershipKey] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [MembershipKey] end,
		[ClientMembershipKey] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [ClientMembershipKey] end,
		[SalesCodeKey] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [SalesCodeKey] end,
		[Employee1Key] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Employee1Key] end,
		[Employee2Key] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [Employee2Key] end,
		[Employee3Key] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [Employee3Key] end,
		[Employee4Key] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [Employee4Key] end,
		[Quantity] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Quantity] end,
		[Price] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Price] end,
		[Discount] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Discount] end,
		[Tax1] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [Tax1] end,
		[Tax2] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [Tax2] end,
		[TaxRate1] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [TaxRate1] end,
		[TaxRate2] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [TaxRate2] end,
		[InsertAuditKey] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [InsertAuditKey] end,
		[UpdateAuditKey] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [UpdateAuditKey] end,
		[RowTimeStamp] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [RowTimeStamp] end,
		[msrepl_tran_version] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [msrepl_tran_version] end,
		[IsClosed] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [IsClosed] end,
		[IsVoided] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [IsVoided] end,
		[ContactKey] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [ContactKey] end,
		[SourceKey] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [SourceKey] end,
		[GenderKey] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [GenderKey] end,
		[OccupationKey] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [OccupationKey] end,
		[EthnicityKey] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [EthnicityKey] end,
		[MaritalStatusKey] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [MaritalStatusKey] end,
		[HairLossTypeKey] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [HairLossTypeKey] end,
		[AgeRangeKey] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [AgeRangeKey] end,
		[PromotionCodeKey] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [PromotionCodeKey] end,
		[S1_SaleCnt] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [S1_SaleCnt] end,
		[S_CancelCnt] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [S_CancelCnt] end,
		[S1_NetSalesCnt] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [S1_NetSalesCnt] end,
		[S1_NetSalesAmt] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [S1_NetSalesAmt] end,
		[S1_ContractAmountAmt] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [S1_ContractAmountAmt] end,
		[S1_EstGraftsCnt] = case substring(@bitmap,6,1) & 1 when 1 then @c41 else [S1_EstGraftsCnt] end,
		[S1_EstPerGraftsAmt] = case substring(@bitmap,6,1) & 2 when 2 then @c42 else [S1_EstPerGraftsAmt] end,
		[SA_NetSalesCnt] = case substring(@bitmap,6,1) & 4 when 4 then @c43 else [SA_NetSalesCnt] end,
		[SA_NetSalesAmt] = case substring(@bitmap,6,1) & 8 when 8 then @c44 else [SA_NetSalesAmt] end,
		[SA_ContractAmountAmt] = case substring(@bitmap,6,1) & 16 when 16 then @c45 else [SA_ContractAmountAmt] end,
		[SA_EstGraftsCnt] = case substring(@bitmap,6,1) & 32 when 32 then @c46 else [SA_EstGraftsCnt] end,
		[SA_EstPerGraftAmt] = case substring(@bitmap,6,1) & 64 when 64 then @c47 else [SA_EstPerGraftAmt] end,
		[S_PostExtCnt] = case substring(@bitmap,6,1) & 128 when 128 then @c48 else [S_PostExtCnt] end,
		[S_PostExtAmt] = case substring(@bitmap,7,1) & 1 when 1 then @c49 else [S_PostExtAmt] end,
		[S_SurgeryPerformedCnt] = case substring(@bitmap,7,1) & 2 when 2 then @c50 else [S_SurgeryPerformedCnt] end,
		[S_SurgeryPerformedAmt] = case substring(@bitmap,7,1) & 4 when 4 then @c51 else [S_SurgeryPerformedAmt] end,
		[S_SurgeryGraftsCnt] = case substring(@bitmap,7,1) & 8 when 8 then @c52 else [S_SurgeryGraftsCnt] end,
		[S1_DepositsTakenCnt] = case substring(@bitmap,7,1) & 16 when 16 then @c53 else [S1_DepositsTakenCnt] end,
		[S1_DepositsTakenAmt] = case substring(@bitmap,7,1) & 32 when 32 then @c54 else [S1_DepositsTakenAmt] end,
		[NB_GrossNB1Cnt] = case substring(@bitmap,7,1) & 64 when 64 then @c55 else [NB_GrossNB1Cnt] end,
		[NB_TradCnt] = case substring(@bitmap,7,1) & 128 when 128 then @c56 else [NB_TradCnt] end,
		[NB_TradAmt] = case substring(@bitmap,8,1) & 1 when 1 then @c57 else [NB_TradAmt] end,
		[NB_GradCnt] = case substring(@bitmap,8,1) & 2 when 2 then @c58 else [NB_GradCnt] end,
		[NB_GradAmt] = case substring(@bitmap,8,1) & 4 when 4 then @c59 else [NB_GradAmt] end,
		[NB_ExtCnt] = case substring(@bitmap,8,1) & 8 when 8 then @c60 else [NB_ExtCnt] end,
		[NB_ExtAmt] = case substring(@bitmap,8,1) & 16 when 16 then @c61 else [NB_ExtAmt] end,
		[NB_AppsCnt] = case substring(@bitmap,8,1) & 32 when 32 then @c62 else [NB_AppsCnt] end,
		[NB_BIOConvCnt] = case substring(@bitmap,8,1) & 64 when 64 then @c63 else [NB_BIOConvCnt] end,
		[NB_EXTConvCnt] = case substring(@bitmap,8,1) & 128 when 128 then @c64 else [NB_EXTConvCnt] end,
		[PCP_NB2Amt] = case substring(@bitmap,9,1) & 1 when 1 then @c65 else [PCP_NB2Amt] end,
		[PCP_PCPAmt] = case substring(@bitmap,9,1) & 2 when 2 then @c66 else [PCP_PCPAmt] end,
		[PCP_BioAmt] = case substring(@bitmap,9,1) & 4 when 4 then @c67 else [PCP_BioAmt] end,
		[PCP_ExtMemAmt] = case substring(@bitmap,9,1) & 8 when 8 then @c68 else [PCP_ExtMemAmt] end,
		[PCPNonPgmAmt] = case substring(@bitmap,9,1) & 16 when 16 then @c69 else [PCPNonPgmAmt] end,
		[ServiceAmt] = case substring(@bitmap,9,1) & 32 when 32 then @c70 else [ServiceAmt] end,
		[RetailAmt] = case substring(@bitmap,9,1) & 64 when 64 then @c71 else [RetailAmt] end,
		[ClientServicedCnt] = case substring(@bitmap,9,1) & 128 when 128 then @c72 else [ClientServicedCnt] end,
		[NetMembershipAmt] = case substring(@bitmap,10,1) & 1 when 1 then @c73 else [NetMembershipAmt] end,
		[S_GrossSurCnt] = case substring(@bitmap,10,1) & 2 when 2 then @c74 else [S_GrossSurCnt] end,
		[S_SurCnt] = case substring(@bitmap,10,1) & 4 when 4 then @c75 else [S_SurCnt] end,
		[S_SurAmt] = case substring(@bitmap,10,1) & 8 when 8 then @c76 else [S_SurAmt] end,
		[AccountID] = case substring(@bitmap,10,1) & 16 when 16 then @c77 else [AccountID] end,
		[PCP_UpgCnt] = case substring(@bitmap,10,1) & 32 when 32 then @c78 else [PCP_UpgCnt] end,
		[PCP_DwnCnt] = case substring(@bitmap,10,1) & 64 when 64 then @c79 else [PCP_DwnCnt] end,
		[NB_RemCnt] = case substring(@bitmap,10,1) & 128 when 128 then @c80 else [NB_RemCnt] end,
		[NB_XTRAmt] = case substring(@bitmap,11,1) & 1 when 1 then @c81 else [NB_XTRAmt] end,
		[NB_XTRCnt] = case substring(@bitmap,11,1) & 2 when 2 then @c82 else [NB_XTRCnt] end,
		[NB_XTRConvCnt] = case substring(@bitmap,11,1) & 4 when 4 then @c83 else [NB_XTRConvCnt] end,
		[PCP_XtrAmt] = case substring(@bitmap,11,1) & 8 when 8 then @c84 else [PCP_XtrAmt] end,
		[MbrPromotion] = case substring(@bitmap,11,1) & 16 when 16 then @c85 else [MbrPromotion] end,
		[NetSalesAmt] = case substring(@bitmap,11,1) & 32 when 32 then @c86 else [NetSalesAmt] end,
		[S_PRPCnt] = case substring(@bitmap,11,1) & 64 when 64 then @c87 else [S_PRPCnt] end,
		[S_PRPAmt] = case substring(@bitmap,11,1) & 128 when 128 then @c88 else [S_PRPAmt] end,
		[LaserAmt] = case substring(@bitmap,12,1) & 1 when 1 then @c89 else [LaserAmt] end,
		[S_StripCnt] = case substring(@bitmap,12,1) & 2 when 2 then @c90 else [S_StripCnt] end,
		[S_StripAmt] = case substring(@bitmap,12,1) & 4 when 4 then @c91 else [S_StripAmt] end,
		[S_ArtasCnt] = case substring(@bitmap,12,1) & 8 when 8 then @c92 else [S_ArtasCnt] end,
		[S_ArtasAmt] = case substring(@bitmap,12,1) & 16 when 16 then @c93 else [S_ArtasAmt] end,
		[LaserCnt] = case substring(@bitmap,12,1) & 32 when 32 then @c94 else [LaserCnt] end,
		[NB_MDPCnt] = case substring(@bitmap,12,1) & 64 when 64 then @c95 else [NB_MDPCnt] end,
		[NB_MDPAmt] = case substring(@bitmap,12,1) & 128 when 128 then @c96 else [NB_MDPAmt] end,
		[NB_LaserCnt] = case substring(@bitmap,13,1) & 1 when 1 then @c97 else [NB_LaserCnt] end,
		[NB_LaserAmt] = case substring(@bitmap,13,1) & 2 when 2 then @c98 else [NB_LaserAmt] end,
		[PCP_LaserCnt] = case substring(@bitmap,13,1) & 4 when 4 then @c99 else [PCP_LaserCnt] end,
		[PCP_LaserAmt] = case substring(@bitmap,13,1) & 8 when 8 then @c100 else [PCP_LaserAmt] end,
		[EMP_RetailAmt] = case substring(@bitmap,13,1) & 16 when 16 then @c101 else [EMP_RetailAmt] end,
		[EMP_NB_LaserCnt] = case substring(@bitmap,13,1) & 32 when 32 then @c102 else [EMP_NB_LaserCnt] end,
		[EMP_NB_LaserAmt] = case substring(@bitmap,13,1) & 64 when 64 then @c103 else [EMP_NB_LaserAmt] end,
		[EMP_PCP_LaserCnt] = case substring(@bitmap,13,1) & 128 when 128 then @c104 else [EMP_PCP_LaserCnt] end,
		[EMP_PCP_LaserAmt] = case substring(@bitmap,14,1) & 1 when 1 then @c105 else [EMP_PCP_LaserAmt] end
	where [OrderDateKey] = @pkc1
  and [SalesOrderKey] = @pkc2
  and [SalesOrderDetailKey] = @pkc3
if @@rowcount = 0
    if @@microsoftversion>0x07320000
		Begin
			if exists (Select * from sys.all_parameters where object_id = OBJECT_ID('sp_MSreplraiserror') and [name] = '@param3')
			Begin

				set @primarykey_text = @primarykey_text + '[OrderDateKey] = ' + convert(nvarchar(100),@pkc1,1) + ', '
				set @primarykey_text = @primarykey_text + '[SalesOrderKey] = ' + convert(nvarchar(100),@pkc2,1) + ', '
				set @primarykey_text = @primarykey_text + '[SalesOrderDetailKey] = ' + convert(nvarchar(100),@pkc3,1)
				exec sp_MSreplraiserror @errorid=20598, @param1=N'[bi_cms_dds].[FactSalesTransaction]', @param2=@primarykey_text, @param3=13233
			End
			Else
				exec sp_MSreplraiserror @errorid=20598
		End
end
end
GO
