create procedure [sp_MSins_bi_cms_ddsDimEmployeePosition]
    @c1 int,
    @c2 nvarchar(50),
    @c3 nvarchar(50),
    @c4 nvarchar(10),
    @c5 int,
    @c6 nvarchar(50),
    @c7 bit,
    @c8 bit,
    @c9 bit,
    @c10 bit,
    @c11 bit,
    @c12 bit,
    @c13 int,
    @c14 bit,
    @c15 bit,
    @c16 bit,
    @c17 nchar(1),
    @c18 tinyint,
    @c19 datetime,
    @c20 datetime,
    @c21 varchar(200),
    @c22 tinyint,
    @c23 int,
    @c24 int,
    @c25 uniqueidentifier
as
begin
	insert into [bi_cms_dds].[DimEmployeePosition] (
		[EmployeePositionKey],
		[EmployeePositionSSID],
		[EmployeePositionDescription],
		[EmployeePositionDescriptionShort],
		[EmployeePositionSortOrder],
		[ActiveDirectoryGroup],
		[IsAdministratorFlag],
		[IsEmployeeOneFlag],
		[IsEmployeeTwoFlag],
		[IsEmployeeThreeFlag],
		[IsEmployeeFourFlag],
		[CanScheduleFlag],
		[ApplicationTimeoutMinutes],
		[UseDefaultCenterFlag],
		[IsSurgeryCenterEmployeeFlag],
		[IsNonSurgeryCenterEmployeeFlag],
		[Active],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		default,
		@c25	)
end
