create procedure [sp_MSins_bi_cms_ddsDimMembership]
    @c1 int,
    @c2 int,
    @c3 nvarchar(50),
    @c4 nvarchar(10),
    @c5 int,
    @c6 int,
    @c7 int,
    @c8 nvarchar(50),
    @c9 nvarchar(10),
    @c10 int,
    @c11 nvarchar(50),
    @c12 nvarchar(10),
    @c13 int,
    @c14 money,
    @c15 money,
    @c16 tinyint,
    @c17 datetime,
    @c18 datetime,
    @c19 varchar(200),
    @c20 tinyint,
    @c21 int,
    @c22 int,
    @c23 uniqueidentifier,
    @c24 int,
    @c25 nvarchar(50),
    @c26 nvarchar(50)
as
begin
	insert into [bi_cms_dds].[DimMembership] (
		[MembershipKey],
		[MembershipSSID],
		[MembershipDescription],
		[MembershipDescriptionShort],
		[BusinessSegmentKey],
		[BusinessSegmentSSID],
		[RevenueGroupSSID],
		[RevenueGroupDescription],
		[RevenueGroupDescriptionShort],
		[GenderSSID],
		[GenderDescription],
		[GenderDescriptionShort],
		[MembershipDurationMonths],
		[MembershipContractPrice],
		[MembershipMonthlyFee],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[MembershipSortOrder],
		[BusinessSegmentDescription],
		[BusinessSegmentDescriptionShort]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		default,
		@c23,
		@c24,
		@c25,
		@c26	)
end
