/* CreateDate: 03/17/2022 11:57:09.203 , ModifyDate: 03/17/2022 11:57:09.203 */
GO
create procedure [dbo].[sp_MSins_bi_cms_ddsDimClient]
    @c1 int,
    @c2 uniqueidentifier,
    @c3 int,
    @c4 int,
    @c5 nvarchar(50),
    @c6 nvarchar(20),
    @c7 nvarchar(50),
    @c8 int,
    @c9 nvarchar(50),
    @c10 nvarchar(10),
    @c11 nvarchar(50),
    @c12 nvarchar(50),
    @c13 nvarchar(50),
    @c14 nvarchar(50),
    @c15 nvarchar(10),
    @c16 nvarchar(50),
    @c17 nvarchar(10),
    @c18 nvarchar(50),
    @c19 nvarchar(15),
    @c20 datetime,
    @c21 int,
    @c22 nvarchar(50),
    @c23 nvarchar(10),
    @c24 int,
    @c25 nvarchar(50),
    @c26 nvarchar(10),
    @c27 int,
    @c28 nvarchar(50),
    @c29 nvarchar(10),
    @c30 int,
    @c31 nvarchar(50),
    @c32 nvarchar(10),
    @c33 bit,
    @c34 bit,
    @c35 bit,
    @c36 bit,
    @c37 nvarchar(100),
    @c38 nvarchar(100),
    @c39 nvarchar(15),
    @c40 int,
    @c41 nvarchar(50),
    @c42 nvarchar(10),
    @c43 nvarchar(15),
    @c44 int,
    @c45 nvarchar(50),
    @c46 nvarchar(10),
    @c47 nvarchar(15),
    @c48 int,
    @c49 nvarchar(50),
    @c50 nvarchar(10),
    @c51 tinyint,
    @c52 datetime,
    @c53 datetime,
    @c54 varchar(200),
    @c55 tinyint,
    @c56 int,
    @c57 int,
    @c58 binary(8),
    @c59 uniqueidentifier,
    @c60 uniqueidentifier,
    @c61 uniqueidentifier,
    @c62 uniqueidentifier,
    @c63 int,
    @c64 money,
    @c65 nvarchar(10),
    @c66 int,
    @c67 uniqueidentifier,
    @c68 nvarchar(50),
    @c69 nvarchar(50),
    @c70 nvarchar(50),
    @c71 datetime,
    @c72 nvarchar(18),
    @c73 uniqueidentifier,
    @c74 varbinary(128)
as
begin
	insert into [bi_cms_dds].[DimClient] (
		[ClientKey],
		[ClientSSID],
		[ClientNumber_Temp],
		[ClientIdentifier],
		[ClientFirstName],
		[ClientMiddleName],
		[ClientLastName],
		[SalutationSSID],
		[ClientSalutationDescription],
		[ClientSalutationDescriptionShort],
		[ClientAddress1],
		[ClientAddress2],
		[ClientAddress3],
		[CountryRegionDescription],
		[CountryRegionDescriptionShort],
		[StateProvinceDescription],
		[StateProvinceDescriptionShort],
		[City],
		[PostalCode],
		[ClientDateOfBirth],
		[GenderSSID],
		[ClientGenderDescription],
		[ClientGenderDescriptionShort],
		[MaritalStatusSSID],
		[ClientMaritalStatusDescription],
		[ClientMaritalStatusDescriptionShort],
		[OccupationSSID],
		[ClientOccupationDescription],
		[ClientOccupationDescriptionShort],
		[EthinicitySSID],
		[ClientEthinicityDescription],
		[ClientEthinicityDescriptionShort],
		[DoNotCallFlag],
		[DoNotContactFlag],
		[IsHairModelFlag],
		[IsTaxExemptFlag],
		[ClientEMailAddress],
		[ClientTextMessageAddress],
		[ClientPhone1],
		[Phone1TypeSSID],
		[ClientPhone1TypeDescription],
		[ClientPhone1TypeDescriptionShort],
		[ClientPhone2],
		[Phone2TypeSSID],
		[ClientPhone2TypeDescription],
		[ClientPhone2TypeDescriptionShort],
		[ClientPhone3],
		[Phone3TypeSSID],
		[ClientPhone3TypeDescription],
		[ClientPhone3TypeDescriptionShort],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[CurrentBioMatrixClientMembershipSSID],
		[CurrentSurgeryClientMembershipSSID],
		[CurrentExtremeTherapyClientMembershipSSID],
		[CenterSSID],
		[ClientARBalance],
		[contactssid],
		[contactkey],
		[CurrentXtrandsClientMembershipSSID],
		[BosleyProcedureOffice],
		[BosleyConsultOffice],
		[BosleySiebelID],
		[ExpectedConversionDate],
		[SFDC_Leadid],
		[CurrentMDPClientMembershipSSID],
		[ClientEmailAddressHashed]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29,
		@c30,
		@c31,
		@c32,
		@c33,
		@c34,
		@c35,
		@c36,
		@c37,
		@c38,
		@c39,
		@c40,
		@c41,
		@c42,
		@c43,
		@c44,
		@c45,
		@c46,
		@c47,
		@c48,
		@c49,
		@c50,
		@c51,
		@c52,
		@c53,
		@c54,
		@c55,
		@c56,
		@c57,
		@c58,
		@c59,
		@c60,
		@c61,
		@c62,
		@c63,
		@c64,
		@c65,
		@c66,
		@c67,
		@c68,
		@c69,
		@c70,
		@c71,
		@c72,
		@c73,
		@c74	)
end
GO
