create procedure [dbo].[sp_MSins_bi_cms_ddsDimClientMembership]
    @c1 int,
    @c2 uniqueidentifier,
    @c3 int,
    @c4 int,
    @c5 uniqueidentifier,
    @c6 int,
    @c7 int,
    @c8 int,
    @c9 int,
    @c10 int,
    @c11 nvarchar(50),
    @c12 nvarchar(10),
    @c13 money,
    @c14 money,
    @c15 money,
    @c16 datetime,
    @c17 datetime,
    @c18 datetime,
    @c19 tinyint,
    @c20 datetime,
    @c21 datetime,
    @c22 varchar(200),
    @c23 tinyint,
    @c24 int,
    @c25 int,
    @c26 binary(8),
    @c27 uniqueidentifier,
    @c28 nvarchar(50),
    @c29 money
as
begin
	insert into [bi_cms_dds].[DimClientMembership] (
		[ClientMembershipKey],
		[ClientMembershipSSID],
		[Member1_ID_Temp],
		[ClientKey],
		[ClientSSID],
		[CenterKey],
		[CenterSSID],
		[MembershipKey],
		[MembershipSSID],
		[ClientMembershipStatusSSID],
		[ClientMembershipStatusDescription],
		[ClientMembershipStatusDescriptionShort],
		[ClientMembershipContractPrice],
		[ClientMembershipContractPaidAmount],
		[ClientMembershipMonthlyFee],
		[ClientMembershipBeginDate],
		[ClientMembershipEndDate],
		[ClientMembershipCancelDate],
		[RowIsCurrent],
		[RowStartDate],
		[RowEndDate],
		[RowChangeReason],
		[RowIsInferred],
		[InsertAuditKey],
		[UpdateAuditKey],
		[RowTimeStamp],
		[msrepl_tran_version],
		[ClientMembershipIdentifier],
		[NationalMonthlyFee]
	) values (
		@c1,
		@c2,
		@c3,
		@c4,
		@c5,
		@c6,
		@c7,
		@c8,
		@c9,
		@c10,
		@c11,
		@c12,
		@c13,
		@c14,
		@c15,
		@c16,
		@c17,
		@c18,
		@c19,
		@c20,
		@c21,
		@c22,
		@c23,
		@c24,
		@c25,
		@c26,
		@c27,
		@c28,
		@c29	)
end
