/* CreateDate: 04/06/2021 14:09:51.370 , ModifyDate: 04/06/2021 14:09:51.370 */
GO
CREATE TABLE [dbo].[Task](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordTypeId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhoId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhatId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WhoCount] [int] NULL,
	[WhatCount] [int] NULL,
	[Subject] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ActivityDate] [date] NULL,
	[Status] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Priority] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsHighPriority] [bit] NULL,
	[OwnerId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrencyIsoCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeleted] [bit] NULL,
	[AccountId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsClosed] [bit] NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SystemModstamp] [datetime] NULL,
	[IsArchived] [bit] NULL,
	[CallDurationInSeconds] [int] NULL,
	[CallType] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CallDisposition] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CallObject] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReminderDateTime] [datetime] NULL,
	[IsReminderSet] [bit] NULL,
	[RecurrenceActivityId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRecurrence] [bit] NULL,
	[RecurrenceStartDateOnly] [date] NULL,
	[RecurrenceEndDateOnly] [date] NULL,
	[RecurrenceTimeZoneSidKey] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceType] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceInterval] [int] NULL,
	[RecurrenceDayOfWeekMask] [int] NULL,
	[RecurrenceDayOfMonth] [int] NULL,
	[RecurrenceInstance] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceMonthOfYear] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecurrenceRegeneratedType] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TaskSubtype] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrightPattern__SPRecordingOrTranscriptURL__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPRecordingOrTranscriptURL__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recording_Link__c] [nvarchar](1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
