/* CreateDate: 04/06/2021 11:49:26.140 , ModifyDate: 04/06/2021 11:49:26.140 */
GO
CREATE TABLE [dbo].[Contact](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeleted] [bit] NULL,
	[MasterRecordId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccountId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPersonAccount] [bit] NULL,
	[LastName] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Salutation] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MiddleName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Suffix] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [nvarchar](121) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingStreet] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingCity] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingState] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingPostalCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingCountry] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingStateCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingCountryCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingLatitude] [float] NULL,
	[MailingLongitude] [float] NULL,
	[MailingGeocodeAccuracy] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MailingAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MobilePhone] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportsToId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Email] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Title] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Department] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrencyIsoCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OwnerId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HasOptedOutOfEmail] [bit] NULL,
	[DoNotCall] [bit] NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SystemModstamp] [datetime] NULL,
	[LastActivityDate] [date] NULL,
	[LastCURequestDate] [datetime] NULL,
	[LastCUUpdateDate] [datetime] NULL,
	[LastViewedDate] [datetime] NULL,
	[LastReferencedDate] [datetime] NULL,
	[EmailBouncedReason] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmailBouncedDate] [datetime] NULL,
	[IsEmailBounced] [bit] NULL,
	[PhotoUrl] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Jigsaw] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JigsawContactId] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
