/* CreateDate: 04/06/2021 11:20:35.240 , ModifyDate: 04/06/2021 11:20:35.240 */
GO
CREATE TABLE [dbo].[Account](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeleted] [bit] NULL,
	[MasterRecordId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Salutation] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MiddleName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Suffix] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordTypeId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParentId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingStreet] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingCity] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingState] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingPostalCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingCountry] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingStateCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingCountryCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingLatitude] [float] NULL,
	[BillingLongitude] [float] NULL,
	[BillingGeocodeAccuracy] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BillingAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingStreet] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingCity] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingState] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingPostalCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingCountry] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingStateCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingCountryCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingLatitude] [float] NULL,
	[ShippingLongitude] [float] NULL,
	[ShippingGeocodeAccuracy] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShippingAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Phone] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Fax] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccountNumber] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Website] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhotoUrl] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Industry] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NumberOfEmployees] [int] NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrencyIsoCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OwnerId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SystemModstamp] [datetime] NULL,
	[LastActivityDate] [date] NULL,
	[LastViewedDate] [datetime] NULL,
	[LastReferencedDate] [datetime] NULL,
	[IsPartner] [bit] NULL,
	[IsCustomerPortal] [bit] NULL,
	[PersonContactId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPersonAccount] [bit] NULL,
	[PersonMailingStreet] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingCity] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingState] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingPostalCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingCountry] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingStateCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingCountryCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingLatitude] [float] NULL,
	[PersonMailingLongitude] [float] NULL,
	[PersonMailingGeocodeAccuracy] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMailingAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonMobilePhone] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonEmail] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonTitle] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonDepartment] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonHasOptedOutOfEmail] [bit] NULL,
	[PersonDoNotCall] [bit] NULL,
	[PersonLastCURequestDate] [datetime] NULL,
	[PersonLastCUUpdateDate] [datetime] NULL,
	[PersonEmailBouncedReason] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonEmailBouncedDate] [datetime] NULL,
	[Jigsaw] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JigsawCompanyId] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccountSource] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SicDesc] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OperatingHoursId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
