/* CreateDate: 04/06/2021 13:50:05.550 , ModifyDate: 04/06/2021 13:50:05.550 */
GO
CREATE TABLE [dbo].[Opportunity](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeleted] [bit] NULL,
	[AccountId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordTypeId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Name] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StageName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amount] [float] NULL,
	[Probability] [float] NULL,
	[CloseDate] [date] NULL,
	[Type] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NextStep] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LeadSource] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsClosed] [bit] NULL,
	[IsWon] [bit] NULL,
	[ForecastCategory] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ForecastCategoryName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrencyIsoCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CampaignId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HasOpportunityLineItem] [bit] NULL,
	[Pricebook2Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OwnerId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SystemModstamp] [datetime] NULL,
	[LastActivityDate] [date] NULL,
	[FiscalQuarter] [int] NULL,
	[FiscalYear] [int] NULL,
	[Fiscal] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastViewedDate] [datetime] NULL,
	[LastReferencedDate] [datetime] NULL,
	[SyncedQuoteId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContractId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HasOpenActivity] [bit] NULL,
	[HasOverdueTask] [bit] NULL,
	[Referral_Code__c] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Referral_Code_Expiration_Date__c] [date] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
