/* CreateDate: 04/06/2021 11:21:51.653 , ModifyDate: 04/06/2021 11:21:51.653 */
GO
CREATE TABLE [dbo].[Campaign](
	[Id] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeleted] [bit] NULL,
	[Name] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParentId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordTypeId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[CurrencyIsoCode] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExpectedRevenue] [float] NULL,
	[BudgetedCost] [float] NULL,
	[ActualCost] [float] NULL,
	[ExpectedResponse] [float] NULL,
	[NumberSent] [float] NULL,
	[IsActive] [bit] NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NumberOfLeads] [int] NULL,
	[NumberOfConvertedLeads] [int] NULL,
	[NumberOfContacts] [int] NULL,
	[NumberOfResponses] [int] NULL,
	[NumberOfOpportunities] [int] NULL,
	[NumberOfWonOpportunities] [int] NULL,
	[AmountAllOpportunities] [float] NULL,
	[AmountWonOpportunities] [float] NULL,
	[OwnerId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedById] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SystemModstamp] [datetime] NULL,
	[LastActivityDate] [date] NULL,
	[LastViewedDate] [datetime] NULL,
	[LastReferencedDate] [datetime] NULL,
	[CampaignMemberRecordTypeId] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
