/* CreateDate: 10/03/2019 22:32:12.520 , ModifyDate: 10/04/2019 00:08:58.767 */
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactReceivables](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CenterKey] [int] NOT NULL,
	[DateKey] [int] NOT NULL,
	[ClientKey] [int] NOT NULL,
	[Balance] [float] NULL,
	[PrePaid] [money] NULL,
 CONSTRAINT [PK__FactRece__3214EC27304B41EF] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FactReceivables_Balance_INCL] ON [dbo].[FactReceivables]
(
	[DateKey] ASC,
	[Balance] ASC
)
INCLUDE([CenterKey],[ClientKey]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FactReceivables_ClientKey_INCL] ON [dbo].[FactReceivables]
(
	[ClientKey] ASC
)
INCLUDE([CenterKey],[DateKey],[Balance]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
