/* CreateDate: 10/03/2019 22:32:12.463 , ModifyDate: 10/04/2019 00:08:26.853 */
GO
CREATE TABLE [dbo].[FactPCPDetail](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CenterKey] [int] NULL,
	[ClientKey] [int] NULL,
	[GenderKey] [int] NULL,
	[MembershipKey] [int] NULL,
	[DateKey] [int] NULL,
	[PCP] [int] NULL,
	[EXT] [int] NULL,
	[Timestamp] [datetime] NULL,
	[XTR] [int] NULL,
 CONSTRAINT [PK__FactPCPD__3214EC27BD7E2AE8] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NC_FactPCPDetail_DateKey] ON [dbo].[FactPCPDetail]
(
	[DateKey] ASC
)
INCLUDE([ClientKey],[PCP],[EXT],[XTR]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
