/* CreateDate: 07/30/2015 15:49:41.727 , ModifyDate: 07/30/2015 15:49:41.727 */
GO
create procedure [sp_MSins_dboCampaignNames]
    @c1 int,
    @c2 varchar(255),
    @c3 smalldatetime,
    @c4 varchar(40),
    @c5 int,
    @c6 varchar(1000),
    @c7 varchar(1000),
    @c8 varchar(200),
    @c9 smalldatetime,
    @c10 smalldatetime,
    @c11 smalldatetime,
    @c12 smalldatetime,
    @c13 varchar(10),
    @c14 tinyint,
    @c15 varchar(1000),
    @c16 smalldatetime,
    @c17 smalldatetime,
    @c18 smalldatetime,
    @c19 smalldatetime,
    @c20 smalldatetime,
    @c21 smalldatetime,
    @c22 char(1),
    @c23 char(1),
    @c24 char(1),
    @c25 char(1),
    @c26 smalldatetime,
    @c27 smalldatetime,
    @c28 smalldatetime,
    @c29 smalldatetime,
    @c30 smalldatetime,
    @c31 smalldatetime,
    @c32 datetime,
    @c33 datetime,
    @c34 bit,
    @c35 varchar(1000),
    @c36 varchar(1000)
as
begin
	insert into [dbo].[CampaignNames](
		[CampaignID],
		[CampaignName],
		[DateCreated],
		[CreatedBy],
		[ListID],
		[CampaignDescription],
		[Param_Centers],
		[Param_Regions],
		[Param_ResultStartDate],
		[Param_ResultEndDate],
		[Param_ShowStartDate],
		[Param_ShowEndDate],
		[Param_Gender],
		[Param_GenderID],
		[Param_Member1],
		[Param_CancelStartDate],
		[Param_CancelEndDate],
		[Param_SurStartDate],
		[Param_SurEndDate],
		[Param_SurpostStartDate],
		[Param_SurpostEndDate],
		[Param_DoNotMail],
		[Param_DoNotEmail],
		[Param_DoNotCall],
		[Param_DoNotContact],
		[Param_LeadCreationStartDate],
		[Param_LeadCreationEndDate],
		[Param_MembershipBeginStartDate],
		[Param_MembershipBeginEndDate],
		[Param_MembershipExpStartDate],
		[Param_MembershipExpEndDate],
		[StartTime],
		[EndTime],
		[Param_BeBacks],
		[Param_NoSaleReason],
		[Param_CancelReasonIDs]
	) values (
    @c1,
    @c2,
    @c3,
    @c4,
    @c5,
    @c6,
    @c7,
    @c8,
    @c9,
    @c10,
    @c11,
    @c12,
    @c13,
    @c14,
    @c15,
    @c16,
    @c17,
    @c18,
    @c19,
    @c20,
    @c21,
    @c22,
    @c23,
    @c24,
    @c25,
    @c26,
    @c27,
    @c28,
    @c29,
    @c30,
    @c31,
    @c32,
    @c33,
    @c34,
    @c35,
    @c36	)
end
GO
