/* CreateDate: 07/30/2015 15:49:41.800 , ModifyDate: 07/30/2015 15:49:41.800 */
GO
create procedure [sp_MSupd_dboCampaignResults]
		@c1 int = NULL,
		@c2 int = NULL,
		@c3 int = NULL,
		@c4 varchar(40) = NULL,
		@c5 int = NULL,
		@c6 varchar(50) = NULL,
		@c7 smalldatetime = NULL,
		@c8 varchar(10) = NULL,
		@c9 tinyint = NULL,
		@c10 varchar(10) = NULL,
		@c11 varchar(10) = NULL,
		@c12 varchar(25) = NULL,
		@c13 varchar(30) = NULL,
		@c14 varchar(60) = NULL,
		@c15 varchar(60) = NULL,
		@c16 varchar(60) = NULL,
		@c17 char(2) = NULL,
		@c18 varchar(25) = NULL,
		@c19 char(20) = NULL,
		@c20 varchar(30) = NULL,
		@c21 tinyint = NULL,
		@c22 varchar(50) = NULL,
		@c23 tinyint = NULL,
		@c24 varchar(30) = NULL,
		@c25 tinyint = NULL,
		@c26 char(50) = NULL,
		@c27 varchar(30) = NULL,
		@c28 varchar(30) = NULL,
		@c29 smalldatetime = NULL,
		@c30 smalldatetime = NULL,
		@c31 varchar(50) = NULL,
		@c32 int = NULL,
		@c33 varchar(100) = NULL,
		@c34 varchar(50) = NULL,
		@c35 varchar(30) = NULL,
		@c36 varchar(30) = NULL,
		@c37 int = NULL,
		@pkc1 int = NULL,
		@bitmap binary(5)
as
begin
update [dbo].[CampaignResults] set
		[CampaignID] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [CampaignID] end,
		[Center] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [Center] end,
		[CenterName] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [CenterName] end,
		[RegionID] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [RegionID] end,
		[Region] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [Region] end,
		[ApptDate] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [ApptDate] end,
		[Gender] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [Gender] end,
		[GenderID] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [GenderID] end,
		[RecordID] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [RecordID] end,
		[ContactID] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [ContactID] end,
		[FirstName] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [FirstName] end,
		[LastName] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [LastName] end,
		[Address1] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Address1] end,
		[Address2] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Address2] end,
		[City] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [City] end,
		[State] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [State] end,
		[Zip] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [Zip] end,
		[Phone] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [Phone] end,
		[Ethnicity] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [Ethnicity] end,
		[EthnicityID] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [EthnicityID] end,
		[Age] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [Age] end,
		[AgeID] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [AgeID] end,
		[MaritalStatus] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [MaritalStatus] end,
		[MaritalStatusID] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [MaritalStatusID] end,
		[Email] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [Email] end,
		[Member1] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [Member1] end,
		[Member2] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [Member2] end,
		[CreationDate] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [CreationDate] end,
		[CancelTrxDate] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [CancelTrxDate] end,
		[NoSaleReason] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [NoSaleReason] end,
		[CancelReasonID] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [CancelReasonID] end,
		[CancelReason] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [CancelReason] end,
		[Occupation] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [Occupation] end,
		[Ludwig] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [Ludwig] end,
		[Norwood] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [Norwood] end,
		[Client_No] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [Client_No] end
where [ResultsID] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end
GO
