/* CreateDate: 07/30/2015 15:49:41.750 , ModifyDate: 07/30/2015 15:49:41.750 */
GO
create procedure [sp_MSupd_dboCampaignNames]
		@c1 int = NULL,
		@c2 varchar(255) = NULL,
		@c3 smalldatetime = NULL,
		@c4 varchar(40) = NULL,
		@c5 int = NULL,
		@c6 varchar(1000) = NULL,
		@c7 varchar(1000) = NULL,
		@c8 varchar(200) = NULL,
		@c9 smalldatetime = NULL,
		@c10 smalldatetime = NULL,
		@c11 smalldatetime = NULL,
		@c12 smalldatetime = NULL,
		@c13 varchar(10) = NULL,
		@c14 tinyint = NULL,
		@c15 varchar(1000) = NULL,
		@c16 smalldatetime = NULL,
		@c17 smalldatetime = NULL,
		@c18 smalldatetime = NULL,
		@c19 smalldatetime = NULL,
		@c20 smalldatetime = NULL,
		@c21 smalldatetime = NULL,
		@c22 char(1) = NULL,
		@c23 char(1) = NULL,
		@c24 char(1) = NULL,
		@c25 char(1) = NULL,
		@c26 smalldatetime = NULL,
		@c27 smalldatetime = NULL,
		@c28 smalldatetime = NULL,
		@c29 smalldatetime = NULL,
		@c30 smalldatetime = NULL,
		@c31 smalldatetime = NULL,
		@c32 datetime = NULL,
		@c33 datetime = NULL,
		@c34 bit = NULL,
		@c35 varchar(1000) = NULL,
		@c36 varchar(1000) = NULL,
		@pkc1 int = NULL,
		@bitmap binary(5)
as
begin
update [dbo].[CampaignNames] set
		[CampaignName] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [CampaignName] end,
		[DateCreated] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [DateCreated] end,
		[CreatedBy] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [CreatedBy] end,
		[ListID] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [ListID] end,
		[CampaignDescription] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [CampaignDescription] end,
		[Param_Centers] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [Param_Centers] end,
		[Param_Regions] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [Param_Regions] end,
		[Param_ResultStartDate] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [Param_ResultStartDate] end,
		[Param_ResultEndDate] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Param_ResultEndDate] end,
		[Param_ShowStartDate] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [Param_ShowStartDate] end,
		[Param_ShowEndDate] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [Param_ShowEndDate] end,
		[Param_Gender] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [Param_Gender] end,
		[Param_GenderID] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [Param_GenderID] end,
		[Param_Member1] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Param_Member1] end,
		[Param_CancelStartDate] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [Param_CancelStartDate] end,
		[Param_CancelEndDate] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [Param_CancelEndDate] end,
		[Param_SurStartDate] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [Param_SurStartDate] end,
		[Param_SurEndDate] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [Param_SurEndDate] end,
		[Param_SurpostStartDate] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [Param_SurpostStartDate] end,
		[Param_SurpostEndDate] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [Param_SurpostEndDate] end,
		[Param_DoNotMail] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [Param_DoNotMail] end,
		[Param_DoNotEmail] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [Param_DoNotEmail] end,
		[Param_DoNotCall] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [Param_DoNotCall] end,
		[Param_DoNotContact] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [Param_DoNotContact] end,
		[Param_LeadCreationStartDate] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [Param_LeadCreationStartDate] end,
		[Param_LeadCreationEndDate] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [Param_LeadCreationEndDate] end,
		[Param_MembershipBeginStartDate] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [Param_MembershipBeginStartDate] end,
		[Param_MembershipBeginEndDate] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [Param_MembershipBeginEndDate] end,
		[Param_MembershipExpStartDate] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [Param_MembershipExpStartDate] end,
		[Param_MembershipExpEndDate] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [Param_MembershipExpEndDate] end,
		[StartTime] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [StartTime] end,
		[EndTime] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [EndTime] end,
		[Param_BeBacks] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [Param_BeBacks] end,
		[Param_NoSaleReason] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [Param_NoSaleReason] end,
		[Param_CancelReasonIDs] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [Param_CancelReasonIDs] end
where [CampaignID] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end
GO
