/* CreateDate: 04/23/2018 16:25:13.693 , ModifyDate: 04/23/2018 16:25:13.693 */
GO
create procedure [sp_MSupd_dboMediaSourceSources]     @c1 int = NULL,     @c2 varchar(50) = NULL,     @c3 varchar(100) = NULL,     @c4 int = NULL,     @c5 tinyint = NULL,     @c6 smallint = NULL,     @c7 int = NULL,     @c8 int = NULL,     @c9 int = NULL,     @c10 int = NULL,     @c11 smalldatetime = NULL,     @c12 smalldatetime = NULL,     @c13 smalldatetime = NULL,     @c14 smalldatetime = NULL,     @c15 varchar(1000) = NULL,     @c16 char(1) = NULL,     @c17 char(1) = NULL,     @pkc1 int = NULL,     @bitmap binary(3)
as
begin   update [dbo].[MediaSourceSources] set     [SourceCode] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [SourceCode] end,     [SourceName] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [SourceName] end,     [PhoneID] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [PhoneID] end,     [NumberTypeID] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [NumberTypeID] end,     [MediaID] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [MediaID] end,     [Level02ID] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [Level02ID] end,     [Level03ID] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [Level03ID] end,     [Level04ID] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [Level04ID] end,     [Level05ID] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [Level05ID] end,     [StartDate] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [StartDate] end,     [EndDate] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [EndDate] end,     [CreationDate] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [CreationDate] end,     [LastUpdateDate] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [LastUpdateDate] end,     [Description] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [Description] end,     [IsInHouseSourceFlag] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [IsInHouseSourceFlag] end,     [IsHansWiemannSourceFlag] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [IsHansWiemannSourceFlag] end
where [SourceID] = @pkc1 if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598 end   --
GO
