SELECT
    [s].[FirstName] AS [LeadFirstName]
  , [s].[Id] AS [LeadId]
  , [s].[LastName] AS [LeadLastName]
  , [s].[Name] AS [LeadFullName]
  , [s].[Birthdate__c] AS [LeadBirthday]
  , [s].[Street] AS [LeadAddress]
  , [s].[Email] AS [LeadEmail]
  , [s].[CreatedById]
  , [s].[LastModifiedById]
  , [s].[Phone] AS [LeadPhone]
  , [s].[MobilePhone] AS [LeadMobilePhone]
  , [s].[NorwoodScale__c] AS [NorwoodScale]
  , [s].[LudwigScale__c] AS [LudwigScale]
  , [s].[HairLossFamily__c] AS [HairLossInFamily]
  , [s].[HairLossProductUsed__c] AS [HairLossProductUsed]
  , [s].[HairLossSpot__c] AS [HairLossSpot]
  , [s].[PostalCode] AS [LeadPostalCode]
  , [s].[City]
  , [s].[State]
  , [s].[Ethnicity__c] AS [LeadEthnicity]
  , [s].[Gender__c] AS [LeadGender]
  , [s].[Language__c] AS [LeadLanguage]
  , [s].[Status] AS [LeadStatus]
  , [s].[CreatedDate]
  , [s].[LastActivityDate]
  , [s].[MaritalStatus__c] AS [LeadMaritalStatus]
  , [s].[LastModifiedDate]
  , [s].[LeadSource]
  , [s].[DoNotCall]
  , [s].[DoNotContact__c] AS [DoNotContact]
  , [s].[DoNotEmail__c] AS [DoNotEmail]
  , [s].[DoNotMail__c] AS [DoNotMail]
FROM [ODS].[SF_Lead] AS [s]
WHERE [s].[LastModifiedDate] <= GETDATE() AND CAST([s].[LastModifiedDate] AS DATE) > DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) ;
