/* CreateDate: 03/17/2022 15:12:21.027 , ModifyDate: 03/17/2022 15:12:21.027 */
GO
CREATE PROCEDURE [SF].[sp_CampaignMember_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[CampaignMember])
RETURN ;

BEGIN TRY
;MERGE [SF].[CampaignMember] AS [t]
USING [SFStaging].[CampaignMember] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[IsDeleted] = [t].[IsDeleted]
	, [t].[CampaignId] = [t].[CampaignId]
	, [t].[LeadId] = [t].[LeadId]
	, [t].[ContactId] = [t].[ContactId]
	, [t].[Status] = [t].[Status]
	, [t].[HasResponded] = [t].[HasResponded]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[FirstRespondedDate] = [t].[FirstRespondedDate]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[Salutation] = [t].[Salutation]
	, [t].[Name] = [t].[Name]
	, [t].[FirstName] = [t].[FirstName]
	, [t].[LastName] = [t].[LastName]
	, [t].[Title] = [t].[Title]
	, [t].[Street] = [t].[Street]
	, [t].[City] = [t].[City]
	, [t].[State] = [t].[State]
	, [t].[PostalCode] = [t].[PostalCode]
	, [t].[Country] = [t].[Country]
	, [t].[Email] = [t].[Email]
	, [t].[Phone] = [t].[Phone]
	, [t].[Fax] = [t].[Fax]
	, [t].[MobilePhone] = [t].[MobilePhone]
	, [t].[Description] = [t].[Description]
	, [t].[DoNotCall] = [t].[DoNotCall]
	, [t].[HasOptedOutOfEmail] = [t].[HasOptedOutOfEmail]
	, [t].[HasOptedOutOfFax] = [t].[HasOptedOutOfFax]
	, [t].[LeadSource] = [t].[LeadSource]
	, [t].[CompanyOrAccount] = [t].[CompanyOrAccount]
	, [t].[Type] = [t].[Type]
	, [t].[LeadOrContactId] = [t].[LeadOrContactId]
	, [t].[LeadOrContactOwnerId] = [t].[LeadOrContactOwnerId]
	, [t].[Opportunity__c] = [t].[Opportunity__c]
	, [t].[SourceCode__c] = [t].[SourceCode__c]
	, [t].[Device_Type__c] = [t].[Device_Type__c]
	, [t].[Do_Not_Call_from_Lead_Contact__c] = [t].[Do_Not_Call_from_Lead_Contact__c]
	, [t].[Last_Activity_Date__c] = [t].[Last_Activity_Date__c]
	, [t].[Lead_Status__c] = [t].[Lead_Status__c]
	, [t].[Time_Zone__c] = [t].[Time_Zone__c]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [IsDeleted]
	, [CampaignId]
	, [LeadId]
	, [ContactId]
	, [Status]
	, [HasResponded]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [FirstRespondedDate]
	, [CurrencyIsoCode]
	, [Salutation]
	, [Name]
	, [FirstName]
	, [LastName]
	, [Title]
	, [Street]
	, [City]
	, [State]
	, [PostalCode]
	, [Country]
	, [Email]
	, [Phone]
	, [Fax]
	, [MobilePhone]
	, [Description]
	, [DoNotCall]
	, [HasOptedOutOfEmail]
	, [HasOptedOutOfFax]
	, [LeadSource]
	, [CompanyOrAccount]
	, [Type]
	, [LeadOrContactId]
	, [LeadOrContactOwnerId]
	, [Opportunity__c]
	, [SourceCode__c]
	, [Device_Type__c]
	, [Do_Not_Call_from_Lead_Contact__c]
	, [Last_Activity_Date__c]
	, [Lead_Status__c]
	, [Time_Zone__c]
	)
	VALUES(
	[s].[Id]
	, [s].[IsDeleted]
	, [s].[CampaignId]
	, [s].[LeadId]
	, [s].[ContactId]
	, [s].[Status]
	, [s].[HasResponded]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[FirstRespondedDate]
	, [s].[CurrencyIsoCode]
	, [s].[Salutation]
	, [s].[Name]
	, [s].[FirstName]
	, [s].[LastName]
	, [s].[Title]
	, [s].[Street]
	, [s].[City]
	, [s].[State]
	, [s].[PostalCode]
	, [s].[Country]
	, [s].[Email]
	, [s].[Phone]
	, [s].[Fax]
	, [s].[MobilePhone]
	, [s].[Description]
	, [s].[DoNotCall]
	, [s].[HasOptedOutOfEmail]
	, [s].[HasOptedOutOfFax]
	, [s].[LeadSource]
	, [s].[CompanyOrAccount]
	, [s].[Type]
	, [s].[LeadOrContactId]
	, [s].[LeadOrContactOwnerId]
	, [s].[Opportunity__c]
	, [s].[SourceCode__c]
	, [s].[Device_Type__c]
	, [s].[Do_Not_Call_from_Lead_Contact__c]
	, [s].[Last_Activity_Date__c]
	, [s].[Lead_Status__c]
	, [s].[Time_Zone__c]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[CampaignMember] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
