/* CreateDate: 03/17/2022 15:12:22.593 , ModifyDate: 03/17/2022 15:12:22.593 */
GO
CREATE PROCEDURE [SF].[sp_WorkOrderLineItem_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[WorkOrderLineItem])
RETURN ;

BEGIN TRY
;MERGE [SF].[WorkOrderLineItem] AS [t]
USING [SFStaging].[WorkOrderLineItem] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[IsDeleted] = [t].[IsDeleted]
	, [t].[LineItemNumber] = [t].[LineItemNumber]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[WorkOrderId] = [t].[WorkOrderId]
	, [t].[ParentWorkOrderLineItemId] = [t].[ParentWorkOrderLineItemId]
	, [t].[Product2Id] = [t].[Product2Id]
	, [t].[AssetId] = [t].[AssetId]
	, [t].[OrderId] = [t].[OrderId]
	, [t].[RootWorkOrderLineItemId] = [t].[RootWorkOrderLineItemId]
	, [t].[Description] = [t].[Description]
	, [t].[StartDate] = [t].[StartDate]
	, [t].[EndDate] = [t].[EndDate]
	, [t].[Status] = [t].[Status]
	, [t].[PricebookEntryId] = [t].[PricebookEntryId]
	, [t].[Quantity] = [t].[Quantity]
	, [t].[UnitPrice] = [t].[UnitPrice]
	, [t].[Discount] = [t].[Discount]
	, [t].[ListPrice] = [t].[ListPrice]
	, [t].[Subtotal] = [t].[Subtotal]
	, [t].[TotalPrice] = [t].[TotalPrice]
	, [t].[Duration] = [t].[Duration]
	, [t].[DurationType] = [t].[DurationType]
	, [t].[DurationInMinutes] = [t].[DurationInMinutes]
	, [t].[WorkTypeId] = [t].[WorkTypeId]
	, [t].[Street] = [t].[Street]
	, [t].[City] = [t].[City]
	, [t].[State] = [t].[State]
	, [t].[PostalCode] = [t].[PostalCode]
	, [t].[Country] = [t].[Country]
	, [t].[StateCode] = [t].[StateCode]
	, [t].[CountryCode] = [t].[CountryCode]
	, [t].[Latitude] = [t].[Latitude]
	, [t].[Longitude] = [t].[Longitude]
	, [t].[GeocodeAccuracy] = [t].[GeocodeAccuracy]
	, [t].[Address] = [t].[Address]
	, [t].[ServiceTerritoryId] = [t].[ServiceTerritoryId]
	, [t].[Subject] = [t].[Subject]
	, [t].[StatusCategory] = [t].[StatusCategory]
	, [t].[IsClosed] = [t].[IsClosed]
	, [t].[Priority] = [t].[Priority]
	, [t].[ServiceAppointmentCount] = [t].[ServiceAppointmentCount]
	, [t].[LocationId] = [t].[LocationId]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [IsDeleted]
	, [LineItemNumber]
	, [CurrencyIsoCode]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [WorkOrderId]
	, [ParentWorkOrderLineItemId]
	, [Product2Id]
	, [AssetId]
	, [OrderId]
	, [RootWorkOrderLineItemId]
	, [Description]
	, [StartDate]
	, [EndDate]
	, [Status]
	, [PricebookEntryId]
	, [Quantity]
	, [UnitPrice]
	, [Discount]
	, [ListPrice]
	, [Subtotal]
	, [TotalPrice]
	, [Duration]
	, [DurationType]
	, [DurationInMinutes]
	, [WorkTypeId]
	, [Street]
	, [City]
	, [State]
	, [PostalCode]
	, [Country]
	, [StateCode]
	, [CountryCode]
	, [Latitude]
	, [Longitude]
	, [GeocodeAccuracy]
	, [Address]
	, [ServiceTerritoryId]
	, [Subject]
	, [StatusCategory]
	, [IsClosed]
	, [Priority]
	, [ServiceAppointmentCount]
	, [LocationId]
	)
	VALUES(
	[s].[Id]
	, [s].[IsDeleted]
	, [s].[LineItemNumber]
	, [s].[CurrencyIsoCode]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[WorkOrderId]
	, [s].[ParentWorkOrderLineItemId]
	, [s].[Product2Id]
	, [s].[AssetId]
	, [s].[OrderId]
	, [s].[RootWorkOrderLineItemId]
	, [s].[Description]
	, [s].[StartDate]
	, [s].[EndDate]
	, [s].[Status]
	, [s].[PricebookEntryId]
	, [s].[Quantity]
	, [s].[UnitPrice]
	, [s].[Discount]
	, [s].[ListPrice]
	, [s].[Subtotal]
	, [s].[TotalPrice]
	, [s].[Duration]
	, [s].[DurationType]
	, [s].[DurationInMinutes]
	, [s].[WorkTypeId]
	, [s].[Street]
	, [s].[City]
	, [s].[State]
	, [s].[PostalCode]
	, [s].[Country]
	, [s].[StateCode]
	, [s].[CountryCode]
	, [s].[Latitude]
	, [s].[Longitude]
	, [s].[GeocodeAccuracy]
	, [s].[Address]
	, [s].[ServiceTerritoryId]
	, [s].[Subject]
	, [s].[StatusCategory]
	, [s].[IsClosed]
	, [s].[Priority]
	, [s].[ServiceAppointmentCount]
	, [s].[LocationId]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[WorkOrderLineItem] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
