/* CreateDate: 03/17/2022 15:12:22.543 , ModifyDate: 03/17/2022 15:12:22.543 */
GO
CREATE PROCEDURE [SF].[sp_WorkOrder_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[WorkOrder])
RETURN ;

BEGIN TRY
;MERGE [SF].[WorkOrder] AS [t]
USING [SFStaging].[WorkOrder] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[OwnerId] = [t].[OwnerId]
	, [t].[IsDeleted] = [t].[IsDeleted]
	, [t].[WorkOrderNumber] = [t].[WorkOrderNumber]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[ContactId] = [t].[ContactId]
	, [t].[CaseId] = [t].[CaseId]
	, [t].[EntitlementId] = [t].[EntitlementId]
	, [t].[ServiceContractId] = [t].[ServiceContractId]
	, [t].[AssetId] = [t].[AssetId]
	, [t].[Street] = [t].[Street]
	, [t].[City] = [t].[City]
	, [t].[State] = [t].[State]
	, [t].[PostalCode] = [t].[PostalCode]
	, [t].[Country] = [t].[Country]
	, [t].[StateCode] = [t].[StateCode]
	, [t].[CountryCode] = [t].[CountryCode]
	, [t].[Latitude] = [t].[Latitude]
	, [t].[Longitude] = [t].[Longitude]
	, [t].[GeocodeAccuracy] = [t].[GeocodeAccuracy]
	, [t].[Address] = [t].[Address]
	, [t].[Description] = [t].[Description]
	, [t].[StartDate] = [t].[StartDate]
	, [t].[EndDate] = [t].[EndDate]
	, [t].[Subject] = [t].[Subject]
	, [t].[RootWorkOrderId] = [t].[RootWorkOrderId]
	, [t].[Status] = [t].[Status]
	, [t].[Priority] = [t].[Priority]
	, [t].[Tax] = [t].[Tax]
	, [t].[Subtotal] = [t].[Subtotal]
	, [t].[TotalPrice] = [t].[TotalPrice]
	, [t].[LineItemCount] = [t].[LineItemCount]
	, [t].[Pricebook2Id] = [t].[Pricebook2Id]
	, [t].[Discount] = [t].[Discount]
	, [t].[GrandTotal] = [t].[GrandTotal]
	, [t].[ParentWorkOrderId] = [t].[ParentWorkOrderId]
	, [t].[IsClosed] = [t].[IsClosed]
	, [t].[IsStopped] = [t].[IsStopped]
	, [t].[StopStartDate] = [t].[StopStartDate]
	, [t].[SlaStartDate] = [t].[SlaStartDate]
	, [t].[SlaExitDate] = [t].[SlaExitDate]
	, [t].[BusinessHoursId] = [t].[BusinessHoursId]
	, [t].[MilestoneStatus] = [t].[MilestoneStatus]
	, [t].[Duration] = [t].[Duration]
	, [t].[DurationType] = [t].[DurationType]
	, [t].[DurationInMinutes] = [t].[DurationInMinutes]
	, [t].[ServiceAppointmentCount] = [t].[ServiceAppointmentCount]
	, [t].[WorkTypeId] = [t].[WorkTypeId]
	, [t].[ServiceTerritoryId] = [t].[ServiceTerritoryId]
	, [t].[StatusCategory] = [t].[StatusCategory]
	, [t].[LocationId] = [t].[LocationId]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [OwnerId]
	, [IsDeleted]
	, [WorkOrderNumber]
	, [CurrencyIsoCode]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [AccountId]
	, [ContactId]
	, [CaseId]
	, [EntitlementId]
	, [ServiceContractId]
	, [AssetId]
	, [Street]
	, [City]
	, [State]
	, [PostalCode]
	, [Country]
	, [StateCode]
	, [CountryCode]
	, [Latitude]
	, [Longitude]
	, [GeocodeAccuracy]
	, [Address]
	, [Description]
	, [StartDate]
	, [EndDate]
	, [Subject]
	, [RootWorkOrderId]
	, [Status]
	, [Priority]
	, [Tax]
	, [Subtotal]
	, [TotalPrice]
	, [LineItemCount]
	, [Pricebook2Id]
	, [Discount]
	, [GrandTotal]
	, [ParentWorkOrderId]
	, [IsClosed]
	, [IsStopped]
	, [StopStartDate]
	, [SlaStartDate]
	, [SlaExitDate]
	, [BusinessHoursId]
	, [MilestoneStatus]
	, [Duration]
	, [DurationType]
	, [DurationInMinutes]
	, [ServiceAppointmentCount]
	, [WorkTypeId]
	, [ServiceTerritoryId]
	, [StatusCategory]
	, [LocationId]
	)
	VALUES(
	[s].[Id]
	, [s].[OwnerId]
	, [s].[IsDeleted]
	, [s].[WorkOrderNumber]
	, [s].[CurrencyIsoCode]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[AccountId]
	, [s].[ContactId]
	, [s].[CaseId]
	, [s].[EntitlementId]
	, [s].[ServiceContractId]
	, [s].[AssetId]
	, [s].[Street]
	, [s].[City]
	, [s].[State]
	, [s].[PostalCode]
	, [s].[Country]
	, [s].[StateCode]
	, [s].[CountryCode]
	, [s].[Latitude]
	, [s].[Longitude]
	, [s].[GeocodeAccuracy]
	, [s].[Address]
	, [s].[Description]
	, [s].[StartDate]
	, [s].[EndDate]
	, [s].[Subject]
	, [s].[RootWorkOrderId]
	, [s].[Status]
	, [s].[Priority]
	, [s].[Tax]
	, [s].[Subtotal]
	, [s].[TotalPrice]
	, [s].[LineItemCount]
	, [s].[Pricebook2Id]
	, [s].[Discount]
	, [s].[GrandTotal]
	, [s].[ParentWorkOrderId]
	, [s].[IsClosed]
	, [s].[IsStopped]
	, [s].[StopStartDate]
	, [s].[SlaStartDate]
	, [s].[SlaExitDate]
	, [s].[BusinessHoursId]
	, [s].[MilestoneStatus]
	, [s].[Duration]
	, [s].[DurationType]
	, [s].[DurationInMinutes]
	, [s].[ServiceAppointmentCount]
	, [s].[WorkTypeId]
	, [s].[ServiceTerritoryId]
	, [s].[StatusCategory]
	, [s].[LocationId]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[WorkOrder] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
