/* CreateDate: 03/04/2022 08:19:53.910 , ModifyDate: 03/04/2022 08:19:53.910 */
GO
CREATE PROCEDURE [SF].[sp_ServiceContract_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[ServiceContract])
RETURN ;

SET XACT_ABORT ON

BEGIN TRANSACTION

;MERGE [SF].[ServiceContract] AS [t]
USING [SFStaging].[ServiceContract] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[OwnerId] = [t].[OwnerId]
	, [t].[IsDeleted] = [t].[IsDeleted]
	, [t].[Name] = [t].[Name]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[ContactId] = [t].[ContactId]
	, [t].[Term] = [t].[Term]
	, [t].[StartDate] = [t].[StartDate]
	, [t].[EndDate] = [t].[EndDate]
	, [t].[ActivationDate] = [t].[ActivationDate]
	, [t].[ApprovalStatus] = [t].[ApprovalStatus]
	, [t].[Description] = [t].[Description]
	, [t].[BillingStreet] = [t].[BillingStreet]
	, [t].[BillingCity] = [t].[BillingCity]
	, [t].[BillingState] = [t].[BillingState]
	, [t].[BillingPostalCode] = [t].[BillingPostalCode]
	, [t].[BillingCountry] = [t].[BillingCountry]
	, [t].[BillingStateCode] = [t].[BillingStateCode]
	, [t].[BillingCountryCode] = [t].[BillingCountryCode]
	, [t].[BillingLatitude] = [t].[BillingLatitude]
	, [t].[BillingLongitude] = [t].[BillingLongitude]
	, [t].[BillingGeocodeAccuracy] = [t].[BillingGeocodeAccuracy]
	, [t].[BillingAddress] = [t].[BillingAddress]
	, [t].[ShippingStreet] = [t].[ShippingStreet]
	, [t].[ShippingCity] = [t].[ShippingCity]
	, [t].[ShippingState] = [t].[ShippingState]
	, [t].[ShippingPostalCode] = [t].[ShippingPostalCode]
	, [t].[ShippingCountry] = [t].[ShippingCountry]
	, [t].[ShippingStateCode] = [t].[ShippingStateCode]
	, [t].[ShippingCountryCode] = [t].[ShippingCountryCode]
	, [t].[ShippingLatitude] = [t].[ShippingLatitude]
	, [t].[ShippingLongitude] = [t].[ShippingLongitude]
	, [t].[ShippingGeocodeAccuracy] = [t].[ShippingGeocodeAccuracy]
	, [t].[ShippingAddress] = [t].[ShippingAddress]
	, [t].[Pricebook2Id] = [t].[Pricebook2Id]
	, [t].[ShippingHandling] = [t].[ShippingHandling]
	, [t].[Tax] = [t].[Tax]
	, [t].[Subtotal] = [t].[Subtotal]
	, [t].[TotalPrice] = [t].[TotalPrice]
	, [t].[LineItemCount] = [t].[LineItemCount]
	, [t].[ContractNumber] = [t].[ContractNumber]
	, [t].[SpecialTerms] = [t].[SpecialTerms]
	, [t].[Discount] = [t].[Discount]
	, [t].[GrandTotal] = [t].[GrandTotal]
	, [t].[Status] = [t].[Status]
	, [t].[ParentServiceContractId] = [t].[ParentServiceContractId]
	, [t].[RootServiceContractId] = [t].[RootServiceContractId]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [OwnerId]
	, [IsDeleted]
	, [Name]
	, [CurrencyIsoCode]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [AccountId]
	, [ContactId]
	, [Term]
	, [StartDate]
	, [EndDate]
	, [ActivationDate]
	, [ApprovalStatus]
	, [Description]
	, [BillingStreet]
	, [BillingCity]
	, [BillingState]
	, [BillingPostalCode]
	, [BillingCountry]
	, [BillingStateCode]
	, [BillingCountryCode]
	, [BillingLatitude]
	, [BillingLongitude]
	, [BillingGeocodeAccuracy]
	, [BillingAddress]
	, [ShippingStreet]
	, [ShippingCity]
	, [ShippingState]
	, [ShippingPostalCode]
	, [ShippingCountry]
	, [ShippingStateCode]
	, [ShippingCountryCode]
	, [ShippingLatitude]
	, [ShippingLongitude]
	, [ShippingGeocodeAccuracy]
	, [ShippingAddress]
	, [Pricebook2Id]
	, [ShippingHandling]
	, [Tax]
	, [Subtotal]
	, [TotalPrice]
	, [LineItemCount]
	, [ContractNumber]
	, [SpecialTerms]
	, [Discount]
	, [GrandTotal]
	, [Status]
	, [ParentServiceContractId]
	, [RootServiceContractId]
	)
	VALUES(
	[s].[Id]
	, [s].[OwnerId]
	, [s].[IsDeleted]
	, [s].[Name]
	, [s].[CurrencyIsoCode]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[AccountId]
	, [s].[ContactId]
	, [s].[Term]
	, [s].[StartDate]
	, [s].[EndDate]
	, [s].[ActivationDate]
	, [s].[ApprovalStatus]
	, [s].[Description]
	, [s].[BillingStreet]
	, [s].[BillingCity]
	, [s].[BillingState]
	, [s].[BillingPostalCode]
	, [s].[BillingCountry]
	, [s].[BillingStateCode]
	, [s].[BillingCountryCode]
	, [s].[BillingLatitude]
	, [s].[BillingLongitude]
	, [s].[BillingGeocodeAccuracy]
	, [s].[BillingAddress]
	, [s].[ShippingStreet]
	, [s].[ShippingCity]
	, [s].[ShippingState]
	, [s].[ShippingPostalCode]
	, [s].[ShippingCountry]
	, [s].[ShippingStateCode]
	, [s].[ShippingCountryCode]
	, [s].[ShippingLatitude]
	, [s].[ShippingLongitude]
	, [s].[ShippingGeocodeAccuracy]
	, [s].[ShippingAddress]
	, [s].[Pricebook2Id]
	, [s].[ShippingHandling]
	, [s].[Tax]
	, [s].[Subtotal]
	, [s].[TotalPrice]
	, [s].[LineItemCount]
	, [s].[ContractNumber]
	, [s].[SpecialTerms]
	, [s].[Discount]
	, [s].[GrandTotal]
	, [s].[Status]
	, [s].[ParentServiceContractId]
	, [s].[RootServiceContractId]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[ServiceContract] ;

COMMIT ;
GO
