/* CreateDate: 03/17/2022 15:12:21.450 , ModifyDate: 03/17/2022 15:12:21.450 */
GO
CREATE PROCEDURE [SF].[sp_Opportunity_Merge]
	@ROWCOUNT BIGINT = NULL OUTPUT
AS
SET NOCOUNT ON

SET @ROWCOUNT = 0

IF NOT EXISTS(SELECT 1 FROM [SFStaging].[Opportunity])
RETURN ;

BEGIN TRY
;MERGE [SF].[Opportunity] AS [t]
USING [SFStaging].[Opportunity] AS [s]
	ON [t].[Id] = [s].[Id]
WHEN MATCHED THEN
	UPDATE SET
	[t].[IsDeleted] = [t].[IsDeleted]
	, [t].[AccountId] = [t].[AccountId]
	, [t].[RecordTypeId] = [t].[RecordTypeId]
	, [t].[IsPrivate] = [t].[IsPrivate]
	, [t].[Name] = [t].[Name]
	, [t].[Description] = [t].[Description]
	, [t].[StageName] = [t].[StageName]
	, [t].[Amount] = [t].[Amount]
	, [t].[Probability] = [t].[Probability]
	, [t].[ExpectedRevenue] = [t].[ExpectedRevenue]
	, [t].[TotalOpportunityQuantity] = [t].[TotalOpportunityQuantity]
	, [t].[CloseDate] = [t].[CloseDate]
	, [t].[Type] = [t].[Type]
	, [t].[NextStep] = [t].[NextStep]
	, [t].[LeadSource] = [t].[LeadSource]
	, [t].[IsClosed] = [t].[IsClosed]
	, [t].[IsWon] = [t].[IsWon]
	, [t].[ForecastCategory] = [t].[ForecastCategory]
	, [t].[ForecastCategoryName] = [t].[ForecastCategoryName]
	, [t].[CurrencyIsoCode] = [t].[CurrencyIsoCode]
	, [t].[CampaignId] = [t].[CampaignId]
	, [t].[HasOpportunityLineItem] = [t].[HasOpportunityLineItem]
	, [t].[Pricebook2Id] = [t].[Pricebook2Id]
	, [t].[OwnerId] = [t].[OwnerId]
	, [t].[Territory2Id] = [t].[Territory2Id]
	, [t].[IsExcludedFromTerritory2Filter] = [t].[IsExcludedFromTerritory2Filter]
	, [t].[CreatedDate] = [t].[CreatedDate]
	, [t].[CreatedById] = [t].[CreatedById]
	, [t].[LastModifiedDate] = [t].[LastModifiedDate]
	, [t].[LastModifiedById] = [t].[LastModifiedById]
	, [t].[SystemModstamp] = [t].[SystemModstamp]
	, [t].[LastActivityDate] = [t].[LastActivityDate]
	, [t].[PushCount] = [t].[PushCount]
	, [t].[LastStageChangeDate] = [t].[LastStageChangeDate]
	, [t].[FiscalQuarter] = [t].[FiscalQuarter]
	, [t].[FiscalYear] = [t].[FiscalYear]
	, [t].[Fiscal] = [t].[Fiscal]
	, [t].[ContactId] = [t].[ContactId]
	, [t].[LastViewedDate] = [t].[LastViewedDate]
	, [t].[LastReferencedDate] = [t].[LastReferencedDate]
	, [t].[SyncedQuoteId] = [t].[SyncedQuoteId]
	, [t].[ContractId] = [t].[ContractId]
	, [t].[HasOpenActivity] = [t].[HasOpenActivity]
	, [t].[HasOverdueTask] = [t].[HasOverdueTask]
	, [t].[IqScore] = [t].[IqScore]
	, [t].[LastAmountChangedHistoryId] = [t].[LastAmountChangedHistoryId]
	, [t].[LastCloseDateChangedHistoryId] = [t].[LastCloseDateChangedHistoryId]
	, [t].[Budget_Confirmed__c] = [t].[Budget_Confirmed__c]
	, [t].[Discovery_Completed__c] = [t].[Discovery_Completed__c]
	, [t].[ROI_Analysis_Completed__c] = [t].[ROI_Analysis_Completed__c]
	, [t].[Appointment_Source__c] = [t].[Appointment_Source__c]
	, [t].[Loss_Reason__c] = [t].[Loss_Reason__c]
	, [t].[Cancellation_Reason__c] = [t].[Cancellation_Reason__c]
	, [t].[Hair_Loss_Experience__c] = [t].[Hair_Loss_Experience__c]
	, [t].[Hair_Loss_Family__c] = [t].[Hair_Loss_Family__c]
	, [t].[Hair_Loss_Or_Volume__c] = [t].[Hair_Loss_Or_Volume__c]
	, [t].[Hair_Loss_Product_Other__c] = [t].[Hair_Loss_Product_Other__c]
	, [t].[Hair_Loss_Product_Used__c] = [t].[Hair_Loss_Product_Used__c]
	, [t].[Hair_Loss_Spot__c] = [t].[Hair_Loss_Spot__c]
	, [t].[IP_Address__c] = [t].[IP_Address__c]
	, [t].[Ludwig_Scale__c] = [t].[Ludwig_Scale__c]
	, [t].[Norwood_Scale__c] = [t].[Norwood_Scale__c]
	, [t].[Referral_Code_Expiration_Date__c] = [t].[Referral_Code_Expiration_Date__c]
	, [t].[Referral_Code__c] = [t].[Referral_Code__c]
	, [t].[Service_Territory__c] = [t].[Service_Territory__c]
	, [t].[DB_Competitor__c] = [t].[DB_Competitor__c]
	, [t].[Source_Code__c] = [t].[Source_Code__c]
	, [t].[Submitted_for_Approval__c] = [t].[Submitted_for_Approval__c]
	, [t].[Ammount__c] = [t].[Ammount__c]
	, [t].[GCLID__c] = [t].[GCLID__c]
	, [t].[Promo_Code__c] = [t].[Promo_Code__c]
	, [t].[SolutionOffered__c] = [t].[SolutionOffered__c]
	, [t].[Approver__c] = [t].[Approver__c]
	, [t].[Email__c] = [t].[Email__c]
	, [t].[Goals_Expectations__c] = [t].[Goals_Expectations__c]
	, [t].[How_many_times_a_week_do_you_think__c] = [t].[How_many_times_a_week_do_you_think__c]
	, [t].[How_much_time_a_week_do_you_spend__c] = [t].[How_much_time_a_week_do_you_spend__c]
	, [t].[Mobile__c] = [t].[Mobile__c]
	, [t].[Opportunity_Owner__c] = [t].[Opportunity_Owner__c]
	, [t].[Other_Reason__c] = [t].[Other_Reason__c]
	, [t].[Owner__c] = [t].[Owner__c]
	, [t].[Phone__c] = [t].[Phone__c]
	, [t].[What_are_your_main_concerns_today__c] = [t].[What_are_your_main_concerns_today__c]
	, [t].[What_else_would_be_helpful_for_your__c] = [t].[What_else_would_be_helpful_for_your__c]
	, [t].[What_methods_have_you_used_or_currently__c] = [t].[What_methods_have_you_used_or_currently__c]
	, [t].[RefersionLogId__c] = [t].[RefersionLogId__c]
	, [t].[Commission_Paid__c] = [t].[Commission_Paid__c]
	, [t].[Owner_Division__c] = [t].[Owner_Division__c]
	, [t].[Service_Territory_Number__c] = [t].[Service_Territory_Number__c]
	, [t].[Commission_Override__c] = [t].[Commission_Override__c]
WHEN NOT MATCHED THEN
	INSERT(
	[Id]
	, [IsDeleted]
	, [AccountId]
	, [RecordTypeId]
	, [IsPrivate]
	, [Name]
	, [Description]
	, [StageName]
	, [Amount]
	, [Probability]
	, [ExpectedRevenue]
	, [TotalOpportunityQuantity]
	, [CloseDate]
	, [Type]
	, [NextStep]
	, [LeadSource]
	, [IsClosed]
	, [IsWon]
	, [ForecastCategory]
	, [ForecastCategoryName]
	, [CurrencyIsoCode]
	, [CampaignId]
	, [HasOpportunityLineItem]
	, [Pricebook2Id]
	, [OwnerId]
	, [Territory2Id]
	, [IsExcludedFromTerritory2Filter]
	, [CreatedDate]
	, [CreatedById]
	, [LastModifiedDate]
	, [LastModifiedById]
	, [SystemModstamp]
	, [LastActivityDate]
	, [PushCount]
	, [LastStageChangeDate]
	, [FiscalQuarter]
	, [FiscalYear]
	, [Fiscal]
	, [ContactId]
	, [LastViewedDate]
	, [LastReferencedDate]
	, [SyncedQuoteId]
	, [ContractId]
	, [HasOpenActivity]
	, [HasOverdueTask]
	, [IqScore]
	, [LastAmountChangedHistoryId]
	, [LastCloseDateChangedHistoryId]
	, [Budget_Confirmed__c]
	, [Discovery_Completed__c]
	, [ROI_Analysis_Completed__c]
	, [Appointment_Source__c]
	, [Loss_Reason__c]
	, [Cancellation_Reason__c]
	, [Hair_Loss_Experience__c]
	, [Hair_Loss_Family__c]
	, [Hair_Loss_Or_Volume__c]
	, [Hair_Loss_Product_Other__c]
	, [Hair_Loss_Product_Used__c]
	, [Hair_Loss_Spot__c]
	, [IP_Address__c]
	, [Ludwig_Scale__c]
	, [Norwood_Scale__c]
	, [Referral_Code_Expiration_Date__c]
	, [Referral_Code__c]
	, [Service_Territory__c]
	, [DB_Competitor__c]
	, [Source_Code__c]
	, [Submitted_for_Approval__c]
	, [Ammount__c]
	, [GCLID__c]
	, [Promo_Code__c]
	, [SolutionOffered__c]
	, [Approver__c]
	, [Email__c]
	, [Goals_Expectations__c]
	, [How_many_times_a_week_do_you_think__c]
	, [How_much_time_a_week_do_you_spend__c]
	, [Mobile__c]
	, [Opportunity_Owner__c]
	, [Other_Reason__c]
	, [Owner__c]
	, [Phone__c]
	, [What_are_your_main_concerns_today__c]
	, [What_else_would_be_helpful_for_your__c]
	, [What_methods_have_you_used_or_currently__c]
	, [RefersionLogId__c]
	, [Commission_Paid__c]
	, [Owner_Division__c]
	, [Service_Territory_Number__c]
	, [Commission_Override__c]
	)
	VALUES(
	[s].[Id]
	, [s].[IsDeleted]
	, [s].[AccountId]
	, [s].[RecordTypeId]
	, [s].[IsPrivate]
	, [s].[Name]
	, [s].[Description]
	, [s].[StageName]
	, [s].[Amount]
	, [s].[Probability]
	, [s].[ExpectedRevenue]
	, [s].[TotalOpportunityQuantity]
	, [s].[CloseDate]
	, [s].[Type]
	, [s].[NextStep]
	, [s].[LeadSource]
	, [s].[IsClosed]
	, [s].[IsWon]
	, [s].[ForecastCategory]
	, [s].[ForecastCategoryName]
	, [s].[CurrencyIsoCode]
	, [s].[CampaignId]
	, [s].[HasOpportunityLineItem]
	, [s].[Pricebook2Id]
	, [s].[OwnerId]
	, [s].[Territory2Id]
	, [s].[IsExcludedFromTerritory2Filter]
	, [s].[CreatedDate]
	, [s].[CreatedById]
	, [s].[LastModifiedDate]
	, [s].[LastModifiedById]
	, [s].[SystemModstamp]
	, [s].[LastActivityDate]
	, [s].[PushCount]
	, [s].[LastStageChangeDate]
	, [s].[FiscalQuarter]
	, [s].[FiscalYear]
	, [s].[Fiscal]
	, [s].[ContactId]
	, [s].[LastViewedDate]
	, [s].[LastReferencedDate]
	, [s].[SyncedQuoteId]
	, [s].[ContractId]
	, [s].[HasOpenActivity]
	, [s].[HasOverdueTask]
	, [s].[IqScore]
	, [s].[LastAmountChangedHistoryId]
	, [s].[LastCloseDateChangedHistoryId]
	, [s].[Budget_Confirmed__c]
	, [s].[Discovery_Completed__c]
	, [s].[ROI_Analysis_Completed__c]
	, [s].[Appointment_Source__c]
	, [s].[Loss_Reason__c]
	, [s].[Cancellation_Reason__c]
	, [s].[Hair_Loss_Experience__c]
	, [s].[Hair_Loss_Family__c]
	, [s].[Hair_Loss_Or_Volume__c]
	, [s].[Hair_Loss_Product_Other__c]
	, [s].[Hair_Loss_Product_Used__c]
	, [s].[Hair_Loss_Spot__c]
	, [s].[IP_Address__c]
	, [s].[Ludwig_Scale__c]
	, [s].[Norwood_Scale__c]
	, [s].[Referral_Code_Expiration_Date__c]
	, [s].[Referral_Code__c]
	, [s].[Service_Territory__c]
	, [s].[DB_Competitor__c]
	, [s].[Source_Code__c]
	, [s].[Submitted_for_Approval__c]
	, [s].[Ammount__c]
	, [s].[GCLID__c]
	, [s].[Promo_Code__c]
	, [s].[SolutionOffered__c]
	, [s].[Approver__c]
	, [s].[Email__c]
	, [s].[Goals_Expectations__c]
	, [s].[How_many_times_a_week_do_you_think__c]
	, [s].[How_much_time_a_week_do_you_spend__c]
	, [s].[Mobile__c]
	, [s].[Opportunity_Owner__c]
	, [s].[Other_Reason__c]
	, [s].[Owner__c]
	, [s].[Phone__c]
	, [s].[What_are_your_main_concerns_today__c]
	, [s].[What_else_would_be_helpful_for_your__c]
	, [s].[What_methods_have_you_used_or_currently__c]
	, [s].[RefersionLogId__c]
	, [s].[Commission_Paid__c]
	, [s].[Owner_Division__c]
	, [s].[Service_Territory_Number__c]
	, [s].[Commission_Override__c]
	)
OPTION(RECOMPILE) ;

SET @ROWCOUNT = @@ROWCOUNT ;

TRUNCATE TABLE [SFStaging].[Opportunity] ;

END TRY
BEGIN CATCH
	THROW ;
END CATCH
GO
