/* CreateDate: 07/30/2015 15:49:41.950 , ModifyDate: 11/08/2018 11:07:20.603 */
GO
CREATE TABLE [dbo].[MediaSourceLevel05](
	[Level05ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Level05CreativeCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Level05Creative] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MediaSourceLevel05] PRIMARY KEY CLUSTERED
(
	[Level05ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
