/* CreateDate: 07/30/2015 15:49:41.907 , ModifyDate: 11/08/2018 11:07:20.973 */
GO
CREATE TABLE [dbo].[MediaSourceLevel04](
	[Level04ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Level04FormatCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Level04Format] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MediaID] [smallint] NULL,
 CONSTRAINT [PK_MediaSourceLevel04] PRIMARY KEY CLUSTERED
(
	[Level04ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
