/* CreateDate: 07/30/2015 15:49:41.867 , ModifyDate: 11/08/2018 11:07:21.013 */
GO
CREATE TABLE [dbo].[MediaSourceLevel03](
	[Level03ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Level03LanguageCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Level03Language] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MediaID] [smallint] NULL,
 CONSTRAINT [PK_Level02ID] PRIMARY KEY CLUSTERED
(
	[Level03ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
