/* CreateDate: 07/30/2015 15:49:41.987 , ModifyDate: 11/08/2018 11:07:20.507 */
GO
CREATE TABLE [dbo].[MediaSourceMediaTypes](
	[MediaID] [smallint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MediaCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Media] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MediaID] PRIMARY KEY CLUSTERED
(
	[MediaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
