/* CreateDate: 07/25/2018 13:53:36.680 , ModifyDate: 07/25/2018 13:53:36.680 */
GO
create procedure [dbo].[sp_MSupd_dboonca_action]     @c1 nchar(10) = NULL,     @c2 nchar(50) = NULL,     @c3 nchar(10) = NULL,     @c4 nchar(10) = NULL,     @c5 nchar(1) = NULL,     @c6 nchar(1) = NULL,     @c7 nchar(1) = NULL,     @c8 nchar(1) = NULL,     @c9 nchar(1) = NULL,     @c10 nchar(30) = NULL,     @c11 nchar(10) = NULL,     @c12 nchar(1) = NULL,     @c13 int = NULL,     @c14 nchar(1) = NULL,     @c15 nchar(1) = NULL,     @c16 nchar(1) = NULL,     @c17 nchar(10) = NULL,     @pkc1 nchar(10) = NULL,     @bitmap binary(3)
as
begin   if (substring(@bitmap,1,1) & 1 = 1)
begin  update [dbo].[onca_action] set     [action_code] = case substring(@bitmap,1,1) & 1 when 1 then @c1 else [action_code] end,     [description] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [description] end,     [action_type_code] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [action_type_code] end,     [chain_id] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [chain_id] end,     [schedule_type] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [schedule_type] end,     [prompt_for_schedule] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [prompt_for_schedule] end,     [available_to_outlook] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [available_to_outlook] end,     [available_to_mobile] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [available_to_mobile] end,     [prompt_for_next] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [prompt_for_next] end,     [source_code] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [source_code] end,     [campaign_code] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [campaign_code] end,     [active] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [active] end,     [sort_order] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [sort_order] end,     [cst_noble_exclusion] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [cst_noble_exclusion] end,     [cst_noble_addition] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [cst_noble_addition] end,     [cst_is_outbound_call] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [cst_is_outbound_call] end,     [cst_category_code] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [cst_category_code] end
where [action_code] = @pkc1 if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598 end   else
begin  update [dbo].[onca_action] set     [description] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [description] end,     [action_type_code] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [action_type_code] end,     [chain_id] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [chain_id] end,     [schedule_type] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [schedule_type] end,     [prompt_for_schedule] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [prompt_for_schedule] end,     [available_to_outlook] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [available_to_outlook] end,     [available_to_mobile] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [available_to_mobile] end,     [prompt_for_next] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [prompt_for_next] end,     [source_code] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [source_code] end,     [campaign_code] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [campaign_code] end,     [active] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [active] end,     [sort_order] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [sort_order] end,     [cst_noble_exclusion] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [cst_noble_exclusion] end,     [cst_noble_addition] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [cst_noble_addition] end,     [cst_is_outbound_call] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [cst_is_outbound_call] end,     [cst_category_code] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [cst_category_code] end
where [action_code] = @pkc1 if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598 end  end   --
GO
