/* CreateDate: 01/03/2018 16:31:35.070 , ModifyDate: 01/03/2018 16:31:35.070 */
GO
create procedure [dbo].[sp_MSupd_dbocstd_contact_completion]
		@c1 nchar(10) = NULL,
		@c2 nchar(10) = NULL,
		@c3 nchar(20) = NULL,
		@c4 nchar(20) = NULL,
		@c5 nchar(10) = NULL,
		@c6 nchar(10) = NULL,
		@c7 nvarchar(50) = NULL,
		@c8 nchar(1) = NULL,
		@c9 nchar(1) = NULL,
		@c10 nchar(10) = NULL,
		@c11 decimal(15,4) = NULL,
		@c12 nvarchar(50) = NULL,
		@c13 decimal(15,4) = NULL,
		@c14 int = NULL,
		@c15 int = NULL,
		@c16 int = NULL,
		@c17 datetime = NULL,
		@c18 datetime = NULL,
		@c19 nvarchar(1000) = NULL,
		@c20 nvarchar(1000) = NULL,
		@c21 decimal(15,4) = NULL,
		@c22 decimal(15,4) = NULL,
		@c23 nvarchar(10) = NULL,
		@c24 decimal(15,4) = NULL,
		@c25 nvarchar(10) = NULL,
		@c26 nvarchar(50) = NULL,
		@c27 nchar(1) = NULL,
		@c28 datetime = NULL,
		@c29 datetime = NULL,
		@c30 nchar(1) = NULL,
		@c31 ntext = NULL,
		@c32 int = NULL,
		@c33 nvarchar(50) = NULL,
		@c34 nchar(1) = NULL,
		@c35 nchar(1) = NULL,
		@c36 datetime = NULL,
		@c37 datetime = NULL,
		@c38 nchar(10) = NULL,
		@c39 decimal(15,4) = NULL,
		@c40 nchar(1) = NULL,
		@pkc1 nchar(10) = NULL,
		@bitmap binary(5)
as
begin
if (substring(@bitmap,1,1) & 1 = 1)
begin
update [dbo].[cstd_contact_completion] set
		[contact_completion_id] = case substring(@bitmap,1,1) & 1 when 1 then @c1 else [contact_completion_id] end,
		[company_id] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [company_id] end,
		[created_by_user_code] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [created_by_user_code] end,
		[updated_by_user_code] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [updated_by_user_code] end,
		[contact_id] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [contact_id] end,
		[sale_type_code] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [sale_type_code] end,
		[sale_type_description] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [sale_type_description] end,
		[show_no_show_flag] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [show_no_show_flag] end,
		[sale_no_sale_flag] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [sale_no_sale_flag] end,
		[contract_number] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [contract_number] end,
		[contract_amount] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [contract_amount] end,
		[client_number] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [client_number] end,
		[initial_payment] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [initial_payment] end,
		[systems] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [systems] end,
		[services] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [services] end,
		[number_of_graphs] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [number_of_graphs] end,
		[original_appointment_date] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [original_appointment_date] end,
		[date_saved] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [date_saved] end,
		[status_line] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [status_line] end,
		[head_size] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [head_size] end,
		[base_price] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [base_price] end,
		[discount_amount] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [discount_amount] end,
		[discount_percentage] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [discount_percentage] end,
		[balance_amount] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [balance_amount] end,
		[balance_percentage] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [balance_percentage] end,
		[hair_length] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [hair_length] end,
		[reschedule_flag] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [reschedule_flag] end,
		[date_rescheduled] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [date_rescheduled] end,
		[time_rescheduled] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [time_rescheduled] end,
		[discount_markup_flag] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [discount_markup_flag] end,
		[comment] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [comment] end,
		[followup_result_id] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [followup_result_id] end,
		[followup_result] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [followup_result] end,
		[surgery_offered_flag] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [surgery_offered_flag] end,
		[referred_to_doctor_flag] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [referred_to_doctor_flag] end,
		[creation_date] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [creation_date] end,
		[updated_date] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [updated_date] end,
		[activity_id] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [activity_id] end,
		[length_price] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [length_price] end,
		[surgery_consultation_flag] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [surgery_consultation_flag] end
where [contact_completion_id] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end
else
begin
update [dbo].[cstd_contact_completion] set
		[company_id] = case substring(@bitmap,1,1) & 2 when 2 then @c2 else [company_id] end,
		[created_by_user_code] = case substring(@bitmap,1,1) & 4 when 4 then @c3 else [created_by_user_code] end,
		[updated_by_user_code] = case substring(@bitmap,1,1) & 8 when 8 then @c4 else [updated_by_user_code] end,
		[contact_id] = case substring(@bitmap,1,1) & 16 when 16 then @c5 else [contact_id] end,
		[sale_type_code] = case substring(@bitmap,1,1) & 32 when 32 then @c6 else [sale_type_code] end,
		[sale_type_description] = case substring(@bitmap,1,1) & 64 when 64 then @c7 else [sale_type_description] end,
		[show_no_show_flag] = case substring(@bitmap,1,1) & 128 when 128 then @c8 else [show_no_show_flag] end,
		[sale_no_sale_flag] = case substring(@bitmap,2,1) & 1 when 1 then @c9 else [sale_no_sale_flag] end,
		[contract_number] = case substring(@bitmap,2,1) & 2 when 2 then @c10 else [contract_number] end,
		[contract_amount] = case substring(@bitmap,2,1) & 4 when 4 then @c11 else [contract_amount] end,
		[client_number] = case substring(@bitmap,2,1) & 8 when 8 then @c12 else [client_number] end,
		[initial_payment] = case substring(@bitmap,2,1) & 16 when 16 then @c13 else [initial_payment] end,
		[systems] = case substring(@bitmap,2,1) & 32 when 32 then @c14 else [systems] end,
		[services] = case substring(@bitmap,2,1) & 64 when 64 then @c15 else [services] end,
		[number_of_graphs] = case substring(@bitmap,2,1) & 128 when 128 then @c16 else [number_of_graphs] end,
		[original_appointment_date] = case substring(@bitmap,3,1) & 1 when 1 then @c17 else [original_appointment_date] end,
		[date_saved] = case substring(@bitmap,3,1) & 2 when 2 then @c18 else [date_saved] end,
		[status_line] = case substring(@bitmap,3,1) & 4 when 4 then @c19 else [status_line] end,
		[head_size] = case substring(@bitmap,3,1) & 8 when 8 then @c20 else [head_size] end,
		[base_price] = case substring(@bitmap,3,1) & 16 when 16 then @c21 else [base_price] end,
		[discount_amount] = case substring(@bitmap,3,1) & 32 when 32 then @c22 else [discount_amount] end,
		[discount_percentage] = case substring(@bitmap,3,1) & 64 when 64 then @c23 else [discount_percentage] end,
		[balance_amount] = case substring(@bitmap,3,1) & 128 when 128 then @c24 else [balance_amount] end,
		[balance_percentage] = case substring(@bitmap,4,1) & 1 when 1 then @c25 else [balance_percentage] end,
		[hair_length] = case substring(@bitmap,4,1) & 2 when 2 then @c26 else [hair_length] end,
		[reschedule_flag] = case substring(@bitmap,4,1) & 4 when 4 then @c27 else [reschedule_flag] end,
		[date_rescheduled] = case substring(@bitmap,4,1) & 8 when 8 then @c28 else [date_rescheduled] end,
		[time_rescheduled] = case substring(@bitmap,4,1) & 16 when 16 then @c29 else [time_rescheduled] end,
		[discount_markup_flag] = case substring(@bitmap,4,1) & 32 when 32 then @c30 else [discount_markup_flag] end,
		[comment] = case substring(@bitmap,4,1) & 64 when 64 then @c31 else [comment] end,
		[followup_result_id] = case substring(@bitmap,4,1) & 128 when 128 then @c32 else [followup_result_id] end,
		[followup_result] = case substring(@bitmap,5,1) & 1 when 1 then @c33 else [followup_result] end,
		[surgery_offered_flag] = case substring(@bitmap,5,1) & 2 when 2 then @c34 else [surgery_offered_flag] end,
		[referred_to_doctor_flag] = case substring(@bitmap,5,1) & 4 when 4 then @c35 else [referred_to_doctor_flag] end,
		[creation_date] = case substring(@bitmap,5,1) & 8 when 8 then @c36 else [creation_date] end,
		[updated_date] = case substring(@bitmap,5,1) & 16 when 16 then @c37 else [updated_date] end,
		[activity_id] = case substring(@bitmap,5,1) & 32 when 32 then @c38 else [activity_id] end,
		[length_price] = case substring(@bitmap,5,1) & 64 when 64 then @c39 else [length_price] end,
		[surgery_consultation_flag] = case substring(@bitmap,5,1) & 128 when 128 then @c40 else [surgery_consultation_flag] end
where [contact_completion_id] = @pkc1
if @@rowcount = 0
    if @@microsoftversion>0x07320000
        exec sp_MSreplraiserror 20598
end
end
GO
