CREATE TABLE [dbo].[cron](
	[id] [bigint] NOT NULL,
	[userid] [int] NOT NULL,
	[cron_type] [int] NOT NULL,
	[cron_sched] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[cron_data] [bigint] NOT NULL,
	[cron_custom] [varchar](2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[last_ts] [bigint] NOT NULL,
	[next_ts] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [i_cron_ts] ON [dbo].[cron]
(
	[next_ts] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [i_cron_user] ON [dbo].[cron]
(
	[userid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
