/* CreateDate: 08/20/2013 12:22:52.170 , ModifyDate: 08/20/2013 12:22:52.170 */
GO
CREATE TABLE [dbo].[BosleyUpdates](
	[RECORDID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIEBELID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONECTID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACTIVITYID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MRMRS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIRSTNAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LASTNAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 7] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 8] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 9] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 10] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 11] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 12] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 13] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 14] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 15] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 16] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 17] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 18] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 19] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 20] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 21] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 22] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 23] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 24] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 25] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 26] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 27] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 28] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 29] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 30] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 31] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 32] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 33] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 34] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 35] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 36] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 37] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 38] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 39] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 40] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 41] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 42] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 43] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 44] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 45] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Column 46] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
